//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 300.23.11.14.2
//
#ifndef NSURLSessionTaskDelegatePrivate_Protocol_h
#define NSURLSessionTaskDelegatePrivate_Protocol_h
@import Foundation;

@protocol NSURLSessionTaskDelegatePrivate <NSURLSessionTaskDelegate>

@required

@optional

/* optional instance methods */
- (void)URLSession:(id)urlsession _taskIsWaitingForConnection:(id)connection;
- (void)URLSession:(id)urlsession task:(id)task _alternatePathAvailable:(int)available;
- (void)URLSession:(id)urlsession task:(id)task _conditionalRequirementsChanged:(_Bool)changed;
- (void)URLSession:(id)urlsession task:(id)task _didReceiveInformationalResponse:(id)response;
- (void)URLSession:(id)urlsession task:(id)task _isWaitingForConnectionWithError:(id)error;
- (void)URLSession:(id)urlsession task:(id)task _isWaitingForConnectionWithReason:(long long)reason;
- (void)URLSession:(id)urlsession
                 task:(id)task
      _schemeUpgraded:(id)upgraded
    completionHandler:(id /* block */)handler;
- (void)URLSession:(id)urlsession
                                        task:(id)task
    _willSendRequestForEstablishedConnection:(id)connection
                           completionHandler:(id /* block */)handler;

@end

#endif /* NSURLSessionTaskDelegatePrivate_Protocol_h */
