//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 300.23.11.14.2
//
#ifndef PBCodable_h
#define PBCodable_h
@import Foundation;

@interface PBCodable : NSObject <NSSecureCoding>

@property(readonly, nonatomic) NSData *data;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)options;

/* instance methods */
- (id)init;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithData:(id)data;
- (id)dictionaryRepresentation;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (id)formattedText;

@end

#endif /* PBCodable_h */
