//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 300.23.11.14.2
//
#ifndef PBMessageStreamReader_h
#define PBMessageStreamReader_h
@import Foundation;

@interface PBMessageStreamReader : NSObject {
    /* instance variables */
    NSInputStream *_stream;
}

@property(nonatomic) Class classOfNextMessage;
@property(readonly, nonatomic) unsigned long long position;

/* instance methods */
- (id)initWithStream:(id)stream;
- (id)nextMessage;

@end

#endif /* PBMessageStreamReader_h */
