//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 300.23.11.14.2
//
#ifndef PBRequest_h
#define PBRequest_h
@import Foundation;

#include "PBCodable.h"

@interface PBRequest : PBCodable

/* instance methods */
- (unsigned int)requestTypeCode;
- (Class)responseClass;

@end

#endif /* PBRequest_h */
