//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 300.23.11.14.2
//
#ifndef PBSessionRequester_h
#define PBSessionRequester_h
@import Foundation;

#include "NSURLSessionTaskDelegatePrivate-Protocol.h"
#include "PBDataReader.h"

@class NSURLSession, NSURLSessionTask;
@protocol PBSessionRequesterDelegate;

@interface PBSessionRequester
    : NSObject <NSURLSessionTaskDelegatePrivate, NSURLSessionDataDelegate> {
    /* instance variables */
    NSOperationQueue *_delegateQueue;
    NSOperationQueue *_sessionDelegateQ;
    NSMutableData *_data;
    PBDataReader *_dataReader;
    unsigned long long _lastGoodDataOffset;
    unsigned long long _timeRequestSent;
    unsigned long long _timeResponseReceived;
    long long _responseStatusCode;
    NSMutableArray *_responses;
    NSMutableArray *_internalRequests;
    NSMutableArray *_internalResponses;
    _Bool _didNotifyRequestCompleted;
    NSDictionary *_connectionProperties;
    struct {
        unsigned int ignoresResponse : 1;
        unsigned int loading : 1;
        unsigned int needsCancel : 1;
        unsigned int responseStatusSet : 1;
        unsigned int parsedResponseHeader : 1;
        unsigned int delegateDidReceiveResponse : 1;
        unsigned int delegateDidFinish : 1;
        unsigned int delegateDidCancel : 1;
        unsigned int delegateDidFailWithError : 1;
        unsigned int paused : 1;
        unsigned int resuming : 1;
    } _flags;
}

@property(retain, nonatomic) NSURL *URL;
@property(readonly, weak, nonatomic) id<PBSessionRequesterDelegate> delegate;
@property(retain, nonatomic) NSURLSession *session;
@property(retain, nonatomic) NSURLSessionTask *currentTask;
@property(nonatomic) _Bool ignoresResponse;
@property(retain, nonatomic) NSString *logRequestToFile;
@property(retain, nonatomic) NSString *logResponseToFile;
@property(readonly, weak, nonatomic) NSArray *requests;
@property(readonly, nonatomic) unsigned long long uploadPayloadSize;
@property(readonly, nonatomic) unsigned long long downloadPayloadSize;
@property(readonly, nonatomic) unsigned long long requestResponseTime;
@property(copy, nonatomic) NSString *apsRelayTopic;
@property(nonatomic) unsigned long long nwActivityDomain;
@property(nonatomic) unsigned long long nwActivityLabel;
@property(nonatomic) double timeoutSeconds;
@property(retain, nonatomic) NSArray *clientCertificates;
@property(copy, nonatomic) NSDictionary *httpRequestHeaders;
@property(retain, nonatomic) NSDictionary *httpResponseHeaders;
@property(nonatomic) _Bool shouldHandleCookies;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)usesEncodedMessages;

/* instance methods */
- (void)dealloc;
- (void)resume;
- (void)pause;
- (void)start;
- (void)URLSession:(id)urlsession
              dataTask:(id)task
    didReceiveResponse:(id)response
     completionHandler:(id /* block */)handler;
- (void)URLSession:(id)urlsession
    didReceiveChallenge:(id)challenge
      completionHandler:(id /* block */)handler;
- (void)URLSession:(id)urlsession dataTask:(id)task didReceiveData:(id)data;
- (void)URLSession:(id)urlsession task:(id)task didCompleteWithError:(id)error;
- (void)cancel;
- (_Bool)isPaused;
- (void)URLSession:(id)urlsession
                                        task:(id)task
    _willSendRequestForEstablishedConnection:(id)connection
                           completionHandler:(id /* block */)handler;
- (id)requestPreamble;
- (void)addInternalRequest:(id)request;
- (void)addRequest:(id)request;
- (void)cancelWithErrorCode:(long long)code;
- (void)clearRequests;
- (id)decodeResponseData:(id)data;
- (void)encodeRequestData:(id)data startRequestCallback:(id /* block */)callback;
- (void)handleResponse:(id)response forInternalRequest:(id)request;
- (id)initWithURL:(id)url delegate:(id)delegate queue:(id)queue;
- (id)internalRequests;
- (id)newMutableURLRequestWithURL:(id)url;
- (id)newSessionTaskOnSession:(id)session withURLRequest:(id)urlrequest;
- (id)newSessionWithDelegate:(id)delegate delegateQueue:(id)queue;
- (id)newSessionWithDelegate:(id)delegate
               delegateQueue:(id)queue
        connectionProperties:(id)properties;
- (_Bool)readResponsePreamble:(id)preamble;
- (id)responseForInternalRequest:(id)request;
- (id)responseForRequest:(id)request;
- (void)setHttpRequestHeader:(id)header forKey:(id)key;
- (void)setNeedsCancel;
- (void)startWithConnectionProperties:(id)properties;
- (id)tryReadResponseData:(id)data forRequest:(id)request forResponseClass:(Class)_class;
- (void)writeRequest:(id)request into:(id)into;

@end

#endif /* PBSessionRequester_h */
