//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 300.23.11.14.2
//
#ifndef PBUnknownFields_h
#define PBUnknownFields_h
@import Foundation;

@interface PBUnknownFields : NSObject {
    /* instance variables */
    char *_buf;
    unsigned long long _bufSpace;
    unsigned long long _bufLen;
    unsigned long long _recursionDepth;
}

/* instance methods */
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
- (void)writeTo:(id)to;

@end

#endif /* PBUnknownFields_h */
