//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRAudioFormatProtobuf_h
#define _MRAudioFormatProtobuf_h
@import Foundation;

@class PBCodable;

@interface _MRAudioFormatProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int bitDepth : 1;
        unsigned int bitrate : 1;
        unsigned int sampleRate : 1;
        unsigned int channelLayout : 1;
        unsigned int codec : 1;
        unsigned int renderingMode : 1;
        unsigned int tier : 1;
        unsigned int multiChannel : 1;
        unsigned int spatialized : 1;
    } _has;
}

@property(nonatomic) _Bool hasTier;
@property(nonatomic) int tier;
@property(nonatomic) _Bool hasBitrate;
@property(nonatomic) long long bitrate;
@property(nonatomic) _Bool hasSampleRate;
@property(nonatomic) long long sampleRate;
@property(nonatomic) _Bool hasBitDepth;
@property(nonatomic) long long bitDepth;
@property(nonatomic) _Bool hasCodec;
@property(nonatomic) unsigned int codec;
@property(nonatomic) _Bool hasSpatialized;
@property(nonatomic) _Bool spatialized;
@property(nonatomic) _Bool hasMultiChannel;
@property(nonatomic) _Bool multiChannel;
@property(nonatomic) _Bool hasChannelLayout;
@property(nonatomic) unsigned int channelLayout;
@property(readonly, nonatomic) _Bool hasAudioChannelLayoutDescription;
@property(retain, nonatomic) NSString *audioChannelLayoutDescription;
@property(readonly, nonatomic) _Bool hasGroupID;
@property(retain, nonatomic) NSString *groupID;
@property(readonly, nonatomic) _Bool hasStableVariantID;
@property(retain, nonatomic) NSString *stableVariantID;
@property(nonatomic) _Bool hasRenderingMode;
@property(nonatomic) int renderingMode;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (int)StringAsRenderingMode:(id)mode;
- (id)renderingModeAsString:(int)string;
- (int)StringAsTier:(id)tier;
- (id)tierAsString:(int)string;

@end

#endif /* _MRAudioFormatProtobuf_h */
