//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRAudioRouteProtobuf_h
#define _MRAudioRouteProtobuf_h
@import Foundation;

@class PBCodable;

@interface _MRAudioRouteProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int type : 1;
        unsigned int spatializationEnabled : 1;
        unsigned int supportsSpatialization : 1;
    } _has;
}

@property(nonatomic) _Bool hasType;
@property(nonatomic) int type;
@property(readonly, nonatomic) _Bool hasName;
@property(retain, nonatomic) NSString *name;
@property(nonatomic) _Bool hasSupportsSpatialization;
@property(nonatomic) _Bool supportsSpatialization;
@property(nonatomic) _Bool hasSpatializationEnabled;
@property(nonatomic) _Bool spatializationEnabled;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (int)StringAsType:(id)type;
- (id)typeAsString:(int)string;

@end

#endif /* _MRAudioRouteProtobuf_h */
