//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRAudioStreamPacketDescriptionProtobuf_h
#define _MRAudioStreamPacketDescriptionProtobuf_h
@import Foundation;

@class PBCodable;

@interface _MRAudioStreamPacketDescriptionProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int startOffset : 1;
        unsigned int dataByteSize : 1;
        unsigned int variableFramesInPacket : 1;
    } _has;
}

@property(nonatomic) _Bool hasStartOffset;
@property(nonatomic) long long startOffset;
@property(nonatomic) _Bool hasVariableFramesInPacket;
@property(nonatomic) unsigned int variableFramesInPacket;
@property(nonatomic) _Bool hasDataByteSize;
@property(nonatomic) unsigned int dataByteSize;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;

@end

#endif /* _MRAudioStreamPacketDescriptionProtobuf_h */
