//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRAVEndpointDescriptorProtobuf_h
#define _MRAVEndpointDescriptorProtobuf_h
@import Foundation;

#include "_MRAVOutputDeviceDescriptorProtobuf.h"

@class PBCodable;

@interface _MRAVEndpointDescriptorProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int connectionType : 1;
        unsigned int canModifyGroupMembership : 1;
        unsigned int isLocalEndpoint : 1;
        unsigned int isProxyGroupPlayer : 1;
    } _has;
}

@property(readonly, nonatomic) _Bool hasName;
@property(retain, nonatomic) NSString *name;
@property(readonly, nonatomic) _Bool hasUniqueIdentifier;
@property(retain, nonatomic) NSString *uniqueIdentifier;
@property(retain, nonatomic) NSMutableArray *outputDevices;
@property(readonly, nonatomic) _Bool hasDesignatedGroupLeader;
@property(retain, nonatomic) _MRAVOutputDeviceDescriptorProtobuf *designatedGroupLeader;
@property(nonatomic) _Bool hasIsLocalEndpoint;
@property(nonatomic) _Bool isLocalEndpoint;
@property(readonly, nonatomic) _Bool hasInstanceIdentifier;
@property(retain, nonatomic) NSString *instanceIdentifier;
@property(nonatomic) _Bool hasIsProxyGroupPlayer;
@property(nonatomic) _Bool isProxyGroupPlayer;
@property(nonatomic) _Bool hasConnectionType;
@property(nonatomic) int connectionType;
@property(nonatomic) _Bool hasCanModifyGroupMembership;
@property(nonatomic) _Bool canModifyGroupMembership;
@property(retain, nonatomic) NSMutableArray *personalOutputDevices;

/* class methods */
+ (Class)outputDevicesType;
+ (Class)personalOutputDevicesType;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (int)StringAsConnectionType:(id)type;
- (id)connectionTypeAsString:(int)string;
- (void)addOutputDevices:(id)devices;
- (void)addPersonalOutputDevices:(id)devices;
- (void)clearOutputDevices;
- (void)clearPersonalOutputDevices;
- (id)outputDevicesAtIndex:(unsigned long long)index;
- (unsigned long long)outputDevicesCount;
- (id)personalOutputDevicesAtIndex:(unsigned long long)index;
- (unsigned long long)personalOutputDevicesCount;

@end

#endif /* _MRAVEndpointDescriptorProtobuf_h */
