//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRAudioDataBlockProtobuf_h
#define _MRAudioDataBlockProtobuf_h
@import Foundation;

#include "_MRAudioBufferProtobuf.h"
#include "_MRAudioTimeProtobuf.h"

@class PBCodable;

@interface _MRAudioDataBlockProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int gain : 1;
    } _has;
}

@property(readonly, nonatomic) _Bool hasBuffer;
@property(retain, nonatomic) _MRAudioBufferProtobuf *buffer;
@property(readonly, nonatomic) _Bool hasTime;
@property(retain, nonatomic) _MRAudioTimeProtobuf *time;
@property(nonatomic) _Bool hasGain;
@property(nonatomic) double gain;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;

@end

#endif /* _MRAudioDataBlockProtobuf_h */
