//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRAVAirPlaySecuritySettingsProtobuf_h
#define _MRAVAirPlaySecuritySettingsProtobuf_h
@import Foundation;

@class PBCodable;

@interface _MRAVAirPlaySecuritySettingsProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int securityType : 1;
    } _has;
}

@property(readonly, nonatomic) _Bool hasPassword;
@property(retain, nonatomic) NSString *password;
@property(nonatomic) _Bool hasSecurityType;
@property(nonatomic) int securityType;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (int)StringAsSecurityType:(id)type;
- (id)securityTypeAsString:(int)string;

@end

#endif /* _MRAVAirPlaySecuritySettingsProtobuf_h */
