//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRColorProtobuf_h
#define _MRColorProtobuf_h
@import Foundation;

@class PBCodable;

@interface _MRColorProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int alpha : 1;
        unsigned int blue : 1;
        unsigned int green : 1;
        unsigned int red : 1;
    } _has;
}

@property(nonatomic) _Bool hasRed;
@property(nonatomic) float red;
@property(nonatomic) _Bool hasGreen;
@property(nonatomic) float green;
@property(nonatomic) _Bool hasBlue;
@property(nonatomic) float blue;
@property(nonatomic) _Bool hasAlpha;
@property(nonatomic) float alpha;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;

@end

#endif /* _MRColorProtobuf_h */
