//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRDiscoverySessionConfigurationProtobuf_h
#define _MRDiscoverySessionConfigurationProtobuf_h
@import Foundation;

@class PBCodable;

@interface _MRDiscoverySessionConfigurationProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int features : 1;
        unsigned int targetSessionID : 1;
        unsigned int alwaysAllowUpdates : 1;
        unsigned int enableThrottling : 1;
        unsigned int populatesExternalDevice : 1;
    } _has;
}

@property(nonatomic) _Bool hasFeatures;
@property(nonatomic) int features;
@property(readonly, nonatomic) _Bool hasRoutingContextUID;
@property(retain, nonatomic) NSString *routingContextUID;
@property(nonatomic) _Bool hasEnableThrottling;
@property(nonatomic) _Bool enableThrottling;
@property(nonatomic) _Bool hasAlwaysAllowUpdates;
@property(nonatomic) _Bool alwaysAllowUpdates;
@property(nonatomic) _Bool hasPopulatesExternalDevice;
@property(nonatomic) _Bool populatesExternalDevice;
@property(readonly, nonatomic) _Bool hasOutputDeviceUID;
@property(retain, nonatomic) NSString *outputDeviceUID;
@property(nonatomic) _Bool hasTargetSessionID;
@property(nonatomic) unsigned int targetSessionID;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (int)StringAsFeatures:(id)features;
- (id)featuresAsString:(int)string;

@end

#endif /* _MRDiscoverySessionConfigurationProtobuf_h */
