//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRGetVoiceInputDevicesResponseMessageProtobuf_h
#define _MRGetVoiceInputDevicesResponseMessageProtobuf_h
@import Foundation;

@class PBCodable;

@interface _MRGetVoiceInputDevicesResponseMessageProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int errorCode : 1;
    } _has;
}

@property(readonly, nonatomic) unsigned long long deviceIDsCount;
@property(readonly, nonatomic) unsigned int *deviceIDs;
@property(nonatomic) _Bool hasErrorCode;
@property(nonatomic) unsigned int errorCode;

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)addDeviceIDs:(unsigned int)ids;
- (void)clearDeviceIDs;
- (unsigned int)deviceIDsAtIndex:(unsigned long long)index;
- (void)setDeviceIDs:(unsigned int *)ids count:(unsigned long long)count;

@end

#endif /* _MRGetVoiceInputDevicesResponseMessageProtobuf_h */
