//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRGroupSessionMemberSyncMessageProtobuf_h
#define _MRGroupSessionMemberSyncMessageProtobuf_h
@import Foundation;

@class PBCodable;

@interface _MRGroupSessionMemberSyncMessageProtobuf : PBCodable <NSCopying>

@property(retain, nonatomic) NSMutableArray *participants;
@property(retain, nonatomic) NSMutableArray *members;
@property(retain, nonatomic) NSMutableArray *pendingParticipants;

/* class methods */
+ (Class)participantsType;
+ (Class)membersType;
+ (Class)pendingParticipantsType;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)addParticipants:(id)participants;
- (void)clearParticipants;
- (id)participantsAtIndex:(unsigned long long)index;
- (unsigned long long)participantsCount;
- (void)addMembers:(id)members;
- (id)membersAtIndex:(unsigned long long)index;
- (void)addPendingParticipants:(id)participants;
- (void)clearMembers;
- (void)clearPendingParticipants;
- (unsigned long long)membersCount;
- (id)pendingParticipantsAtIndex:(unsigned long long)index;
- (unsigned long long)pendingParticipantsCount;

@end

#endif /* _MRGroupSessionMemberSyncMessageProtobuf_h */
