//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRLanguageOptionGroupProtobuf_h
#define _MRLanguageOptionGroupProtobuf_h
@import Foundation;

#include "_MRLanguageOptionProtobuf.h"

@class PBCodable;

@interface _MRLanguageOptionGroupProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int allowEmptySelection : 1;
    } _has;
}

@property(nonatomic) _Bool hasAllowEmptySelection;
@property(nonatomic) _Bool allowEmptySelection;
@property(readonly, nonatomic) _Bool hasDefaultLanguageOption;
@property(retain, nonatomic) _MRLanguageOptionProtobuf *defaultLanguageOption;
@property(retain, nonatomic) NSMutableArray *languageOptions;

/* class methods */
+ (Class)languageOptionsType;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)addLanguageOptions:(id)options;
- (void)clearLanguageOptions;
- (id)languageOptionsAtIndex:(unsigned long long)index;
- (unsigned long long)languageOptionsCount;

@end

#endif /* _MRLanguageOptionGroupProtobuf_h */
