//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRLanguageOptionProtobuf_h
#define _MRLanguageOptionProtobuf_h
@import Foundation;

@class PBCodable;

@interface _MRLanguageOptionProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int type : 1;
    } _has;
}

@property(nonatomic) _Bool hasType;
@property(nonatomic) int type;
@property(readonly, nonatomic) _Bool hasLanguageTag;
@property(retain, nonatomic) NSString *languageTag;
@property(retain, nonatomic) NSMutableArray *characteristics;
@property(readonly, nonatomic) _Bool hasDisplayName;
@property(retain, nonatomic) NSString *displayName;
@property(readonly, nonatomic) _Bool hasIdentifier;
@property(retain, nonatomic) NSString *identifier;

/* class methods */
+ (Class)characteristicsType;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)addCharacteristics:(id)characteristics;
- (id)characteristicsAtIndex:(unsigned long long)index;
- (unsigned long long)characteristicsCount;
- (void)clearCharacteristics;

@end

#endif /* _MRLanguageOptionProtobuf_h */
