//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRNowPlayingInfoProtobuf_h
#define _MRNowPlayingInfoProtobuf_h
@import Foundation;

@class PBCodable;

@interface _MRNowPlayingInfoProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int duration : 1;
        unsigned int elapsedTime : 1;
        unsigned int radioStationIdentifier : 1;
        unsigned int timestamp : 1;
        unsigned int uniqueIdentifier : 1;
        unsigned int playbackRate : 1;
        unsigned int repeatMode : 1;
        unsigned int shuffleMode : 1;
        unsigned int isAdvertisement : 1;
        unsigned int isAlwaysLive : 1;
        unsigned int isExplicitTrack : 1;
        unsigned int isMusicApp : 1;
    } _has;
}

@property(readonly, nonatomic) _Bool hasAlbum;
@property(retain, nonatomic) NSString *album;
@property(readonly, nonatomic) _Bool hasArtist;
@property(retain, nonatomic) NSString *artist;
@property(nonatomic) _Bool hasDuration;
@property(nonatomic) double duration;
@property(nonatomic) _Bool hasElapsedTime;
@property(nonatomic) double elapsedTime;
@property(nonatomic) _Bool hasPlaybackRate;
@property(nonatomic) float playbackRate;
@property(nonatomic) _Bool hasRepeatMode;
@property(nonatomic) int repeatMode;
@property(nonatomic) _Bool hasShuffleMode;
@property(nonatomic) int shuffleMode;
@property(nonatomic) _Bool hasTimestamp;
@property(nonatomic) double timestamp;
@property(readonly, nonatomic) _Bool hasTitle;
@property(retain, nonatomic) NSString *title;
@property(nonatomic) _Bool hasUniqueIdentifier;
@property(nonatomic) unsigned long long uniqueIdentifier;
@property(nonatomic) _Bool hasIsExplicitTrack;
@property(nonatomic) _Bool isExplicitTrack;
@property(nonatomic) _Bool hasIsMusicApp;
@property(nonatomic) _Bool isMusicApp;
@property(nonatomic) _Bool hasRadioStationIdentifier;
@property(nonatomic) long long radioStationIdentifier;
@property(readonly, nonatomic) _Bool hasRadioStationHash;
@property(retain, nonatomic) NSString *radioStationHash;
@property(readonly, nonatomic) _Bool hasRadioStationName;
@property(retain, nonatomic) NSString *radioStationName;
@property(readonly, nonatomic) _Bool hasArtworkDataDigest;
@property(retain, nonatomic) NSData *artworkDataDigest;
@property(nonatomic) _Bool hasIsAlwaysLive;
@property(nonatomic) _Bool isAlwaysLive;
@property(nonatomic) _Bool hasIsAdvertisement;
@property(nonatomic) _Bool isAdvertisement;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (int)StringAsShuffleMode:(id)mode;
- (int)StringAsRepeatMode:(id)mode;
- (id)repeatModeAsString:(int)string;
- (id)shuffleModeAsString:(int)string;

@end

#endif /* _MRNowPlayingInfoProtobuf_h */
