//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRNowPlayingClientProtobuf_h
#define _MRNowPlayingClientProtobuf_h
@import Foundation;

#include "_MRColorProtobuf.h"

@class PBCodable;

@interface _MRNowPlayingClientProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int nowPlayingVisibility : 1;
        unsigned int processIdentifier : 1;
        unsigned int processUserIdentifier : 1;
        unsigned int isEmptyDeprecated : 1;
    } _has;
}

@property(nonatomic) _Bool hasProcessIdentifier;
@property(nonatomic) int processIdentifier;
@property(readonly, nonatomic) _Bool hasBundleIdentifier;
@property(retain, nonatomic) NSString *bundleIdentifier;
@property(readonly, nonatomic) _Bool hasParentApplicationBundleIdentifier;
@property(retain, nonatomic) NSString *parentApplicationBundleIdentifier;
@property(nonatomic) _Bool hasProcessUserIdentifier;
@property(nonatomic) int processUserIdentifier;
@property(nonatomic) _Bool hasNowPlayingVisibility;
@property(nonatomic) int nowPlayingVisibility;
@property(readonly, nonatomic) _Bool hasTintColor;
@property(retain, nonatomic) _MRColorProtobuf *tintColor;
@property(readonly, nonatomic) _Bool hasDisplayName;
@property(retain, nonatomic) NSString *displayName;
@property(retain, nonatomic) NSMutableArray *extendedBundleIdentifierHierarchys;
@property(nonatomic) _Bool hasIsEmptyDeprecated;
@property(nonatomic) _Bool isEmptyDeprecated;
@property(readonly, nonatomic) _Bool hasIconURL;
@property(retain, nonatomic) NSString *iconURL;

/* class methods */
+ (Class)extendedBundleIdentifierHierarchyType;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (int)StringAsNowPlayingVisibility:(id)visibility;
- (void)addExtendedBundleIdentifierHierarchy:(id)hierarchy;
- (void)clearExtendedBundleIdentifierHierarchys;
- (id)extendedBundleIdentifierHierarchyAtIndex:(unsigned long long)index;
- (unsigned long long)extendedBundleIdentifierHierarchysCount;
- (id)nowPlayingVisibilityAsString:(int)string;

@end

#endif /* _MRNowPlayingClientProtobuf_h */
