//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRPlaybackSessionMigrateRequestProtobuf_h
#define _MRPlaybackSessionMigrateRequestProtobuf_h
@import Foundation;

#include "_MRContentItemProtobuf.h"
#include "_MRNowPlayingPlayerPathProtobuf.h"
#include "_MRPlaybackSessionRequestProtobuf.h"

@class PBCodable;

@interface _MRPlaybackSessionMigrateRequestProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int playbackPosition : 1;
        unsigned int playbackRate : 1;
        unsigned int destinationTypes : 1;
        unsigned int endpointOptions : 1;
        unsigned int originatorType : 1;
        unsigned int playbackState : 1;
        unsigned int playerOptions : 1;
        unsigned int allowFadeTransition : 1;
    } _has;
}

@property(readonly, nonatomic) _Bool hasRequestID;
@property(retain, nonatomic) NSString *requestID;
@property(nonatomic) _Bool hasPlayerOptions;
@property(nonatomic) int playerOptions;
@property(nonatomic) _Bool hasEndpointOptions;
@property(nonatomic) int endpointOptions;
@property(retain, nonatomic) NSMutableArray *events;
@property(nonatomic) _Bool hasPlaybackPosition;
@property(nonatomic) double playbackPosition;
@property(readonly, nonatomic) _Bool hasContentItem;
@property(retain, nonatomic) _MRContentItemProtobuf *contentItem;
@property(readonly, nonatomic) _Bool hasPlayerPath;
@property(retain, nonatomic) _MRNowPlayingPlayerPathProtobuf *playerPath;
@property(nonatomic) _Bool hasPlaybackState;
@property(nonatomic) int playbackState;
@property(nonatomic) _Bool hasPlaybackRate;
@property(nonatomic) double playbackRate;
@property(readonly, nonatomic) _Bool hasPlaybackSessionRequest;
@property(retain, nonatomic) _MRPlaybackSessionRequestProtobuf *playbackSessionRequest;
@property(nonatomic) _Bool hasAllowFadeTransition;
@property(nonatomic) _Bool allowFadeTransition;
@property(nonatomic) _Bool hasOriginatorType;
@property(nonatomic) unsigned int originatorType;
@property(nonatomic) _Bool hasDestinationTypes;
@property(nonatomic) unsigned int destinationTypes;
@property(readonly, nonatomic) _Bool hasInitiator;
@property(retain, nonatomic) NSString *initiator;
@property(readonly, nonatomic) _Bool hasResolvedPlayerPath;
@property(retain, nonatomic) _MRNowPlayingPlayerPathProtobuf *resolvedPlayerPath;

/* class methods */
+ (Class)eventsType;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)addEvents:(id)events;
- (void)clearEvents;
- (id)eventsAtIndex:(unsigned long long)index;
- (unsigned long long)eventsCount;
- (int)StringAsPlaybackState:(id)state;
- (int)StringAsEndpointOptions:(id)options;
- (int)StringAsPlayerOptions:(id)options;
- (id)endpointOptionsAsString:(int)string;
- (id)playbackStateAsString:(int)string;
- (id)playerOptionsAsString:(int)string;

@end

#endif /* _MRPlaybackSessionMigrateRequestProtobuf_h */
