//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRReceivedCommandProtobuf_h
#define _MRReceivedCommandProtobuf_h
@import Foundation;

#include "_MRCommandOptionsProtobuf.h"
#include "_MRNowPlayingPlayerPathProtobuf.h"
#include "_MRReceivedCommandAppOptionsProtobuf.h"

@class PBCodable;

@interface _MRReceivedCommandProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int destinationAppProcessID : 1;
        unsigned int command : 1;
        unsigned int originUID : 1;
    } _has;
}

@property(nonatomic) _Bool hasCommand;
@property(nonatomic) int command;
@property(readonly, nonatomic) _Bool hasOptions;
@property(retain, nonatomic) _MRCommandOptionsProtobuf *options;
@property(nonatomic) _Bool hasOriginUID;
@property(nonatomic) int originUID;
@property(readonly, nonatomic) _Bool hasSenderAppDisplayID;
@property(retain, nonatomic) NSString *senderAppDisplayID;
@property(readonly, nonatomic) _Bool hasDestinationAppDisplayID;
@property(retain, nonatomic) NSString *destinationAppDisplayID;
@property(nonatomic) _Bool hasDestinationAppProcessID;
@property(nonatomic) long long destinationAppProcessID;
@property(readonly, nonatomic) _Bool hasRemoteControlInterfaceID;
@property(retain, nonatomic) NSString *remoteControlInterfaceID;
@property(readonly, nonatomic) _Bool hasAppOptions;
@property(retain, nonatomic) _MRReceivedCommandAppOptionsProtobuf *appOptions;
@property(readonly, nonatomic) _Bool hasPlayerPath;
@property(retain, nonatomic) _MRNowPlayingPlayerPathProtobuf *playerPath;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (int)StringAsCommand:(id)command;
- (id)commandAsString:(int)string;

@end

#endif /* _MRReceivedCommandProtobuf_h */
