//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRSendCommandResultStatusProtobuf_h
#define _MRSendCommandResultStatusProtobuf_h
@import Foundation;

#include "_MRErrorProtobuf.h"
#include "_MRSendCommandResultHandlerDialogProtobuf.h"

@class PBCodable;

@interface _MRSendCommandResultStatusProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int statusCode : 1;
        unsigned int type : 1;
    } _has;
}

@property(nonatomic) _Bool hasStatusCode;
@property(nonatomic) int statusCode;
@property(nonatomic) _Bool hasType;
@property(nonatomic) int type;
@property(readonly, nonatomic) _Bool hasDialog;
@property(retain, nonatomic) _MRSendCommandResultHandlerDialogProtobuf *dialog;
@property(readonly, nonatomic) _Bool hasError;
@property(retain, nonatomic) _MRErrorProtobuf *error;
@property(readonly, nonatomic) _Bool hasCustomData;
@property(retain, nonatomic) NSData *customData;
@property(readonly, nonatomic) _Bool hasCustomDataType;
@property(retain, nonatomic) NSString *customDataType;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (int)StringAsType:(id)type;
- (id)typeAsString:(int)string;
- (int)StringAsStatusCode:(id)code;
- (id)statusCodeAsString:(int)string;

@end

#endif /* _MRSendCommandResultStatusProtobuf_h */
