//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRSendCommandResultMessageProtobuf_h
#define _MRSendCommandResultMessageProtobuf_h
@import Foundation;

#include "_MRNowPlayingPlayerPathProtobuf.h"
#include "_MRSendCommandResultProtobuf.h"

@class PBCodable;

@interface _MRSendCommandResultMessageProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int sendError : 1;
    } _has;
}

@property(nonatomic) _Bool hasSendError;
@property(nonatomic) int sendError;
@property(readonly, nonatomic) unsigned long long handlerReturnStatusCount;
@property(readonly, nonatomic) int *handlerReturnStatus;
@property(retain, nonatomic) NSMutableArray *handlerReturnStatusDatas;
@property(readonly, nonatomic) _Bool hasCommandID;
@property(retain, nonatomic) NSString *commandID;
@property(readonly, nonatomic) _Bool hasPlayerPath;
@property(retain, nonatomic) _MRNowPlayingPlayerPathProtobuf *playerPath;
@property(readonly, nonatomic) _Bool hasCommandResult;
@property(retain, nonatomic) _MRSendCommandResultProtobuf *commandResult;

/* class methods */
+ (Class)handlerReturnStatusDataType;

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (int)StringAsSendError:(id)error;
- (int)StringAsHandlerReturnStatus:(id)status;
- (id)handlerReturnStatusDataAtIndex:(unsigned long long)index;
- (void)addHandlerReturnStatus:(int)status;
- (void)addHandlerReturnStatusData:(id)data;
- (void)clearHandlerReturnStatus;
- (void)clearHandlerReturnStatusDatas;
- (id)handlerReturnStatusAsString:(int)string;
- (int)handlerReturnStatusAtIndex:(unsigned long long)index;
- (unsigned long long)handlerReturnStatusDatasCount;
- (id)sendErrorAsString:(int)string;
- (void)setHandlerReturnStatus:(int *)status count:(unsigned long long)count;

@end

#endif /* _MRSendCommandResultMessageProtobuf_h */
