//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRTelevisionControllerBlockCallback_h
#define _MRTelevisionControllerBlockCallback_h
@import Foundation;

@protocol OS_dispatch_queue;

@interface _MRTelevisionControllerBlockCallback : NSObject

@property(readonly, nonatomic) id /* block */ callbackBlock;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;

/* instance methods */
- (id)initWithCallbackBlock:(id /* block */)block queue:(id)queue;

@end

#endif /* _MRTelevisionControllerBlockCallback_h */
