//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRUpdateEndpointsMessageProtobuf_h
#define _MRUpdateEndpointsMessageProtobuf_h
@import Foundation;

@class PBCodable;

@interface _MRUpdateEndpointsMessageProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int endpointFeatures : 1;
    } _has;
}

@property(retain, nonatomic) NSMutableArray *endpoints;
@property(nonatomic) _Bool hasEndpointFeatures;
@property(nonatomic) int endpointFeatures;

/* class methods */
+ (Class)endpointsType;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (int)StringAsEndpointFeatures:(id)features;
- (void)addEndpoints:(id)endpoints;
- (void)clearEndpoints;
- (id)endpointFeaturesAsString:(int)string;
- (id)endpointsAtIndex:(unsigned long long)index;
- (unsigned long long)endpointsCount;

@end

#endif /* _MRUpdateEndpointsMessageProtobuf_h */
