//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRUpdateActiveSystemEndpointRequestProtobuf_h
#define _MRUpdateActiveSystemEndpointRequestProtobuf_h
@import Foundation;

@class PBCodable;

@interface _MRUpdateActiveSystemEndpointRequestProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int disableDuration : 1;
        unsigned int type : 1;
        unsigned int changeType : 1;
        unsigned int demoteWhenSyncingToCompanion : 1;
        unsigned int pairedDeviceSync : 1;
    } _has;
}

@property(readonly, nonatomic) _Bool hasOutputDeviceUID;
@property(retain, nonatomic) NSString *outputDeviceUID;
@property(nonatomic) _Bool hasChangeType;
@property(nonatomic) int changeType;
@property(readonly, nonatomic) _Bool hasReason;
@property(retain, nonatomic) NSString *reason;
@property(nonatomic) _Bool hasPairedDeviceSync;
@property(nonatomic) _Bool pairedDeviceSync;
@property(nonatomic) _Bool hasType;
@property(nonatomic) unsigned long long type;
@property(nonatomic) _Bool hasDisableDuration;
@property(nonatomic) double disableDuration;
@property(nonatomic) _Bool hasDemoteWhenSyncingToCompanion;
@property(nonatomic) _Bool demoteWhenSyncingToCompanion;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (int)StringAsChangeType:(id)type;
- (id)changeTypeAsString:(int)string;

@end

#endif /* _MRUpdateActiveSystemEndpointRequestProtobuf_h */
