//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRUpdateOutputDevicesMessageProtobuf_h
#define _MRUpdateOutputDevicesMessageProtobuf_h
@import Foundation;

@class PBCodable;

@interface _MRUpdateOutputDevicesMessageProtobuf : PBCodable <NSCopying>

@property(retain, nonatomic) NSMutableArray *outputDevices;
@property(readonly, nonatomic) _Bool hasEndpointUID;
@property(retain, nonatomic) NSString *endpointUID;
@property(retain, nonatomic) NSMutableArray *clusterAwareOutputDevices;

/* class methods */
+ (Class)clusterAwareOutputDevicesType;
+ (Class)outputDevicesType;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)addClusterAwareOutputDevices:(id)devices;
- (void)addOutputDevices:(id)devices;
- (void)clearClusterAwareOutputDevices;
- (void)clearOutputDevices;
- (id)clusterAwareOutputDevicesAtIndex:(unsigned long long)index;
- (unsigned long long)clusterAwareOutputDevicesCount;
- (id)outputDevicesAtIndex:(unsigned long long)index;
- (unsigned long long)outputDevicesCount;

@end

#endif /* _MRUpdateOutputDevicesMessageProtobuf_h */
