//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef _MRVirtualTouchDeviceDescriptorProtobuf_h
#define _MRVirtualTouchDeviceDescriptorProtobuf_h
@import Foundation;

@class PBCodable;

@interface _MRVirtualTouchDeviceDescriptorProtobuf : PBCodable <NSCopying> {
    /* instance variables */
    struct {
        unsigned int screenSizeHeight : 1;
        unsigned int screenSizeWidth : 1;
        unsigned int absolute : 1;
        unsigned int integratedDisplay : 1;
    } _has;
}

@property(nonatomic) _Bool hasAbsolute;
@property(nonatomic) _Bool absolute;
@property(nonatomic) _Bool hasIntegratedDisplay;
@property(nonatomic) _Bool integratedDisplay;
@property(nonatomic) _Bool hasScreenSizeWidth;
@property(nonatomic) float screenSizeWidth;
@property(nonatomic) _Bool hasScreenSizeHeight;
@property(nonatomic) float screenSizeHeight;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)to;
- (void)mergeFrom:(id)from;
- (_Bool)readFrom:(id)from;
- (void)writeTo:(id)to;

@end

#endif /* _MRVirtualTouchDeviceDescriptorProtobuf_h */
