//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef IDSDevice_MRAdditions_h
#define IDSDevice_MRAdditions_h
@import Foundation;

// @interface IDSDevice (MRAdditions)

// /* instance methods */
// - (id)mr_outputDevice;
// - (long long)mr_deviceClass;
// - (id)mr_deviceInfo;
// - (unsigned int)mr_deviceSubType;

// @end

#endif /* IDSDevice_MRAdditions_h */
