//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef IDSService_MRAdditions_h
#define IDSService_MRAdditions_h
@import Foundation;
@protocol IDSService;

// @interface IDSService (MRAdditions)

// /* class methods */
// + (id)mr_companionServiceName;
// + (id)mr_serviceName;
// + (id)mr_sharedIDSCompanionService;
// + (id)mr_sharedIDSService;

// @end

#endif /* IDSService_MRAdditions_h */
