//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVDistantExternalDeviceServiceProtocol_Protocol_h
#define MRAVDistantExternalDeviceServiceProtocol_Protocol_h
@import Foundation;

@protocol MRAVDistantExternalDeviceServiceProtocol <NSObject>

@required

@property(copy, nonatomic) NSArray *subscribedPlayerPaths;

/* required instance methods */
- (void)setNotifications:(unsigned long long)notifications;
- (void)disconnect:(id)disconnect;
- (void)adjustOutputDeviceVolume:(long long)volume
                 outputDeviceUID:(id)uid
                         details:(id)details
                      completion:(id /* block */)completion;
- (void)connectWithOptions:(unsigned int)options
                  userInfo:(id)info
                completion:(id /* block */)completion;
- (void)createHostedEndpointWithOutputDeviceUIDs:(id)uids completion:(id /* block */)completion;
- (void)getCustomOriginDataWithCompletion:(id /* block */)completion;
- (void)getDeviceInfoWithCompletion:(id /* block */)completion;
- (void)getExternalOutputContextWithCompletion:(id /* block */)completion;
- (void)getGroupSessionTokenWithCompletion:(id /* block */)completion;
- (void)getPersonalOutputDevices:(id /* block */)devices;
- (void)modifyTopologyWithRequest:(id)request completion:(id /* block */)completion;
- (void)muteOutputDeviceVolume:(_Bool)volume
               outputDeviceUID:(id)uid
                       details:(id)details
                    completion:(id /* block */)completion;
- (void)pingWithTimeout:(double)timeout callback:(id /* block */)callback;
- (void)sendButtonEventWithUsagePage:(unsigned int)page usage:(unsigned int)usage down:(_Bool)down;
- (void)sendCustomData:(id)data withName:(id)name;
- (void)setConversationDetectionEnabled:(_Bool)enabled
                        outputDeviceUID:(id)uid
                             completion:(id /* block */)completion;
- (void)setDiscoveryMode:(unsigned int)mode forConfiguration:(id)configuration;
- (void)setListeningMode:(id)mode outputDeviceUID:(id)uid completion:(id /* block */)completion;
- (void)setOutputDeviceVolume:(float)volume
              outputDeviceUID:(id)uid
                      details:(id)details
                   completion:(id /* block */)completion;
- (void)setRegisteredCallbacks:(unsigned long long)callbacks;

@optional

@end

#endif /* MRAVDistantExternalDeviceServiceProtocol_Protocol_h */
