//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVRoomOutputDevice_h
#define MRAVRoomOutputDevice_h
@import Foundation;

#include "MRAVConcreteOutputDevice.h"
#include "MRAVOutputDevice.h"

@interface MRAVRoomOutputDevice : MRAVOutputDevice {
    /* instance variables */
    NSArray *_clusterComposition;
    NSString *_uid;
}

@property(readonly, nonatomic) MRAVOutputDevice *outputDevice;
@property(readonly, nonatomic) MRAVConcreteOutputDevice *concreteOutputDevice;
@property(readonly, nonatomic) MRAVOutputDevice *roomMemberOutputDevice;
@property(readonly, nonatomic) NSArray *roomMemberOutputDevices;
@property(readonly, nonatomic) NSString *label;

/* class methods */
+ (id)calculateOutputDeviceIDFromOutputDeviceID:(id)id withRoomID:(id)id;

/* instance methods */
- (id)name;
- (id)uid;
- (id)localizedName;
- (float)volume;
- (unsigned int)deviceType;
- (id)debugName;
- (unsigned int)deviceSubtype;
- (id)modelID;
- (unsigned int)clusterType;
- (id)primaryID;
- (id)roomName;
- (void)adjustVolume:(long long)volume details:(id)details;
- (id)clusterComposition;
- (_Bool)containsUID:(id)uid;
- (id)initWithOutputDevice:(id)device memberOutputDevices:(id)devices;
- (_Bool)isPickable;
- (_Bool)isVolumeMuted;
- (id)parentUID;
- (id)roomID;
- (void)setVolume:(float)volume details:(id)details;
- (void)setVolumeMuted:(_Bool)muted details:(id)details;
- (unsigned int)volumeCapabilities;

@end

#endif /* MRAVRoomOutputDevice_h */
