//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVVirtualOutputDevice_h
#define MRAVVirtualOutputDevice_h
@import Foundation;

#include "MRAVOutputDevice.h"

@protocol OS_dispatch_queue;

@interface MRAVVirtualOutputDevice : MRAVOutputDevice {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_accessSerialQueue;
    NSString *_uid;
    NSString *_modelID;
    NSString *_firmwareVersion;
    NSString *_logicalDeviceID;
    NSString *_groupID;
    NSData *_MACAddress;
    NSDictionary *_modelSpecificInfo;
    NSString *_playingPairedDeviceName;
    NSString *_name;
    _Bool _canAccessRemoteAssets;
    _Bool _canAccessAppleMusic;
    _Bool _canAccessiCloudMusicLibrary;
    _Bool _canPlayEncryptedProgressiveDownloadAssets;
    _Bool _canFetchMediaDataFromSender;
    _Bool _presentsOptimizedUserInterfaceWhenPlayingFetchedAudioOnlyAssets;
    _Bool _isRemoteControllable;
    _Bool _canRelayCommunicationChannel;
    _Bool _supportsBufferedAirPlay;
    _Bool _supportsRapport;
    _Bool _isAddedToHomeKit;
    _Bool _isGroupLeader;
    _Bool _groupContainsGroupLeader;
    _Bool _airPlayReceiver;
    NSString *_parentGroupIdentifier;
    _Bool _isGroupable;
    _Bool _supportsBluetoothSharing;
    _Bool _isProxyGroupPlayer;
    _Bool _isPickedOnPairedDevice;
    float _batteryLevel;
    _Bool _hasBatteryLevel;
    _Bool _isLocalDevice;
    _Bool _supportsExternalScreen;
    unsigned int _deviceType;
    unsigned int _deviceSubType;
    _Bool _requiresAuthorization;
    _Bool _isVolumeControlAvailable;
    float _volume;
    NSString *_bluetoothID;
    _Bool _isUsingJSONProtocol;
    NSString *_currentBluetoothListeningMode;
    NSArray *_availableBluetoothListeningModes;
}

@property(readonly, nonatomic) NSXPCListenerEndpoint *pipeEndpoint;
@property(readonly, nonatomic) NSData *jsonDeviceDefinition;

/* instance methods */
- (id)name;
- (id)uid;
- (float)volume;
- (id)groupID;
- (unsigned int)deviceType;
- (id)firmwareVersion;
- (unsigned int)deviceSubtype;
- (id)modelID;
- (float)batteryLevel;
- (id)bluetoothID;
- (id)sourceInfo;
- (_Bool)requiresAuthorization;
- (_Bool)hasBatteryLevel;
- (id)MACAddress;
- (id)logicalDeviceID;
- (_Bool)presentsOptimizedUserInterfaceWhenPlayingFetchedAudioOnlyAssets;
- (id)availableBluetoothListeningModes;
- (_Bool)canAccessAppleMusic;
- (_Bool)canAccessRemoteAssets;
- (_Bool)canAccessiCloudMusicLibrary;
- (_Bool)canFetchMediaDataFromSender;
- (_Bool)canPlayEncryptedProgressiveDownloadAssets;
- (_Bool)canRelayCommunicationChannel;
- (id)currentBluetoothListeningMode;
- (_Bool)groupContainsGroupLeader;
- (_Bool)isGroupLeader;
- (_Bool)supportsBluetoothSharing;
- (_Bool)supportsBufferedAirPlay;
- (_Bool)supportsRapport;
- (id)initWithJSONData:(id)jsondata pipeEndpoint:(id)endpoint;
- (_Bool)isAddedToHomeKit;
- (_Bool)isAirPlayReceiverSessionActive;
- (_Bool)isDeviceGroupable;
- (_Bool)isGroupable;
- (_Bool)isLocalDevice;
- (_Bool)isPickedOnPairedDevice;
- (_Bool)isProxyGroupPlayer;
- (_Bool)isRemoteControllable;
- (_Bool)isUsingJSONProtocol;
- (_Bool)isVolumeControlAvailable;
- (id)modelSpecificInfo;
- (_Bool)parentGroupContainsDiscoverableLeader;
- (id)parentGroupIdentifier;
- (id)playingPairedDeviceName;
- (_Bool)supportsExternalScreen;

@end

#endif /* MRAVVirtualOutputDevice_h */
