//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVRoutingDiscoverySession_h
#define MRAVRoutingDiscoverySession_h
@import Foundation;

@protocol OS_dispatch_queue;

@interface MRAVRoutingDiscoverySession : NSObject {
    /* instance variables */
    unsigned int _previousEndpointsDiscoveryMode;
    unsigned int _previousOutputDevicesDiscoveryMode;
}

@property(retain, nonatomic) NSMutableDictionary *endpointsChangedCallbacks;
@property(retain, nonatomic) NSMutableDictionary *endpointsAddedCallbacks;
@property(retain, nonatomic) NSMutableDictionary *endpointsRemovedCallbacks;
@property(retain, nonatomic) NSMutableDictionary *endpointsModifiedCallbacks;
@property(retain, nonatomic) NSMutableDictionary *outputDevicesChangedCallbacks;
@property(retain, nonatomic) NSMutableDictionary *outputDevicesAddedCallbacks;
@property(retain, nonatomic) NSMutableDictionary *outputDevicesRemovedCallbacks;
@property(retain, nonatomic) NSMutableDictionary *outputDevicesModifiedCallbacks;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *serialQueue;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *calloutQueue;
@property(retain, nonatomic) NSMapTable *clientDiscoveryStates;
@property(copy, nonatomic) NSArray *endpointsSnapshot;
@property(copy, nonatomic) NSArray *outputDevicesSnapshot;
@property(nonatomic) _Bool populatesExternalDevice;
@property(readonly, nonatomic) unsigned int endpointFeatures;
@property(readonly, nonatomic) _Bool devicePresenceDetected;
@property(readonly, nonatomic) NSArray *availableEndpoints;
@property(readonly, nonatomic) NSArray *availableOutputDevices;
@property(nonatomic) unsigned int discoveryMode;
@property(nonatomic) _Bool alwaysAllowUpdates;
@property(nonatomic) unsigned int targetAudioSessionID;
@property(copy, nonatomic) NSString *routingContextUID;
@property(nonatomic) _Bool onlyDiscoversBluetoothDevices;

/* class methods */
+ (id)discoverySessionWithConfiguration:(id)configuration;
+ (id)discoverySessionWithEndpointFeatures:(unsigned int)features;
+ (id)discoverySessionWithEndpointFeatures:(unsigned int)features
                          enableThrottling:(_Bool)throttling;
+ (id)sharedDiscoverySessionForClass:(Class)_class configuration:(id)configuration;

/* instance methods */
- (id)initWithConfiguration:(id)configuration;
- (id)initWithFeatures:(unsigned int)features;
- (void)removeEndpointsChangedCallback:(id)callback;
- (void)removeEndpointsRemovedCallback:(id)callback;
- (id)addEndpointsAddedCallback:(id /* block */)callback;
- (id)addEndpointsChangedCallback:(id /* block */)callback;
- (id)addEndpointsModifiedCallback:(id /* block */)callback;
- (id)addEndpointsRemovedCallback:(id /* block */)callback;
- (id)addOutputDevicesAddedCallback:(id /* block */)callback;
- (id)addOutputDevicesChangedCallback:(id /* block */)callback;
- (id)addOutputDevicesModifiedCallback:(id /* block */)callback;
- (id)addOutputDevicesRemovedCallback:(id /* block */)callback;
- (void)logEndpointsChanged:(id)changed oldEndpoints:(id)endpoints;
- (void)logOutputDevicesChanged:(id)changed oldOutputDevices:(id)devices;
- (void)notifyAvailableEndpointsChanged:(id)changed discoveredEndpoints:(id)endpoints;
- (void)notifyEndpointsChanged:(id)changed;
- (void)notifyOutputDevicesChanged:(id)changed;
- (void)removeEndpointsAddedCallback:(id)callback;
- (void)removeEndpointsModifiedCallback:(id)callback;
- (void)removeOutputDevicesAddedCallback:(id)callback;
- (void)removeOutputDevicesChangedCallback:(id)callback;
- (void)removeOutputDevicesModifiedCallback:(id)callback;
- (void)removeOutputDevicesRemovedCallback:(id)callback;

@end

#endif /* MRAVRoutingDiscoverySession_h */
