//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVDistantRoutingDiscoveryServiceProtocol_Protocol_h
#define MRAVDistantRoutingDiscoveryServiceProtocol_Protocol_h
@import Foundation;

@protocol MRAVDistantRoutingDiscoveryServiceProtocol <NSObject>

@required

/* required instance methods */
- (void)getDiscoveryModeWithCompletion:(id /* block */)completion;
- (void)getAvailableEndpointsWithCompletion:(id /* block */)completion;
- (void)getAvailableOutputDevicesWithCompletion:(id /* block */)completion;
- (void)getDevicePresenceDetectedWithCompletion:(id /* block */)completion;
- (void)setDiscoveryMode:(unsigned int)mode
        enableThrottling:(_Bool)throttling
          withCompletion:(id /* block */)completion;

@optional

@end

#endif /* MRAVDistantRoutingDiscoveryServiceProtocol_Protocol_h */
