//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVConcreteEndpoint_h
#define MRAVConcreteEndpoint_h
@import Foundation;

#include "MRConcreteEndpoint.h"

@class AVOutputDeviceGroup;

@interface MRAVConcreteEndpoint : MRConcreteEndpoint {
    /* instance variables */
    AVOutputDeviceGroup *_outputDeviceGroup;
}

/* class methods */
+ (id)errorWithChangeResult:(id)result outputDevice:(id)device;

/* instance methods */
- (void)addOutputDevices:(id)devices
               initiator:(id)initiator
          withReplyQueue:(id)queue
              completion:(id /* block */)completion;
- (void)handleVolumeCapabilityChangedNotification:(id)notification;
- (void)handleVolumeChangedNotification:(id)notification;
- (id)initWithDesignatedGroupLeader:(id)leader outputDevices:(id)devices;
- (id)initWithOutputDeviceGroup:(id)group groupLeader:(id)leader outputDevices:(id)devices;
- (void)outputDeviceVolume:(id)volume queue:(id)queue completion:(id /* block */)completion;
- (void)outputDeviceVolumeControlCapabilities:(id)capabilities
                                        queue:(id)queue
                                   completion:(id /* block */)completion;
- (void)registerVolumeNotifications;
- (void)removeOutputDevices:(id)devices
                  initiator:(id)initiator
             withReplyQueue:(id)queue
                 completion:(id /* block */)completion;
- (void)setExternalDevice:(id)device;
- (void)setOutputDeviceVolume:(float)volume
                 outputDevice:(id)device
                        queue:(id)queue
                   completion:(id /* block */)completion;
- (void)setOutputDevices:(id)devices
               initiator:(id)initiator
          withReplyQueue:(id)queue
              completion:(id /* block */)completion;
- (float)volumeForOutputDevice:(id)device error:(id *)error;

@end

#endif /* MRAVConcreteEndpoint_h */
