//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVOutputDevice_h
#define MRAVOutputDevice_h
@import Foundation;

#include "MRAVEndpoint.h"
#include "MRAVOutputDeviceSourceInfo.h"
#include "MRGroupSessionInfo.h"
#include "_MRAVOutputDeviceDescriptorProtobuf.h"

@class MRAVEndpoint;

@protocol MRRouteRecommendation;

@interface MRAVOutputDevice : NSObject

@property(copy, nonatomic) NSString *airPlayGroupID;
@property(readonly, nonatomic) NSString *groupContextID;
@property(copy, nonatomic) NSString *parentGroupIdentifier;
@property(readonly, nonatomic) NSString *baseParentGroupID;
@property(copy, nonatomic) NSString *primaryID;
@property(readonly, nonatomic) _Bool parentGroupContainsDiscoverableLeader;
@property(readonly, nonatomic) _Bool supportsRapportRemoteControlTransport;
@property(readonly, nonatomic) _Bool supportsSharePlayHandoff;
@property(readonly, nonatomic) float distance;
@property(readonly, nonatomic) _Bool discoveredOnSameInfra;
@property(readonly, nonatomic) _Bool canBeAirPlayReceiver;
@property(weak, nonatomic) MRAVEndpoint *endpoint;
@property(readonly, nonatomic) NSDictionary *roomsLookupTable;
@property(readonly, nonatomic) NSArray *rooms;
@property(copy, nonatomic) _MRAVOutputDeviceDescriptorProtobuf *descriptor;
@property(retain, nonatomic) id<MRRouteRecommendation> recommendation;
@property(readonly, nonatomic) NSString *logicalDeviceID;
@property(readonly, nonatomic) NSString *tightSyncID;
@property(readonly, nonatomic) _Bool supportsRapport;
@property(readonly, nonatomic) _Bool isAddedToHomeKit;
@property(readonly, nonatomic) _Bool auxiliary;
@property(readonly, nonatomic) NSString *currentBluetoothListeningMode;
@property(readonly, nonatomic) NSArray *availableBluetoothListeningModes;
@property(readonly, nonatomic) _Bool supportsHeadTrackedSpatialAudio;
@property(readonly, nonatomic) _Bool allowsHeadTrackedSpatialAudio;
@property(readonly, nonatomic) _Bool headTrackedSpatialAudioActive;
@property(readonly, nonatomic) NSString *headTrackedSpatialAudioMode;
@property(readonly, nonatomic) _Bool supportsConversationDetection;
@property(readonly, nonatomic) _Bool conversationDetectionEnabled;
@property(readonly, nonatomic) _Bool primaryLocalDevice;
@property(readonly, nonatomic) _Bool nearby;
@property(readonly, nonatomic) _Bool known;
@property(readonly, nonatomic) MRAVOutputDeviceSourceInfo *sourceInfo;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) NSString *uid;
@property(readonly, nonatomic) NSString *modelID;
@property(readonly, nonatomic) NSString *firmwareVersion;
@property(readonly, nonatomic) NSString *groupID;
@property(readonly, nonatomic) NSString *baseGroupID;
@property(readonly, nonatomic) NSData *MACAddress;
@property(readonly, nonatomic) NSDictionary *modelSpecificInfo;
@property(readonly, nonatomic) NSString *playingPairedDeviceName;
@property(readonly, nonatomic) _Bool canAccessRemoteAssets;
@property(readonly, nonatomic) _Bool canAccessAppleMusic;
@property(readonly, nonatomic) _Bool canAccessiCloudMusicLibrary;
@property(readonly, nonatomic) _Bool canPlayEncryptedProgressiveDownloadAssets;
@property(readonly, nonatomic) _Bool canFetchMediaDataFromSender;
@property(readonly, nonatomic)
    _Bool presentsOptimizedUserInterfaceWhenPlayingFetchedAudioOnlyAssets;
@property(readonly, nonatomic) _Bool remoteControllable;
@property(readonly, nonatomic) _Bool groupLeader;
@property(readonly, nonatomic) _Bool groupContainsGroupLeader;
@property(readonly, nonatomic) _Bool airPlayReceiverSessionActive;
@property(readonly, nonatomic) _Bool groupable;
@property(readonly, nonatomic) _Bool supportsBluetoothSharing;
@property(readonly, nonatomic) _Bool proxyGroupPlayer;
@property(readonly, nonatomic) _Bool canRelayCommunicationChannel;
@property(readonly, nonatomic) _Bool supportsBufferedAirPlay;
@property(readonly, nonatomic) _Bool canProxyEndpoint;
@property(readonly, nonatomic) _Bool supportsMultiplayer;
@property(readonly, nonatomic) _Bool eligibleForWHAPlayback;
@property(readonly, nonatomic) _Bool shouldBeLocallyHosted;
@property(readonly, nonatomic) _Bool supportsMigration;
@property(readonly, nonatomic) _Bool deviceGroupable;
@property(readonly, nonatomic) _Bool pickedOnPairedDevice;
@property(readonly, nonatomic) unsigned int deviceType;
@property(readonly, nonatomic) unsigned int deviceSubtype;
@property(readonly, nonatomic) long long hostDeviceClass;
@property(readonly, nonatomic) NSArray *clusterComposition;
@property(readonly, nonatomic) NSArray *clusterCompositionOutputDevices;
@property(readonly, nonatomic) NSArray *allClusterMembers;
@property(readonly, nonatomic) NSArray *allClusterMembersOutputDevices;
@property(readonly, nonatomic) NSArray *activatedClusterMembersOutputDevices;
@property(readonly, nonatomic) NSArray *roomOutputDevices;
@property(readonly, nonatomic) unsigned long long configuredClusterSize;
@property(readonly, nonatomic) unsigned int clusterType;
@property(readonly, nonatomic) float batteryLevel;
@property(readonly, nonatomic) _Bool hasBatteryLevel;
@property(readonly, nonatomic) _Bool localDevice;
@property(readonly, nonatomic) _Bool supportsExternalScreen;
@property(readonly, nonatomic) _Bool requiresAuthorization;
@property(readonly, nonatomic) _Bool volumeControlAvailable;
@property(readonly, nonatomic) unsigned int volumeCapabilities;
@property(readonly, nonatomic) float volume;
@property(readonly, nonatomic) _Bool volumeMuted;
@property(readonly, nonatomic) _Bool isPersonalRoute;
@property(readonly, nonatomic) _Bool producesLowFidelityAudio;
@property(readonly, nonatomic) NSString *bluetoothID;
@property(readonly, nonatomic) NSString *debugName;
@property(readonly, nonatomic) _Bool usingJSONProtocol;
@property(readonly, nonatomic) _Bool supportsHAP;
@property(readonly, nonatomic) _Bool pickable;
@property(readonly, nonatomic) long long transportType;
@property(readonly, nonatomic) NSString *clusterID;
@property(readonly, nonatomic) _Bool clusterLeader;
@property(readonly, nonatomic) NSString *parentUID;
@property(readonly, nonatomic) NSString *roomID;
@property(readonly, nonatomic) NSString *roomName;
@property(readonly, nonatomic) _Bool multiRoom;
@property(readonly, nonatomic) NSString *localizedName;
@property(readonly, nonatomic) _Bool supportsEngageOnClusterActivation;
@property(readonly, nonatomic) MRGroupSessionInfo *groupSessionInfo;
@property(readonly, nonatomic) NSString *deviceEnclosureColor;
@property(readonly, nonatomic) _Bool appleAccessory;
@property(readonly, nonatomic) NSString *capabilitiesDescription;
@property(readonly, nonatomic) NSString *composedTypeDescription;
@property(readonly, nonatomic) NSString *roleDescription;
@property(readonly, nonatomic) NSDictionary *jsonEncodableDictionaryRepresentation;
@property(readonly, nonatomic) NSArray *dnsNames;
@property(readonly, nonatomic) _Bool isAirpodsDevice;
@property(readonly, nonatomic) _Bool isB298Device;
@property(readonly, nonatomic) _Bool isB515Device;
@property(readonly, nonatomic) _Bool isB688Device;
@property(readonly, nonatomic) _Bool isB698Device;
@property(readonly, nonatomic) _Bool isB698CDevice;
@property(readonly, nonatomic) _Bool isBeatsLegacyDevice;
@property(readonly, nonatomic) _Bool isHearingDevice;
@property(readonly, nonatomic) _Bool isJ327Device;
@property(readonly, nonatomic) _Bool isB238Device;
@property(readonly, nonatomic) _Bool isB520Device;
@property(readonly, nonatomic) _Bool isB620Device;
@property(readonly, nonatomic) _Bool isHomeTheaterB520Device;

/* class methods */
+ (id)localDeviceLocalizedName;
+ (id)localDeviceUID;

/* instance methods */
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (_Bool)isAuxiliary;
- (_Bool)isNearby;
- (_Bool)isKnown;
- (_Bool)isClusterLeader;
- (_Bool)isHeadTrackedSpatialAudioActive;
- (_Bool)isAppleAccessory;
- (_Bool)isConversationDetectionEnabled;
- (_Bool)isGroupLeader;
- (_Bool)isEqualToOutputDevice:(id)device denyList:(id)list;
- (id)outputDeviceWithSourceInfoFrom:(id)from;
- (void)adjustVolume:(long long)volume details:(id)details;
- (id)clusterCompositionMembers;
- (id)clusterMembers;
- (_Bool)containsUID:(id)uid;
- (id)effectiveOutputDeviceForUID:(id)uid;
- (id)groupableOutputDevice;
- (_Bool)isAirPlayReceiverSessionActive;
- (_Bool)isDeviceGroupable;
- (_Bool)isEligibleForWHAPlayback;
- (_Bool)isEqualFuzzy:(id)fuzzy;
- (_Bool)isEqualToOutputDevice:(id)device;
- (_Bool)isEqualToOutputDevice:(id)device
                      denyList:(id)list
               addedProperties:(id *)properties
             removedProperties:(id *)properties
             changedProperties:(id *)properties;
- (_Bool)isGroupable;
- (_Bool)isLocalDevice;
- (_Bool)isMultiRoom;
- (_Bool)isPickable;
- (_Bool)isPickedOnPairedDevice;
- (_Bool)isPrimaryLocalDevice;
- (_Bool)isProxyGroupPlayer;
- (_Bool)isRemoteControllable;
- (_Bool)isUsingJSONProtocol;
- (_Bool)isVolumeControlAvailable;
- (_Bool)isVolumeMuted;
- (id)mergingVolumeFrom:(id)from;
- (void)setVolume:(float)volume details:(id)details;
- (void)setVolumeMuted:(_Bool)muted details:(id)details;

@end

#endif /* MRAVOutputDevice_h */
