//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVOutputContextEndpoint_h
#define MRAVOutputContextEndpoint_h
@import Foundation;

#include "MRAVConcreteOutputContext.h"
#include "MRAVEndpoint.h"
#include "MROrigin.h"
#include "MROutputContextController.h"

@interface MRAVOutputContextEndpoint : MRAVEndpoint <NSSecureCoding> {
    /* instance variables */
    NSString *_uniqueIdentifier;
}

@property(copy, nonatomic) NSArray *outputDevices;
@property(retain, nonatomic) MRAVConcreteOutputContext *outputContext;
@property(retain, nonatomic) MROutputContextController *outputContextController;
@property(retain, nonatomic) MROrigin *origin;
@property(readonly, nonatomic) _Bool realized;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (void)dealloc;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (long long)connectionType;
- (id)uniqueIdentifier;
- (_Bool)isConnected;
- (id)predictedOutputDevice;
- (void)resetPredictedOutputDevice;
- (void)_adjustOutputDeviceVolume:(long long)volume
                     outputDevice:(id)device
                          details:(id)details
                            queue:(id)queue
                       completion:(id /* block */)completion;
- (id)_externalOutputContext;
- (void)_modifyTopologyWithRequest:(id)request
                    withReplyQueue:(id)queue
                        completion:(id /* block */)completion;
- (void)_muteOutputDeviceVolume:(_Bool)volume
                   outputDevice:(id)device
                        details:(id)details
                          queue:(id)queue
                     completion:(id /* block */)completion;
- (void)_setOutputDeviceVolume:(float)volume
                  outputDevice:(id)device
                       details:(id)details
                         queue:(id)queue
                    completion:(id /* block */)completion;
- (_Bool)canModifyGroupMembership;
- (void)connectToExternalDeviceWithOptions:(unsigned int)options
                                  userInfo:(id)info
                                completion:(id /* block */)completion;
- (id)designatedGroupLeader;
- (id)initWithOutputContext:(id)context uniqueIdentifier:(id)identifier;
- (_Bool)isProxyGroupPlayer;
- (_Bool)isRealized;
- (void)outputContextDataSourceReloaded:(id)reloaded;
- (id)personalOutputDevices;
- (void)removeOutputDeviceFromParentGroup:(id)group
                                    queue:(id)queue
                               completion:(id /* block */)completion;
- (void)setAllowsHeadTrackedSpatialAudio:(_Bool)audio
                         outputDeviceUID:(id)uid
                                   queue:(id)queue
                              completion:(id /* block */)completion;
- (void)setConversationDetectionEnabled:(_Bool)enabled
                        outputDeviceUID:(id)uid
                                  queue:(id)queue
                             completion:(id /* block */)completion;
- (void)setHeadTrackedSpatialAudioMode:(id)mode
                       outputDeviceUID:(id)uid
                                 queue:(id)queue
                            completion:(id /* block */)completion;
- (void)setListeningMode:(id)mode
         outputDeviceUID:(id)uid
                   queue:(id)queue
              completion:(id /* block */)completion;

@end

#endif /* MRAVOutputContextEndpoint_h */
