//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVRoutingDiscoverySessionWrapper_h
#define MRAVRoutingDiscoverySessionWrapper_h
@import Foundation;

#include "MRAVRoutingDiscoverySession.h"
#include "MRAVRoutingDiscoverySessionConfiguration.h"

@interface MRAVRoutingDiscoverySessionWrapper : NSProxy {
    /* instance variables */
    NSMutableDictionary *_endpointsChangedCallbacks;
    NSMutableDictionary *_endpointsAddedCallbacks;
    NSMutableDictionary *_endpointsRemovedCallbacks;
    NSMutableDictionary *_endpointsModifiedCallbacks;
    NSMutableDictionary *_outputDevicesChangedCallbacks;
    NSMutableDictionary *_outputDevicesAddedCallbacks;
    NSMutableDictionary *_outputDevicesRemovedCallbacks;
    NSMutableDictionary *_outputDevicesModifiedCallbacks;
    NSMutableDictionary *_endpointsTokensMap;
    NSMutableDictionary *_outputDevicesTokensMap;
    unsigned int _discoveryMode;
}

@property(retain, nonatomic) MRAVRoutingDiscoverySessionConfiguration *configuration;
@property(retain, nonatomic) MRAVRoutingDiscoverySession *sharedSession;

/* instance methods */
- (void)dealloc;
- (id)debugDescription;
- (void)forwardInvocation:(id)invocation;
- (id)methodSignatureForSelector:(SEL)selector;
- (void)setDiscoveryMode:(unsigned int)mode;
- (unsigned int)discoveryMode;
- (void)removeEndpointsChangedCallback:(id)callback;
- (void)removeEndpointsRemovedCallback:(id)callback;
- (id)addEndpointsAddedCallback:(id /* block */)callback;
- (id)addEndpointsChangedCallback:(id /* block */)callback;
- (id)addEndpointsModifiedCallback:(id /* block */)callback;
- (id)addEndpointsRemovedCallback:(id /* block */)callback;
- (id)addOutputDevicesAddedCallback:(id /* block */)callback;
- (id)addOutputDevicesChangedCallback:(id /* block */)callback;
- (id)addOutputDevicesModifiedCallback:(id /* block */)callback;
- (id)addOutputDevicesRemovedCallback:(id /* block */)callback;
- (id)initWithSession:(id)session configuration:(id)configuration;
- (void)reevaluateDiscoveryModeForSession:(id)session;
- (void)removeEndpointsAddedCallback:(id)callback;
- (void)removeEndpointsModifiedCallback:(id)callback;
- (void)removeOutputDevicesAddedCallback:(id)callback;
- (void)removeOutputDevicesChangedCallback:(id)callback;
- (void)removeOutputDevicesModifiedCallback:(id)callback;
- (void)removeOutputDevicesRemovedCallback:(id)callback;
- (void)setAlwaysAllowUpdates:(_Bool)updates;
- (void)setPopulatesExternalDevice:(_Bool)device;
- (void)setRoutingContextUID:(id)uid;
- (void)setTargetAudioSessionID:(unsigned int)id;
- (void)transferCallbacksFromSession:(id)session toSession:(id)session;
- (void)transferEndpointsAddedCallbacksFromSession:(id)session toSession:(id)session;
- (void)transferEndpointsChangedCallbacksFromSession:(id)session toSession:(id)session;
- (void)transferEndpointsModifiedCallbacksFromSession:(id)session toSession:(id)session;
- (void)transferEndpointsRemovedCallbacksFromSession:(id)session toSession:(id)session;
- (void)transferOutputDevicesAddedCallbacksFromSession:(id)session toSession:(id)session;
- (void)transferOutputDevicesChangedCallbacksFromSession:(id)session toSession:(id)session;
- (void)transferOutputDevicesModifiedCallbacksFromSession:(id)session toSession:(id)session;
- (void)transferOutputDevicesRemovedCallbacksFromSession:(id)session toSession:(id)session;
- (void)updateObserversWithPreviousSession:(id)session;
- (void)updateSharedSession;

@end

#endif /* MRAVRoutingDiscoverySessionWrapper_h */
