//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVExternalRoutingDiscoverySession_h
#define MRAVExternalRoutingDiscoverySession_h
@import Foundation;

#include "MRAVEndpoint.h"
#include "MRAVRoutingDiscoverySession.h"
#include "MRAVRoutingDiscoverySessionConfiguration.h"
#include "MRExternalDevice.h"

@interface MRAVExternalRoutingDiscoverySession : MRAVRoutingDiscoverySession {
    /* instance variables */
    unsigned int _discoveryMode;
    MRAVRoutingDiscoverySessionConfiguration *_configuration;
    id _externalDeviceDiscoveryToken;
}

@property(retain, nonatomic) MRAVEndpoint *destination;
@property(retain, nonatomic) MRExternalDevice *externalDevice;

/* instance methods */
- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (id)initWithConfiguration:(id)configuration;
- (void)setDiscoveryMode:(unsigned int)mode;
- (id)availableOutputDevices;
- (_Bool)devicePresenceDetected;
- (unsigned int)discoveryMode;
- (id)availableEndpoints;
- (id)destinationOutputDeviceUID;
- (unsigned int)endpointFeatures;

@end

#endif /* MRAVExternalRoutingDiscoverySession_h */
