//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVRoutingDiscoverySessionOperation_h
#define MRAVRoutingDiscoverySessionOperation_h
@import Foundation;

#include "MRAVRoutingDiscoverySession.h"
#include "MRBlockGuard.h"

@protocol OS_dispatch_queue;

@interface MRAVRoutingDiscoverySessionOperation : NSObject {
    /* instance variables */
    NSMutableSet *_discoveredEndpoints;
    NSMutableSet *_discoveredOutputDevices;
    NSMutableSet *_discoveredTargetOutputDeviceUIDs;
    MRAVRoutingDiscoverySession *_session;
    MRBlockGuard *_guard;
    NSDate *_startDate;
    NSString *_requestID;
}

@property(readonly, copy, nonatomic) NSArray *outputDeviceUIDs;
@property(copy, nonatomic) id /* block */ outputDeviceDiscoveredHandler;
@property(copy, nonatomic) id /* block */ endpointDiscoveredHandler;
@property(copy, nonatomic) id /* block */ finishHandler;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue;

/* instance methods */
- (void)cancel;
- (void)cancelWithError:(id)error;
- (void)_finishWithError:(id)error;
- (void)_notifyDiscoveredEndpoint:(id)endpoint
                     outputDevice:(id)device
            forTargetOutputDevice:(id)device;
- (void)executeWithTimeout:(double)timeout;
- (id)initWithOutputDeviceUIDs:(id)uids;

@end

#endif /* MRAVRoutingDiscoverySessionOperation_h */
