//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVDistantOutputDevice_h
#define MRAVDistantOutputDevice_h
@import Foundation;

#include "MRAVOutputDevice.h"
#include "MRAVOutputDeviceSourceInfo.h"
#include "_MRAVOutputDeviceDescriptorProtobuf.h"

@interface MRAVDistantOutputDevice : MRAVOutputDevice <NSSecureCoding> {
    /* instance variables */
    MRAVOutputDeviceSourceInfo *_sourceInfo;
    NSDictionary *_modelSpecificInfo;
    NSArray *_clusterComposition;
    NSArray *_activatedClusterMemebers;
    NSArray *_allClusterMembers;
    NSArray *_rooms;
}

@property(readonly, nonatomic) _MRAVOutputDeviceDescriptorProtobuf *protobuf;
@property(readonly, nonatomic) _MRAVOutputDeviceDescriptorProtobuf *generateDescriptor;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)name;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)uid;
- (float)volume;
- (id)descriptor;
- (id)groupID;
- (unsigned int)deviceType;
- (long long)transportType;
- (id)firmwareVersion;
- (id)initWithDescriptor:(id)descriptor;
- (float)distance;
- (id)deviceEnclosureColor;
- (unsigned int)deviceSubtype;
- (id)modelID;
- (float)batteryLevel;
- (id)bluetoothID;
- (id)rooms;
- (unsigned int)clusterType;
- (id)primaryID;
- (id)sourceInfo;
- (_Bool)requiresAuthorization;
- (_Bool)hasBatteryLevel;
- (_Bool)supportsHeadTrackedSpatialAudio;
- (id)MACAddress;
- (_Bool)isClusterLeader;
- (_Bool)isHeadTrackedSpatialAudioActive;
- (id)logicalDeviceID;
- (_Bool)presentsOptimizedUserInterfaceWhenPlayingFetchedAudioOnlyAssets;
- (_Bool)allowsHeadTrackedSpatialAudio;
- (id)availableBluetoothListeningModes;
- (_Bool)canAccessAppleMusic;
- (_Bool)canAccessRemoteAssets;
- (_Bool)canAccessiCloudMusicLibrary;
- (_Bool)canFetchMediaDataFromSender;
- (_Bool)canPlayEncryptedProgressiveDownloadAssets;
- (_Bool)canRelayCommunicationChannel;
- (id)clusterID;
- (unsigned long long)configuredClusterSize;
- (id)currentBluetoothListeningMode;
- (_Bool)groupContainsGroupLeader;
- (id)headTrackedSpatialAudioMode;
- (_Bool)isAppleAccessory;
- (_Bool)isConversationDetectionEnabled;
- (_Bool)isGroupLeader;
- (_Bool)producesLowFidelityAudio;
- (_Bool)supportsBluetoothSharing;
- (_Bool)supportsBufferedAirPlay;
- (_Bool)supportsConversationDetection;
- (id)roomName;
- (long long)hostDeviceClass;
- (_Bool)supportsRapport;
- (id)activatedClusterMembersOutputDevices;
- (id)airPlayGroupID;
- (id)allClusterMembers;
- (id)clusterComposition;
- (_Bool)discoveredOnSameInfra;
- (id)dnsNames;
- (id)groupSessionInfo;
- (id)groupableOutputDevice;
- (id)initWithSkeleton:(id)skeleton;
- (_Bool)isAddedToHomeKit;
- (_Bool)isAirPlayReceiverSessionActive;
- (_Bool)isDeviceGroupable;
- (_Bool)isGroupable;
- (_Bool)isLocalDevice;
- (_Bool)isPickable;
- (_Bool)isPickedOnPairedDevice;
- (_Bool)isProxyGroupPlayer;
- (_Bool)isRemoteControllable;
- (_Bool)isUsingJSONProtocol;
- (_Bool)isVolumeMuted;
- (id)modelSpecificInfo;
- (_Bool)parentGroupContainsDiscoverableLeader;
- (id)parentGroupIdentifier;
- (id)parentUID;
- (id)playingPairedDeviceName;
- (id)roomID;
- (_Bool)supportsEngageOnClusterActivation;
- (_Bool)supportsExternalScreen;
- (_Bool)supportsHAP;
- (_Bool)supportsMultiplayer;
- (_Bool)supportsRapportRemoteControlTransport;
- (_Bool)supportsSharePlayHandoff;
- (id)tightSyncID;
- (unsigned int)volumeCapabilities;

@end

#endif /* MRAVDistantOutputDevice_h */
