//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVReconnaissanceSession_h
#define MRAVReconnaissanceSession_h
@import Foundation;

#include "MRAVEndpoint.h"
#include "MRAVRoutingDiscoverySession.h"

@protocol OS_dispatch_queue
, OS_dispatch_source;

@interface MRAVReconnaissanceSession : NSObject {
    /* instance variables */
    double _timeoutTimerTimeout;
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSMutableDictionary *_localMatchingDevicesFound;
    NSMutableSet *_knownIncompleteClusterMembers;
    _Bool _searchInProgress;
    _Bool _shouldWaitForUnanimousEndpoints;
    NSSet *_matchingOutputDeviceUIDsSet;
    id _discoverySessionCallbackToken;
    id /* block */ _callback;
    NSObject<OS_dispatch_source> *_timeoutTimer;
    NSMutableDictionary *_matchingDevicesFound;
    NSMutableArray *_matchingEndpointsFound;
    MRAVEndpoint *_unanimousEndpoint;
    NSArray *_availableOutputDevices;
    NSArray *_availableEndpoints;
    unsigned long long _updatesReceived;
    NSArray *_lastProcessedOutputDevices;
    NSArray *_lastProcessedEndpoints;
    unsigned long long _expectedLogicalDevices;
}

@property(readonly, nonatomic) NSArray *matchingOutputDeviceUIDs;
@property(readonly, nonatomic) NSString *matchingOutputDeviceGroupID;
@property(readonly, nonatomic) unsigned int endpointFeatures;
@property(readonly, nonatomic) MRAVRoutingDiscoverySession *discoverySession;
@property(nonatomic) _Bool useWeakMatching;
@property(nonatomic) _Bool returnPartialResults;
@property(nonatomic) _Bool waitForCompleteClusters;
@property(copy, nonatomic) NSArray *matchingLogicalDeviceIDs;

/* instance methods */
- (void)dealloc;
- (void)cancelSearch;
- (void)beginSearchWithTimeout:(double)timeout completion:(id /* block */)completion;
- (void)beginSearchWithTimeout:(double)timeout endpointsCompletion:(id /* block */)completion;
- (void)beginSearchWithTimeout:(double)timeout mapCompletion:(id /* block */)completion;
- (id)initWithOutputDeviceUIDs:(id)uids outputDeviceGroupID:(id)id features:(unsigned int)features;

@end

#endif /* MRAVReconnaissanceSession_h */
