//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVXPCPipeTransport_h
#define MRAVXPCPipeTransport_h
@import Foundation;

#include "MRAVOutputDevice.h"
#include "MRDeviceInfo.h"
#include "MRExternalDeviceTransport.h"
#include "MRVirtualDevicePipeProtocol-Protocol.h"

@class CURunLoopThread;
@protocol OS_dispatch_queue;

@interface MRAVXPCPipeTransport
    : MRExternalDeviceTransport <NSStreamDelegate, MRVirtualDevicePipeProtocol> {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_serialQueue;
    MRDeviceInfo *_deviceInfo;
    NSError *_error;
    NSInputStream *_inputStream;
    NSInputStream *_inputStreamInternal;
    NSOutputStream *_outputStream;
    NSOutputStream *_outputStreamInternal;
    _Bool _useSystemAuthenticationPrompt;
    NSXPCConnection *_pipeConnection;
    NSRunLoop *_runLoop;
    CURunLoopThread *_runLoopThread;
}

@property(readonly, nonatomic) MRAVOutputDevice *outputDevice;
@property(readonly, nonatomic) NSXPCListenerEndpoint *pipeEndpoint;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (id)name;
- (id)error;
- (long long)port;
- (void)stream:(id)stream handleEvent:(unsigned long long)event;
- (id)uid;
- (void)reset;
- (id)hostname;
- (id)deviceInfo;
- (void)sendData:(id)data;
- (void)_onQueue_resetStreams;
- (id)createConnectionWithUserInfo:(id)info;
- (_Bool)getInputStream:(id *)stream outputStream:(id *)stream userInfo:(id)info;
- (id)initWithOutputDevice:(id)device pipeEndpoint:(id)endpoint;
- (_Bool)requiresCustomPairing;
- (void)setShouldUseSystemAuthenticationPrompt:(_Bool)prompt;
- (_Bool)shouldUseSystemAuthenticationPrompt;

@end

#endif /* MRAVXPCPipeTransport_h */
