//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVRoutingClientController_h
#define MRAVRoutingClientController_h
@import Foundation;

#include "MRMediaRemoteService.h"

@protocol OS_dispatch_queue;

@interface MRAVRoutingClientController : NSObject {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSObject<OS_dispatch_queue> *_callbackQueue;
    NSMutableDictionary *_pendingCompletionHandlersForCategories;
    NSMutableDictionary *_cachedRoutesForCategories;
}

@property(readonly, nonatomic) MRMediaRemoteService *mediaRemoteService;

/* instance methods */
- (void)dealloc;
- (id)init;
- (void)_pickableRoutesDidChangeNotification:(id)notification;
- (void)fetchPickableRoutesForCategory:(id)category completion:(id /* block */)completion;
- (id)initWithMediaRemoteService:(id)service;

@end

#endif /* MRAVRoutingClientController_h */
