//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVDistantEndpoint_h
#define MRAVDistantEndpoint_h
@import Foundation;

#include "MRAVDistantOutputDevice.h"
#include "MRAVEndpoint.h"
#include "MRDistantExternalDevice.h"

@protocol OS_dispatch_queue;

@interface MRAVDistantEndpoint : MRAVEndpoint <NSSecureCoding> {
    /* instance variables */
    _Bool _canModifyGroupMembership;
    long long _connectionType;
    NSString *_localizedName;
    NSString *_uniqueIdentifier;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *externalDeviceQueue;
@property(copy, nonatomic) NSArray *distantOutputDevices;
@property(copy, nonatomic) NSArray *distantPersonalOutputDevices;
@property(retain, nonatomic) MRAVDistantOutputDevice *distantGroupLeader;
@property(retain, nonatomic) MRDistantExternalDevice *distantExternalDevice;
@property(retain, nonatomic) NSXPCListenerEndpoint *externalDeviceListenerEndpoint;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)externalDeviceFactory;

/* instance methods */
- (void)dealloc;
- (id)debugDescription;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (long long)connectionType;
- (id)localizedName;
- (id)uniqueIdentifier;
- (_Bool)isConnected;
- (void)setUniqueIdentifier:(id)identifier;
- (id)initWithDescriptor:(id)descriptor;
- (void)setLocalizedName:(id)name;
- (id)outputDevices;
- (id)_externalOutputContext;
- (void)_handleConnectionStateDidChangeNotification:(id)notification;
- (void)_handleGroupSessionTokenDidChangeNotification:(id)notification;
- (_Bool)canModifyGroupMembership;
- (id)designatedGroupLeader;
- (id)externalDevice;
- (id)groupSessionInfo;
- (_Bool)isProxyGroupPlayer;
- (id)personalOutputDevices;

@end

#endif /* MRAVDistantEndpoint_h */
