//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRAVOutputContextModification_h
#define MRAVOutputContextModification_h
@import Foundation;

#include "MRGroupTopologyModificationRequest.h"

@interface MRAVOutputContextModification : NSObject <NSSecureCoding>

@property(readonly, nonatomic) NSArray *discoveredConcreteOutputDevices;
@property(readonly, nonatomic) NSArray *avOutputDevices;
@property(readonly, nonatomic) MRGroupTopologyModificationRequest *request;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)description;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithRequest:(id)request;
- (void)modifyWithOutputContext:(id)context queue:(id)queue completion:(id /* block */)completion;

@end

#endif /* MRAVOutputContextModification_h */
