//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRBaseBannerRequest_h
#define MRBaseBannerRequest_h
@import Foundation;

#include "MRBannerRequestRepresentable-Protocol.h"

@interface MRBaseBannerRequest : NSObject <MRBannerRequestRepresentable>

@property(retain, nonatomic) NSString *requestIdentifier;
@property(retain, nonatomic) NSString *bundleIdentifierAffinity;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)requestWithBundleIdentifierAffinity:(id)affinity;

/* instance methods */
- (_Bool)isEqual:(id)equal;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithBundleIdentifierAffinity:(id)affinity;

@end

#endif /* MRBaseBannerRequest_h */
