//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRClientUpdatesConfigMessage_h
#define MRClientUpdatesConfigMessage_h
@import Foundation;

#include "MRProtocolMessage.h"

@interface MRClientUpdatesConfigMessage : MRProtocolMessage

@property(copy, nonatomic) NSArray *subscribedPlayerPaths;
@property(readonly, nonatomic) _Bool nowPlayingUpdates;
@property(readonly, nonatomic) _Bool artworkUpdates;
@property(readonly, nonatomic) _Bool volumeUpdates;
@property(readonly, nonatomic) _Bool keyboardUpdates;
@property(readonly, nonatomic) _Bool outputDeviceUpdates;
@property(readonly, nonatomic) _Bool systemEndpointUpdates;

/* instance methods */
- (unsigned long long)type;
- (id)initWithNowPlayingUpdates:(_Bool)updates
                 artworkUpdates:(_Bool)updates
                  volumeUpdates:(_Bool)updates
                keyboardUpdates:(_Bool)updates
            outputDeviceUpdates:(_Bool)updates
          systemEndpointUpdates:(_Bool)updates
          subscribedPlayerPaths:(id)paths;
- (id)initWithUnderlyingCodableMessage:(id)message error:(id)error;

@end

#endif /* MRClientUpdatesConfigMessage_h */
