//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRClient_h
#define MRClient_h
@import Foundation;

#include "MRColorComponents.h"
#include "_MRNowPlayingClientProtobuf.h"

@interface MRClient : NSObject <NSCopying, NSSecureCoding>

@property(readonly, nonatomic) _MRNowPlayingClientProtobuf *protobuf;
@property(nonatomic) int processIdentifier;
@property(nonatomic) unsigned int processUserIdentifier;
@property(nonatomic) long long visibility;
@property(copy, nonatomic) MRColorComponents *tintColor;
@property(copy, nonatomic) NSString *bundleIdentifier;
@property(copy, nonatomic) NSString *parentApplicationBundleIdentifier;
@property(copy, nonatomic) NSString *displayName;
@property(readonly, copy, nonatomic) NSString *representedBundleID;
@property(copy, nonatomic) NSArray *extendedBundleIdentifierHierarchy;
@property(copy, nonatomic) NSURL *appIcon;
@property(readonly, nonatomic) _Bool hasPlaceholder;
@property(readonly, nonatomic) _Bool hasAuxiliaryProperties;
@property(readonly, nonatomic) _Bool systemMediaApplication;
@property(readonly, nonatomic) _Bool systemPodcastsApplication;
@property(readonly, nonatomic) _Bool systemBooksApplication;
@property(readonly, nonatomic) _Bool airPlay;
@property(readonly, nonatomic) MRClient *skeleton;
@property(readonly, nonatomic) NSData *data;
@property(readonly, copy, nonatomic) NSArray *bundleIdentifierHierarchy;
@property(readonly, nonatomic) _Bool local;
@property(readonly, nonatomic) _Bool valid;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)anyClient;
+ (id)localClient;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)debugDescription;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (_Bool)isValid;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithData:(id)data;
- (id)initWithBundleIdentifier:(id)identifier;
- (void)mergeFrom:(id)from;
- (_Bool)isLocal;
- (id)initWithProcessIdentifier:(int)identifier bundleIdentifier:(id)identifier;
- (id)initWithProtobuf:(id)protobuf;
- (_Bool)isAirPlay;
- (_Bool)isSystemBooksApplication;
- (_Bool)isSystemMediaApplication;
- (_Bool)isSystemPodcastsApplication;
- (void)resolvePlaceholdersForDeviceInfo:(id)info;

@end

#endif /* MRClient_h */
