//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRCompanionLinkClientRequest_h
#define MRCompanionLinkClientRequest_h
@import Foundation;

#include "MRCompanionLinkClientEvent.h"

@interface MRCompanionLinkClientRequest : MRCompanionLinkClientEvent

@property(retain, nonatomic) NSDate *date;
@property(copy, nonatomic) id /* block */ callback;

/* instance methods */

@end

#endif /* MRCompanionLinkClientRequest_h */
