//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRContentItemRequest_h
#define MRContentItemRequest_h
@import Foundation;

#include "MRContentItem.h"
#include "MRPlaybackQueueRequest.h"

@interface MRContentItemRequest : NSObject <NSSecureCoding>

@property(retain, nonatomic) MRContentItem *item;
@property(retain, nonatomic) MRPlaybackQueueRequest *request;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)description;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithItem:(id)item request:(id)request;

@end

#endif /* MRContentItemRequest_h */
