//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRCodableGroupSessionParticipant_h
#define MRCodableGroupSessionParticipant_h
@import Foundation;

#include "MRGroupSessionParticipant-Protocol.h"
#include "MRUserIdentity.h"

@interface MRCodableGroupSessionParticipant : NSObject <MRGroupSessionParticipant, NSSecureCoding>

@property(retain, nonatomic) NSString *identifier;
@property(retain, nonatomic) MRUserIdentity *identity;
@property(nonatomic) _Bool pending;
@property(nonatomic) _Bool connected;
@property(nonatomic) _Bool guest;
@property(nonatomic) _Bool local;
@property(nonatomic) _Bool host;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (_Bool)isEqual:(id)equal;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (_Bool)isConnected;
- (_Bool)isPending;
- (_Bool)isLocal;
- (_Bool)isGuest;
- (id)initWithIdentifier:(id)identifier identity:(id)identity;
- (_Bool)isHost;

@end

#endif /* MRCodableGroupSessionParticipant_h */
