//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRCommandResult_h
#define MRCommandResult_h
@import Foundation;

#include "MRPlayerPath.h"

@interface MRCommandResult : NSObject <NSCopying>

@property(copy, nonatomic) NSArray *resultStatuses;
@property(nonatomic) unsigned int sendError;
@property(copy, nonatomic) NSError *error;
@property(retain, nonatomic) NSString *sendErrorDescription;
@property(copy, nonatomic) MRPlayerPath *playerPath;
@property(nonatomic) unsigned int startQOS;
@property(nonatomic) unsigned int endQOS;
@property(readonly, copy, nonatomic) NSArray *handlerReturnStatuses;

/* class methods */
+ (id)commandResultWithSendError:(unsigned int)error;
+ (id)commandResultWithSendError:(unsigned int)error description:(id)description;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (id)data;
- (id)initWithData:(id)data;
- (id)initWithError:(id)error;
- (id)protobuf;
- (id)copyWithPlayerPath:(id)path;
- (id)initWithHandlerStatuses:(id)statuses sendError:(unsigned int)error;
- (id)initWithProtobuf:(id)protobuf;
- (id)initWithResultStatuses:(id)statuses sendError:(unsigned int)error playerPath:(id)path;
- (id)initWithWithSendError:(unsigned int)error description:(id)description;

@end

#endif /* MRCommandResult_h */
