//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRConcreteEndpoint_h
#define MRConcreteEndpoint_h
@import Foundation;

#include "MRAVEndpoint.h"
#include "MRAVOutputDevice.h"
#include "MRExternalDevice.h"

@protocol OS_dispatch_queue;

@interface MRConcreteEndpoint : MRAVEndpoint {
    /* instance variables */
    NSString *_uniqueIdentifier;
    MRExternalDevice *_externalDevice;
    MRAVOutputDevice *_designatedGroupLeader;
    long long _connectionType;
    NSObject<OS_dispatch_queue> *_serialQueue;
}

@property(copy, nonatomic) NSArray *outputDevices;

/* instance methods */
- (long long)connectionType;
- (id)uniqueIdentifier;
- (_Bool)canModifyGroupMembership;
- (id)designatedGroupLeader;
- (id)externalDevice;
- (id)initWithDesignatedGroupLeader:(id)leader outputDevices:(id)devices preferredSuffix:(id)suffix;
- (id)initWithDesignatedGroupLeader:(id)leader
                      outputDevices:(id)devices
                    preferredSuffix:(id)suffix
                     connectionType:(long long)type;
- (_Bool)isProxyGroupPlayer;
- (void)setExternalDevice:(id)device;

@end

#endif /* MRConcreteEndpoint_h */
