//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRCryptoPairingMessage_h
#define MRCryptoPairingMessage_h
@import Foundation;

#include "MRProtocolMessage.h"

@interface MRCryptoPairingMessage : MRProtocolMessage

@property(readonly, nonatomic) NSData *pairingData;
@property(readonly, nonatomic) int status;
@property(readonly, nonatomic) _Bool retrying;
@property(readonly, nonatomic) _Bool usingSystemPairing;
@property(readonly, nonatomic) unsigned long long state;

/* instance methods */
- (unsigned long long)type;
- (unsigned long long)encryptionType;
- (id)initWithPairingData:(id)data status:(int)status;
- (id)initWithPairingData:(id)data
                   status:(int)status
               isRetrying:(_Bool)retrying
     isUsingSystemPairing:(_Bool)pairing
                    state:(unsigned long long)state;
- (_Bool)isRetrying;
- (_Bool)isUsingSystemPairing;

@end

#endif /* MRCryptoPairingMessage_h */
