//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRCryptoPairingSession_h
#define MRCryptoPairingSession_h
@import Foundation;

#include "MRCryptoPairingSessionDelegate-Protocol.h"
#include "MRDeviceInfo.h"

@interface MRCryptoPairingSession : NSObject

@property(readonly, nonatomic) MRDeviceInfo *device;
@property(readonly, nonatomic) unsigned long long role;
@property(readonly, nonatomic) _Bool valid;
@property(readonly, nonatomic) _Bool paired;
@property(readonly, nonatomic) NSArray *pairedDevices;
@property(weak, nonatomic) id<MRCryptoPairingSessionDelegate> delegate;

/* class methods */
+ (id)allocWithZone:(struct _NSZone *)zone;

/* instance methods */
- (id)init;
- (_Bool)isValid;
- (void)close;
- (void)open;
- (_Bool)isPaired;
- (void)handlePairingFailureWithStatus:(int)status;
- (id)decryptData:(id)data withError:(id *)error;
- (_Bool)deleteIdentityWithError:(id *)error;
- (id)encryptData:(id)data withError:(id *)error;
- (void)handlePairingExchangeData:(id)data completion:(id /* block */)completion;
- (id)initWithRole:(unsigned long long)role device:(id)device;
- (id)removePeer;
- (id)updatePeer;

@end

#endif /* MRCryptoPairingSession_h */
