//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRDestination_h
#define MRDestination_h
@import Foundation;

#include "MRAVEndpoint.h"
#include "MRClient.h"
#include "MROrigin.h"
#include "MRPlayer.h"
#include "MRPlayerPath.h"
#include "_MRDestinationProtobuf.h"

@interface MRDestination : NSObject <NSCopying, NSSecureCoding>

@property(retain, nonatomic) NSString *outputDeviceUID;
@property(retain, nonatomic) MRAVEndpoint *endpoint;
@property(copy, nonatomic) MRPlayerPath *playerPath;
@property(retain, nonatomic) MROrigin *origin;
@property(readonly, nonatomic) NSData *data;
@property(readonly, nonatomic) _MRDestinationProtobuf *protobuf;
@property(readonly, nonatomic) NSString *outputContextUID;
@property(readonly, nonatomic) _Bool isLocal;
@property(readonly, nonatomic) _Bool isProactive;
@property(readonly, nonatomic) _Bool isUserSelected;
@property(copy, nonatomic) MRClient *client;
@property(copy, nonatomic) MRPlayer *player;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)localDestination;
+ (id)proactiveDestination;
+ (id)userSelectedDestination;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithData:(id)data;
- (id)_init;
- (id)initWithEndpoint:(id)endpoint;
- (id)initWithOrigin:(id)origin;
- (id)initWithOutputContextUID:(id)uid;
- (id)initWithOutputDeviceUID:(id)uid;
- (id)initWithPlayerPath:(id)path;
- (id)initWithProtobuf:(id)protobuf;
- (void)populatePlayerPathIfNeeded;

@end

#endif /* MRDestination_h */
