//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRDestinationResolverDelegate_Protocol_h
#define MRDestinationResolverDelegate_Protocol_h
@import Foundation;

@protocol MRDestinationResolverDelegate <NSObject>

@required

@optional

/* optional instance methods */
- (void)destinationResolver:(id)resolver didFailWithError:(id)error;
- (void)destinationResolver:(id)resolver endpointDidChange:(id)change;
- (void)destinationResolver:(id)resolver originDidChange:(id)change;
- (void)destinationResolver:(id)resolver playerPathDidChange:(id)change;
- (void)destinationResolverDestinationDidInvalidate:(id)invalidate;

@end

#endif /* MRDestinationResolverDelegate_Protocol_h */
