//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRDestinationResolverHelper_h
#define MRDestinationResolverHelper_h
@import Foundation;

#include "MRDestinationResolverDelegate-Protocol.h"

@interface MRDestinationResolverHelper : NSObject <MRDestinationResolverDelegate>

@property(nonatomic) long long level;
@property(copy, nonatomic) id /* block */ callback;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)destinationResolver:(id)resolver didFailWithError:(id)error;
- (void)destinationResolver:(id)resolver endpointDidChange:(id)change;
- (void)destinationResolver:(id)resolver originDidChange:(id)change;
- (void)destinationResolver:(id)resolver playerPathDidChange:(id)change;
- (void)destinationResolverDestinationDidInvalidate:(id)invalidate;

@end

#endif /* MRDestinationResolverHelper_h */
