//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRDiscoveredGroupSession_h
#define MRDiscoveredGroupSession_h
@import Foundation;

#include "MRGroupSessionHostInfo.h"

@interface MRDiscoveredGroupSession : NSObject <NSSecureCoding, NSCopying>

@property(readonly, nonatomic) NSData *data;
@property(readonly, nonatomic) NSString *identifier;
@property(readonly, nonatomic) MRGroupSessionHostInfo *hostInfo;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithData:(id)data;
- (id)initWithIdentifier:(id)identifier hostInfo:(id)info;

@end

#endif /* MRDiscoveredGroupSession_h */
