//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MREmulatedGameController_h
#define MREmulatedGameController_h
@import Foundation;

#include "MRGameControllerDaemonProxy.h"

@class GCController;
@protocol MREmulatedGameControllerDelegate;

@interface MREmulatedGameController : NSObject {
    /* instance variables */
    MRGameControllerDaemonProxy *_remote;
}

@property(retain, nonatomic) GCController *controller;
@property(readonly, nonatomic) int profile;
@property(nonatomic) double buttonAUpDelay;
@property(weak, nonatomic) id<MREmulatedGameControllerDelegate> delegate;

/* instance methods */
- (void)dealloc;
- (id)initWithProperties:(id)properties;
- (void)_handleGameControllerDidChange:(id)change;
- (void)sendGameControllerEvent:(id)event;

@end

#endif /* MREmulatedGameController_h */
