//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRExternalOutputContextDataSource_h
#define MRExternalOutputContextDataSource_h
@import Foundation;

#include "MROutputContextDataSource.h"

@interface MRExternalOutputContextDataSource : MROutputContextDataSource <NSSecureCoding> {
    /* instance variables */
    NSString *_uniqueIdentifier;
    NSMutableArray *_outputDevices;
    float _masterVolume;
    unsigned int _masterVolumeControlCapabilities;
    _Bool _groupVolumeMuted;
}

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)uniqueIdentifier;
- (float)volume;
- (id)outputDevices;
- (id)initWithUniqueIdentifier:(id)identifier;
- (void)initializeVolumeCapabilitiesForLegacyCleints;
- (_Bool)isVolumeMuted;
- (void)removeAllOutputDevices;
- (void)removeOutputDevices:(id)devices;
- (void)updateOutputDevices:(id)devices;
- (void)updateVolume:(float)volume outputDeviceUID:(id)uid;
- (void)updateVolumeControlCapabilities:(unsigned int)capabilities outputDeviceUID:(id)uid;
- (void)updateVolumeMuted:(_Bool)muted outputDeviceUID:(id)uid;
- (unsigned int)volumeControlCapabilities;

@end

#endif /* MRExternalOutputContextDataSource_h */
