//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRExternalDevicePairingSession_h
#define MRExternalDevicePairingSession_h
@import Foundation;

#include "MRCoreUtilsPairingSession.h"
#include "MRCryptoPairingSession.h"
#include "MRCryptoPairingSessionBlockDelegate.h"

@interface MRExternalDevicePairingSession : MRCryptoPairingSession

@property(retain, nonatomic) MRCoreUtilsPairingSession *pairingSession;
@property(retain, nonatomic) MRCryptoPairingSessionBlockDelegate *pairingDelegate;
@property(readonly, nonatomic) _Bool hasExchangedMessage;
@property(readonly, nonatomic) _Bool usingSystemPairing;
@property(readonly, nonatomic) unsigned long long state;

/* instance methods */
- (_Bool)isValid;
- (void)close;
- (void)open;
- (void)setDelegate:(id)delegate;
- (id)initWithDevice:(id)device;
- (id)pairedDevices;
- (_Bool)isPaired;
- (void)handlePairingFailureWithStatus:(int)status;
- (id)decryptData:(id)data withError:(id *)error;
- (_Bool)deleteIdentityWithError:(id *)error;
- (id)encryptData:(id)data withError:(id *)error;
- (void)handlePairingExchangeData:(id)data completion:(id /* block */)completion;
- (_Bool)isUsingSystemPairing;
- (id)removePeer;
- (id)updatePeer;

@end

#endif /* MRExternalDevicePairingSession_h */
