//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRExpanseManager_h
#define MRExpanseManager_h
@import Foundation;

#include "TUConversationManagerDelegate-Protocol.h"

@class AVAudioSession, TUConversationManager, TUNeighborhoodActivityConduit;
@protocol OS_dispatch_queue;

@interface MRExpanseManager : NSObject <TUConversationManagerDelegate>

@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *notifyQueue;
@property(readonly, nonatomic) NSHashTable *observers;
@property(readonly, nonatomic) TUConversationManager *conversationManager;
@property(readonly, nonatomic) TUNeighborhoodActivityConduit *conduit;
@property(retain, nonatomic) AVAudioSession *auxiliaryPlaybackAudioSession;
@property(readonly, nonatomic) _Bool expanseSessionActive;
@property(readonly, nonatomic) _Bool expanseSessionHasActiveActivity;
@property(readonly, nonatomic) _Bool expanseSessionHasRemoteActivity;
@property(readonly, nonatomic) _Bool expanseSessionHasScreenSharingActivity;
@property(readonly, nonatomic) _Bool expanseHandoffSupported;
@property(readonly, nonatomic) NSString *activeTelevisionRouteID;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)sharedManager;

/* instance methods */
- (void)dealloc;
- (void)removeObserver:(id)observer;
- (void)addObserver:(id)observer;
- (id)initWithQueue:(id)queue;
- (_Bool)activeActivityExistsForBundle:(id)bundle;
- (id)activeConversation;
- (void)addTelevisionWithRouteIdentifierToSession:(id)session completion:(id /* block */)completion;
- (_Bool)deviceIsActiveTelevision:(id)television;
- (_Bool)errorIsTelevisionCapabilitiesError:(id)error;
- (void)removeTelevisionWithRouteIdentifierFromSession:(id)session
                                            completion:(id /* block */)completion;

@end

#endif /* MRExpanseManager_h */
