//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRExternalDeviceConnectionDetails_h
#define MRExternalDeviceConnectionDetails_h
@import Foundation;

@interface MRExternalDeviceConnectionDetails : NSObject

@property(retain, nonatomic) NSDate *startDate;
@property(retain, nonatomic) NSString *reason;
@property(retain, nonatomic) NSString *requestID;
@property(nonatomic) unsigned int qos;
@property(copy, nonatomic) id /* block */ completion;

/* instance methods */
- (id)description;

@end

#endif /* MRExternalDeviceConnectionDetails_h */
