//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRExternalJSONClientConnection_h
#define MRExternalJSONClientConnection_h
@import Foundation;

#include "MRExternalClientConnection.h"

@interface MRExternalJSONClientConnection : MRExternalClientConnection {
    /* instance variables */
    NSDictionary *_artwork;
    NSDictionary *_deviceInfo;
    NSDictionary *_volume;
    NSDictionary *_playerPath;
    NSDictionary *_playbackQueue;
    NSDictionary *_supportedCommands;
}

/* instance methods */
- (id)dataForMessage:(id)message;
- (id)_createProtocolMessage:(Class)message underlyingCodableMessage:(id)message;
- (id)_encodeDeviceInfo:(id)info;
- (id)_encodeVolumeDidChange:(id)change;
- (id)_processDeviceInfo:(id)info;
- (id)_processSetState:(id)state;
- (id)_protocolMessageFromData:(id)data;
- (id)initWithConnection:(id)connection queue:(id)queue;

@end

#endif /* MRExternalJSONClientConnection_h */
