//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRExternalDeviceController_h
#define MRExternalDeviceController_h
@import Foundation;

#include "MRExternalDeviceControllerDelegate-Protocol.h"
#include "NSNetServiceBrowserDelegate-Protocol.h"
#include "NSNetServiceDelegate-Protocol.h"

@class NSNetServiceBrowser;
@protocol OS_dispatch_queue;

@interface MRExternalDeviceController
    : NSObject <NSNetServiceBrowserDelegate, NSNetServiceDelegate> {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSNetServiceBrowser *_serviceBrowser;
    NSMutableSet *_discoveredDevices;
    NSMutableSet *_resolvingServices;
    NSMutableSet *_monitoringServices;
}

@property(weak, nonatomic) id<MRExternalDeviceControllerDelegate> delegate;
@property(readonly, nonatomic) NSString *bonjourServiceType;
@property(readonly, nonatomic) _Bool discovering;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* class methods */
+ (Class)externalDeviceClass;

/* instance methods */
- (void)dealloc;
- (void)netService:(id)service didUpdateTXTRecordData:(id)data;
- (void)netServiceBrowser:(id)browser didFindService:(id)service moreComing:(_Bool)coming;
- (void)netServiceBrowser:(id)browser didRemoveService:(id)service moreComing:(_Bool)coming;
- (void)netServiceDidResolveAddress:(id)address;
- (_Bool)_isManagedConfigIDAllowed:(id)idallowed;
- (void)beginDiscovery;
- (void)endDiscovery;
- (id)initWithBonjourServiceType:(id)type;
- (_Bool)isDiscovering;

@end

#endif /* MRExternalDeviceController_h */
