//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRExternalClientConnection_h
#define MRExternalClientConnection_h
@import Foundation;

#include "MRCryptoPairingSession.h"
#include "MRProtocolClientConnection.h"

@interface MRExternalClientConnection : MRProtocolClientConnection

@property(copy, nonatomic) NSArray *subscribedPlayerPaths;
@property(nonatomic) _Bool registeredToNowPlayingUpdates;
@property(nonatomic) _Bool registeredToVolumeUpdates;
@property(nonatomic) _Bool registeredKeyboardUpdates;
@property(nonatomic) _Bool registeredToOutputDeviceUpdates;
@property(nonatomic) _Bool registeredToSystemEndpointUpdates;
@property(nonatomic) unsigned int voiceRecordingState;
@property(retain, nonatomic) MRCryptoPairingSession *cryptoSession;
@property(nonatomic) _Bool cryptoEnabled;

/* instance methods */
- (id)initWithConnection:(id)connection queue:(id)queue;

@end

#endif /* MRExternalClientConnection_h */
