//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRGameControllerDaemonProxy_h
#define MRGameControllerDaemonProxy_h
@import Foundation;

#include "GameControllerDaemonListener-Protocol.h"
#include "MRGameControllerDelayedEvents.h"

@interface MRGameControllerDaemonProxy : NSObject <GameControllerDaemonListener> {
    /* instance variables */
    NSXPCConnection *_connection;
    MRGameControllerDelayedEvents *_delayedEvents;
}

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)defaultGameControllerDaemonProxy;

/* instance methods */
- (void)addController:(id)controller;
- (void)controllerWithUDID:(unsigned long long)udid setData:(id)data;
- (void)controllerWithUDID:(unsigned long long)udid setValue:(float)value forElement:(int)element;
- (void)microControllerWithDigitizerX:(float)x
                                withY:(float)y
                        withTimeStamp:(unsigned long long)stamp
                            touchDown:(_Bool)down;
- (void)microControllerWithUDID:(unsigned long long)udid
                  setDigitizerX:(float)x
                     digitizerY:(float)y
                  withTimeStamp:(unsigned long long)stamp
                      touchDown:(_Bool)down;
- (void)removeController:(id)controller;
- (void)_openConnection;
- (_Bool)_delayEvent:(unsigned long long)event
            setValue:(float)value
          forElement:(int)element
         withUpDelay:(double)delay;
- (id)addEmulatedControllerWithProperties:(id)properties;
- (void)controllerID:(unsigned long long)id
      setArrayValueX:(float)x
                   y:(float)y
                   z:(float)z
                   w:(float)w
          forElement:(int)element;
- (void)controllerID:(unsigned long long)id
       setDigitizerX:(float)x
          digitizerY:(float)y
       withTimeStamp:(unsigned long long)stamp
           touchDown:(_Bool)down;
- (void)controllerID:(unsigned long long)id setValue:(float)value forElement:(int)element;
- (void)controllerID:(unsigned long long)id
            setValue:(float)value
          forElement:(int)element
         withUpDelay:(double)delay;
- (void)removeEmulatedController:(id)controller;
- (void)replyConnectedHosts:(id)hosts;

@end

#endif /* MRGameControllerDaemonProxy_h */
