//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRGroupTopologyModificationRequest_h
#define MRGroupTopologyModificationRequest_h
@import Foundation;

#include "MRRequestDetails.h"
#include "_MRGroupTopologyModificationRequestProtobuf.h"

@interface MRGroupTopologyModificationRequest : NSObject <NSSecureCoding, NSCopying>

@property(readonly, nonatomic) NSData *data;
@property(readonly, nonatomic) _MRGroupTopologyModificationRequestProtobuf *protobuf;
@property(readonly, nonatomic) MRRequestDetails *requestDetails;
@property(readonly, nonatomic) NSArray *outputDeviceUIDs;
@property(readonly, nonatomic) NSArray *outputDevices;
@property(readonly, nonatomic) unsigned long long type;
@property(nonatomic) _Bool fadeAudio;
@property(nonatomic) NSString *password;
@property(nonatomic) _Bool shouldNotPauseIfLastDeviceRemoved;
@property(nonatomic) _Bool suppressErrorDialog;
@property(nonatomic) _Bool muteUntilFinished;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithData:(id)data;
- (id)copyWithOutputDeviceUIDs:(id)uids;
- (id)copyWithType:(unsigned long long)type outputDeviceUIDs:(id)uids;
- (id)initWithProtobuf:(id)protobuf;
- (id)initWithRequestDetails:(id)details type:(unsigned long long)type outputDeviceUIDs:(id)uids;
- (id)initWithRequestDetails:(id)details type:(unsigned long long)type outputDevices:(id)devices;

@end

#endif /* MRGroupTopologyModificationRequest_h */
