//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRGroupSessionXPCConnection_h
#define MRGroupSessionXPCConnection_h
@import Foundation;

#include "MRGroupSessionClientXPCProtocol-Protocol.h"

@protocol OS_dispatch_queue;

@interface MRGroupSessionXPCConnection : NSObject

@property(readonly, nonatomic) id<MRGroupSessionClientXPCProtocol> clientObject;
@property(readonly, nonatomic) NSXPCConnection *connection;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property(readonly, nonatomic) id /* block */ invalidationHandler;

/* instance methods */
- (void)dealloc;
- (id)server;
- (void)sendMessage:(id /* block */)message;
- (void)initializeConnection;
- (id)initWithClientObject:(id)object invalidationHandler:(id /* block */)handler;

@end

#endif /* MRGroupSessionXPCConnection_h */
