//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRGroupSessionRequestManager_h
#define MRGroupSessionRequestManager_h
@import Foundation;
#include <os/lock.h>

#include "MRGroupSessionInfo.h"
#include "MRUserIdentity.h"

@interface MRGroupSessionRequestManager : NSObject

@property(readonly, nonatomic) os_unfair_lock lock;
@property(nonatomic) _Bool hasPopulatedIdentity;
@property(readonly, nonatomic) MRGroupSessionInfo *groupSessionInfo;
@property(retain, nonatomic) MRUserIdentity *localUserIdentity;

/* class methods */
+ (id)sharedManager;

/* instance methods */
- (id)init;
- (void)augmentLocalCommandOptions:(id)options;
- (void)handleGroupSessionNearbyContactDiscoveryDidChange:(id)change;
- (void)registerObservers;
- (void)restoreState;
- (void)updateGroupSessionInfo:(id)info;
- (void)updateLocalIdentity:(id)identity;

@end

#endif /* MRGroupSessionRequestManager_h */
