//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRGroupSessionSubscriberServerXPCProtocol_Protocol_h
#define MRGroupSessionSubscriberServerXPCProtocol_Protocol_h
@import Foundation;

@protocol MRGroupSessionSubscriberServerXPCProtocol

@required

/* required instance methods */
- (void)connectToSession:(id)session reply:(id /* block */)reply;
- (void)session:(id)session approvePendingParticipant:(id)participant reply:(id /* block */)reply;
- (void)session:(id)session denyPendingParticipant:(id)participant reply:(id /* block */)reply;
- (void)session:(id)session removeAllParticipantsWithReply:(id /* block */)reply;
- (void)session:(id)session removeParticipant:(id)participant reply:(id /* block */)reply;

@optional

@end

#endif /* MRGroupSessionSubscriberServerXPCProtocol_Protocol_h */
