//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRGroupSessionHostInfo_h
#define MRGroupSessionHostInfo_h
@import Foundation;

@interface MRGroupSessionHostInfo : NSObject <NSSecureCoding, NSCopying>

@property(readonly, nonatomic) NSString *displayName;
@property(readonly, nonatomic) unsigned char routeType;
@property(readonly, nonatomic) NSString *localizedSessionName;
@property(readonly, nonatomic) _Bool lockScreenAffordanceAllowed;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithRouteType:(unsigned char)type displayName:(id)name;
- (_Bool)isLockScreenAffordanceAllowed;

@end

#endif /* MRGroupSessionHostInfo_h */
