//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRGroupSessionParticipant_Protocol_h
#define MRGroupSessionParticipant_Protocol_h
@import Foundation;

#include "MRUserIdentity.h"

@protocol MRGroupSessionParticipant <NSObject>

@required

@property(readonly, nonatomic) NSString *identifier;
@property(readonly, nonatomic) MRUserIdentity *identity;
@property(readonly, nonatomic) _Bool pending;
@property(readonly, nonatomic) _Bool guest;

/* required instance methods */
- (_Bool)isPending;
- (_Bool)isGuest;

@optional

@end

#endif /* MRGroupSessionParticipant_Protocol_h */
