//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRIDSCompanionMessage_h
#define MRIDSCompanionMessage_h
@import Foundation;

@interface MRIDSCompanionMessage : NSObject

@property(readonly, copy, nonatomic) NSNumber *messageID;
@property(readonly, copy, nonatomic) NSData *data;

/* instance methods */
- (id)initWithID:(id)id data:(id)data;
- (_Bool)replyWithData:(id)data priority:(long long)priority;

@end

#endif /* MRIDSCompanionMessage_h */
