//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRIDSCompanionTransportConnection_h
#define MRIDSCompanionTransportConnection_h
@import Foundation;

#include "MRExternalDeviceTransportConnection.h"
#include "MRIDSCompanionConnection.h"

@interface MRIDSCompanionTransportConnection
    : MRExternalDeviceTransportConnection <NSStreamDelegate> {
    /* instance variables */
    MRIDSCompanionConnection *_connection;
    NSError *_error;
}

@property(readonly, nonatomic) NSString *type;
@property(readonly, nonatomic) NSString *destination;
@property(readonly, nonatomic) NSString *session;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (_Bool)isValid;
- (id)error;
- (id)runLoop;
- (void)closeWithError:(id)error;
- (id)exportEndpoint:(id)endpoint;
- (id)_exportDescriptorForOutputDevice:(id)device
                              endpoint:(id)endpoint
                         remoteControl:(_Bool)control;
- (long long)_idsPriorityFromPriority:(long long)priority;
- (id)exportOutputDevice:(id)device endpoint:(id)endpoint;
- (void)ingestData:(id)data;
- (id)initWithConnection:(id)connection
                    type:(id)type
             destination:(id)destination
                 session:(id)session;
- (unsigned long long)sendTransportData:(id)data options:(id)options;
- (void)setRunLoop:(id)loop;

@end

#endif /* MRIDSCompanionTransportConnection_h */
