//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRIDSCompanionConnection_h
#define MRIDSCompanionConnection_h
@import Foundation;

#include "IDSServiceDelegate-Protocol.h"
#include "MRDeviceInfo.h"

@class IDSDevice, IDSService;
@protocol OS_dispatch_queue;

@interface MRIDSCompanionConnection : NSObject <IDSServiceDelegate> {
    /* instance variables */
    IDSService *_service;
    NSMutableDictionary *_messageHandlers;
    NSMutableDictionary *_destinationMessageHandlers;
    NSMutableDictionary *_responseHandlers;
    unsigned long long _totalOutgoingMessageCount;
    NSObject<OS_dispatch_queue> *_idsQueue;
    NSObject<OS_dispatch_queue> *_calloutQueue;
    int _firstUnlockToken;
}

@property(retain, nonatomic) IDSDevice *device;
@property(readonly, nonatomic) MRDeviceInfo *deviceInfo;
@property(readonly, nonatomic) _Bool isConnected;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)sharedManager;

/* instance methods */
- (id)init;
- (id)name;
- (void)resetConnection;
- (void)service:(id)service
            account:(id)account
    incomingMessage:(id)message
             fromID:(id)id
            context:(id)context;
- (void)service:(id)service connectedDevicesChanged:(id)changed;
- (void)service:(id)service devicesChanged:(id)changed;
- (id)deviceDebugName;
- (_Bool)sendMessage:(id)message
                type:(id)type
         destination:(id)destination
             session:(id)session
             options:(id)options
            priority:(long long)priority
            response:(id /* block */)response;
- (id)_configurationFromDestination:(id)destination session:(id)session;
- (unsigned long long)_generateMessageID;
- (void)_maybeDeviceConnectionStatusChanged;
- (_Bool)_sendMessage:(id)message
                 type:(id)type
          destination:(id)destination
              session:(id)session
              options:(id)options
             priority:(long long)priority
              replyID:(id)id
             response:(id /* block */)response;
- (void)handleDidReceiveResetConnectionRequest;
- (void)initializeService;
- (void)removeMessageHandlerForType:(id)type;
- (void)removeMessageHandlerForType:(id)type destination:(id)destination session:(id)session;
- (_Bool)sendMessage:(id)message
                type:(id)type
         destination:(id)destination
             session:(id)session
             options:(id)options
            priority:(long long)priority;
- (void)setMessageHandler:(id /* block */)handler forType:(id)type;
- (void)setMessageHandler:(id /* block */)handler
                  forType:(id)type
              destination:(id)destination
                  session:(id)session;

@end

#endif /* MRIDSCompanionConnection_h */
