//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRIDSCompanionTransport_h
#define MRIDSCompanionTransport_h
@import Foundation;

#include "MRAVOutputDevice.h"
#include "MRDeviceInfo.h"
#include "MRExternalDeviceTransport.h"
#include "MRIDSCompanionTransportConnection.h"

@interface MRIDSCompanionTransport : MRExternalDeviceTransport {
    /* instance variables */
    MRAVOutputDevice *_outputDevice;
    MRIDSCompanionTransportConnection *_connection;
    _Bool _shouldUseSystemAuthenticationPrompt;
    MRDeviceInfo *_deviceInfo;
    NSError *_error;
}

@property(retain, nonatomic) NSString *sessionUID;

/* instance methods */
- (id)name;
- (id)error;
- (long long)port;
- (id)uid;
- (id)hostname;
- (void)_handleDeviceConnected:(id)connected;
- (void)_handleDeviceDisconnected:(id)disconnected;
- (id)deviceInfo;
- (void)resetWithError:(id)error;
- (id)_generateSessionUID;
- (void)_synchronized_setSessionUID:(id)uid;
- (id)createConnectionWithUserInfo:(id)info;
- (id)initWithOutputDevice:(id)device;
- (void)setShouldUseSystemAuthenticationPrompt:(_Bool)prompt;
- (_Bool)shouldUseSystemAuthenticationPrompt;
- (_Bool)supportsIdleDisconnection;

@end

#endif /* MRIDSCompanionTransport_h */
