//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRImageUtilities_h
#define MRImageUtilities_h
@import Foundation;

@interface MRImageUtilities : NSObject

/* class methods */
+ (CGSize)imageDimensionsForImageData:(id)data error:(id *)error;
+ (id)resizeImageData:(id)data forFittingSize:(CGSize)size error:(id *)error;
+ (CGSize)sizeFromSource:(CGImageSourceRef)source error:(id *)error;
+ (long long)subsampleFactorForMaxPixelSize:(long long)size imageSize:(CGSize)size;

@end

#endif /* MRImageUtilities_h */
