//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRIRNode_h
#define MRIRNode_h
@import Foundation;

#include "MRRouteNodeRepresentable-Protocol.h"

@interface MRIRNode : NSObject <MRRouteNodeRepresentable>

@property(retain, nonatomic) NSString *avOutputDeviceIdentifier;
@property(retain, nonatomic) NSString *rapportIdentifier;
@property(retain, nonatomic) NSString *idsIdentifier;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* instance methods */
- (_Bool)isEqual:(id)equal;

@end

#endif /* MRIRNode_h */
