//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRLegacyController_h
#define MRLegacyController_h
@import Foundation;

#include "MRExternalDevice.h"
#include "MRProtocolClientConnectionDelegate-Protocol.h"

@protocol MRLegacyControllerDelegate
, OS_dispatch_queue;

@interface MRLegacyController : NSObject <MRProtocolClientConnectionDelegate>

@property(copy, nonatomic) NSString *outputDeviceUID;
@property(retain, nonatomic) MRExternalDevice *externalDevice;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property(weak, nonatomic) id<MRLegacyControllerDelegate> delegate;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (void)connect;
- (void)tearDown;
- (void)addOutputDeviceIDs:(id)ids completion:(id /* block */)completion;
- (void)getMasterVolumeCapabilitiesWithCompletion:(id /* block */)completion;
- (void)getMasterVolumeWithCompletion:(id /* block */)completion;
- (void)getOutputDeviceVolume:(id)volume completion:(id /* block */)completion;
- (void)getOutputDeviceVolumeCapabilities:(id)capabilities completion:(id /* block */)completion;
- (void)handleVolumeCapabilitiesDidChangeNotification:(id)notification;
- (id)initWithAVOutputDevice:(id)device;
- (id)initWithExternalDevice:(id)device outputDeviceUID:(id)uid;
- (id)initWithOutputDevice:(id)device;
- (id)initWithOutputDeviceUID:(id)uid;
- (void)modifyTopologyAddingDevices:(id)devices
                    removingDevices:(id)devices
                     settingDevices:(id)devices
                         completion:(id /* block */)completion;
- (void)removeOutputDeviceIDs:(id)ids completion:(id /* block */)completion;
- (void)setMasterVolume:(float)volume completion:(id /* block */)completion;
- (void)setOutputDeviceIDs:(id)ids completion:(id /* block */)completion;
- (void)setVolume:(float)volume forOutputDeviceID:(id)id completion:(id /* block */)completion;
- (void)setupExternalDevice;

@end

#endif /* MRLegacyController_h */
