//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRLogBuffer_h
#define MRLogBuffer_h
@import Foundation;
#include <os/lock.h>

@protocol OS_os_log;

@interface MRLogBuffer : NSObject

@property(retain, nonatomic) NSArray *history;
@property(retain, nonatomic) NSDateFormatter *dateFormatter;
@property(readonly, nonatomic) os_unfair_lock lock;
@property(readonly, nonatomic) long long capacity;
@property(readonly, nonatomic) NSObject<OS_os_log> *category;
@property(readonly, nonatomic) NSString *prefix;

/* class methods */
+ (id)bufferWithCapacity:(long long)capacity category:(id)category loggingPrefix:(id)prefix;

/* instance methods */
- (id)description;
- (void)log:(id)log;
- (void)logError:(id)error;
- (void)logInfo:(id)info;
- (void)logErrorWithInterpolatedString:(id)string;
- (id)initWithCapacity:(long long)capacity category:(id)category prefix:(id)prefix;
- (void)log:(id)log withType:(unsigned char)type capture:(_Bool)capture;
- (void)logDebug:(id)debug;
- (void)logDebugWithoutCapture:(id)capture;
- (void)logErrorWithoutCapture:(id)capture;
- (void)logFault:(id)fault;
- (void)logFaultWithoutCapture:(id)capture;
- (void)logInfoWithoutCapture:(id)capture;
- (void)logInterpolatedString:(id)string;
- (void)logWithoutCapture:(id)capture;

@end

#endif /* MRLogBuffer_h */
