//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRMediaControlsConfiguration_h
#define MRMediaControlsConfiguration_h
@import Foundation;

@interface MRMediaControlsConfiguration : NSObject <NSSecureCoding, NSCopying>

@property(nonatomic) long long style;
@property(nonatomic) long long initiatorStyle;
@property(copy, nonatomic) NSString *routingContextUID;
@property(copy, nonatomic) NSString *presentingAppBundleID;
@property(copy, nonatomic) NSString *nowPlayingAppBundleID;
@property(copy, nonatomic) NSArray *visibleMediaApps;
@property(nonatomic) int presentingAppProcessIdentifier;
@property(nonatomic) _Bool shouldPreventAutorotation;
@property(nonatomic) _Bool allowsNowPlayingApplicationLaunch;
@property(nonatomic) _Bool sortByIsVideoRoute;
@property(nonatomic) _Bool useGenericDevicesIconInHeader;
@property(nonatomic) CGRect sourceRect;
@property(nonatomic) double preferredWidth;
@property(copy, nonatomic) NSString *routeUID;
@property(copy, nonatomic) NSMutableArray *customRows;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (_Bool)isEqual:(id)equal;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;

@end

#endif /* MRMediaControlsConfiguration_h */
