//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRMediaControls_h
#define MRMediaControls_h
@import Foundation;

#include "MRMediaControlsConfiguration.h"
#include "MRMediaControlsProtocol-Protocol.h"

@interface MRMediaControls : NSObject <MRMediaControlsProtocol, NSXPCListenerDelegate> {
    /* instance variables */
    _Bool _shouldObserveRoutingContextUIDChanges;
    unsigned long long _dismissalReason;
    NSString *_tappedCustomRowIdentifier;
}

@property(retain, nonatomic) NSXPCListener *listener;
@property(retain, nonatomic) NSXPCConnection *connection;
@property(readonly, nonatomic) MRMediaControlsConfiguration *configuration;
@property(copy, nonatomic) id /* block */ dismissHandlerWithReason;
@property(copy, nonatomic) id /* block */ dismissHandler;
@property(copy, nonatomic) id /* block */ customRowDidTapHandler;
@property(copy, nonatomic) NSString *routeUID;
@property(nonatomic) double preferredWidth;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (id)init;
- (_Bool)listener:(id)listener shouldAcceptNewConnection:(id)connection;
- (void)_reset;
- (id)initWithConfiguration:(id)configuration;
- (void)dismiss;
- (void)present;
- (void)openConnection;
- (void)startPrewarming;
- (unsigned long long)_MPRouteSharingPolicyToAVRouteSharingPolicy:(unsigned long long)policy;
- (void)_audioSessionRoutingContextDidChangeNotification;
- (id)_dismissalReasonString:(unsigned long long)string;
- (long long)_mediaControlsStyleForRouteSharingPolicy:(unsigned long long)policy;
- (_Bool)_shouldUpdateStyleForCurrentConfigurationStyle:(long long)style;
- (void)_updateAudioSessionRoutingContext;
- (void)addCustomRowWithType:(id)type titleOverride:(id)override identifier:(id)identifier;
- (id)initWithConfiguration:(id)configuration
    shouldObserveRoutingContextUIDChanges:(_Bool)uidchanges;
- (id)initWithRouteSharingPolicy:(unsigned long long)policy routingContextUID:(id)uid;
- (void)setDismissalReason:(unsigned long long)reason;
- (void)setTappedCustomRowIdentifier:(id)identifier;
- (void)stopPrewarming;

@end

#endif /* MRMediaControls_h */
