//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRMuteVolumeMessage_h
#define MRMuteVolumeMessage_h
@import Foundation;

#include "MRProtocolMessage.h"
#include "MRRequestDetails.h"

@interface MRMuteVolumeMessage : MRProtocolMessage

@property(readonly, nonatomic) _Bool muted;
@property(readonly, nonatomic) NSString *outputDeviceUID;
@property(readonly, nonatomic) MRRequestDetails *details;

/* instance methods */
- (unsigned long long)type;
- (_Bool)isMuted;
- (id)initWithMuted:(_Bool)muted outputDeviceUID:(id)uid details:(id)details;

@end

#endif /* MRMuteVolumeMessage_h */
