//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRMutableTextEditingAttributes_h
#define MRMutableTextEditingAttributes_h
@import Foundation;

#include "MRTextEditingAttributes.h"

// @interface MRMutableTextEditingAttributes : MRTextEditingAttributes

// @property (copy, nonatomic) NSString *title;
// @property (copy, nonatomic) NSString *prompt;
// @property (nonatomic) MRTextInputTraits inputTraits;

// @end

#endif /* MRMutableTextEditingAttributes_h */
