//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRMutableApplicationActivity_h
#define MRMutableApplicationActivity_h
@import Foundation;

#include "MRApplicationActivity.h"

@interface MRMutableApplicationActivity : MRApplicationActivity <NSSecureCoding>

@property(copy, nonatomic) NSString *primaryApplicationDisplayID;
@property(copy, nonatomic) NSString *secondaryApplicationDisplayID;
@property(nonatomic) int status;

/* class methods */
+ (_Bool)supportsSecureCoding;

@end

#endif /* MRMutableApplicationActivity_h */
