//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRNotificationClient_h
#define MRNotificationClient_h
@import Foundation;

#include "MRNowPlayingClientState-Protocol.h"

@protocol OS_dispatch_queue;

@interface MRNotificationClient : NSObject <MRNowPlayingClientState> {
    /* instance variables */
    unsigned long long _registeredNowPlayingObservers;
    NSObject<OS_dispatch_queue> *_customNotificationsQueue;
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSOrderedSet *_nowPlayingNotifications;
    NSOrderedSet *_routesChangedNotifications;
    NSOrderedSet *_volumeControlNotifications;
    NSOrderedSet *_externalScreenNotifications;
    NSOrderedSet *_originNotifications;
    NSOrderedSet *_supportedCommandsNotifications;
    NSOrderedSet *_voiceInputNotifications;
    NSOrderedSet *_errorNotifications;
    NSMutableArray *_subscribedWakingPlayerPaths;
}

@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *notificationQueue;
@property(readonly, nonatomic) _Bool registeredForNowPlayingNotifications;
@property(nonatomic) _Bool receivesExternalScreenTypeChangedNotifications;
@property(nonatomic) _Bool receivesSupportedCommandsNotifications;
@property(nonatomic) _Bool receivesRoutesChangedNotifications;
@property(nonatomic) _Bool receivesVolumeControlNotifications;
@property(nonatomic) _Bool receivesOriginChangedNotifications;
@property(nonatomic) _Bool receivesPlaybackErrorNotifications;
@property(nonatomic) _Bool receivesVoiceInputRecordingStateNotifications;

/* class methods */
+ (id)nowPlayingNotifications;

/* instance methods */
- (id)debugDescription;
- (id)init;
- (_Bool)_postNotification:(id)notification
                  userInfo:(id)info
                    object:(id)object
               withHandler:(id /* block */)handler;
- (_Bool)_processAlwaysNeedsNowPlayingNotifications;
- (void)_syncWakingPlayerPathsWithReplyQueue:(id)queue completion:(id /* block */)completion;
- (void)dispatchNotification:(id)notification userInfo:(id)info object:(id)object;
- (_Bool)isRegisteredForNowPlayingNotifications;
- (_Bool)postNotification:(id)notification userInfo:(id)info object:(id)object;
- (void)registerForNowPlayingNotificationsWithQueue:(id)queue;
- (void)registerForNowPlayingNotificationsWithQueue:(id)queue force:(_Bool)force;
- (void)registerForWakingNowPlayingNotificationsForPlayerPath:(id)path
                                                   replyQueue:(id)queue
                                                   completion:(id /* block */)completion;
- (void)restoreNowPlayingClientState;
- (void)unregisterForNowPlayingNotifications;
- (void)unregisterForWakingNowPlayingNotificationsForPlayerPath:(id)path
                                                     replyQueue:(id)queue
                                                     completion:(id /* block */)completion;

@end

#endif /* MRNotificationClient_h */
