//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRNowPlayingClientRequests_h
#define MRNowPlayingClientRequests_h
@import Foundation;

#include "MRClient.h"
#include "MRNowPlayingClientState-Protocol.h"
#include "MRPlayerPath.h"

@interface MRNowPlayingClientRequests : NSObject <MRNowPlayingClientState> {
    /* instance variables */
    NSMutableArray *_playerClients;
    NSMutableArray *_clientPropertiesCompletions;
}

@property(readonly, nonatomic) MRPlayerPath *playerPath;
@property(readonly, nonatomic) MRClient *client;
@property(copy, nonatomic) MRClient *clientProperties;
@property(readonly, nonatomic) NSArray *nowPlayingClients;

/* instance methods */
- (id)debugDescription;
- (id)existingNowPlayingPlayerClientRequestsForPlayerPath:(id)path;
- (void)handleClientPropertiesRequestWithCompletion:(id /* block */)completion;
- (id)initWithPlayerPath:(id)path;
- (id)nowPlayingPlayerClientRequestsForPlayerPath:(id)path;
- (void)removePlayer:(id)player;
- (void)restoreNowPlayingClientState;

@end

#endif /* MRNowPlayingClientRequests_h */
