//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRNowPlayingPlayerPathInvalidationHandler_h
#define MRNowPlayingPlayerPathInvalidationHandler_h
@import Foundation;

#include "MRPlayerPath.h"

@protocol OS_dispatch_queue;

@interface MRNowPlayingPlayerPathInvalidationHandler : NSObject

@property(readonly, nonatomic) MRPlayerPath *playerPath;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property(readonly, nonatomic) id /* block */ callback;
@property(readonly, nonatomic) _Bool invalidateImmediatlyIfInvalid;

/* instance methods */
- (id)description;
- (id)initWithPlayerPath:(id)path
    invalidateImmediatlyIfInvalid:(_Bool)invalid
                            queue:(id)queue
             invalidationCallback:(id /* block */)callback;

@end

#endif /* MRNowPlayingPlayerPathInvalidationHandler_h */
