//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRNowPlayingOriginClientManager_h
#define MRNowPlayingOriginClientManager_h
@import Foundation;

#include "MRNowPlayingClientState-Protocol.h"

@interface MRNowPlayingOriginClientManager : NSObject <MRNowPlayingClientState> {
    /* instance variables */
    NSMutableDictionary *_originClientRequests;
    id /* block */ _createPlayerCallback;
    NSMutableDictionary *_activeSystemEndpointUIDs;
    NSMutableDictionary *_activeSystemEndpointUIDCompletions;
    NSMutableDictionary *_resolveActiveSystemEndpointCompletions;
}

@property(copy, nonatomic) id /* block */ createNewPlayerCallback;
@property(copy, nonatomic) id /* block */ destroyPlayerCallback;
@property(copy, nonatomic) id /* block */ generatePlayerIDCallback;
@property(readonly, nonatomic) NSArray *originClients;
@property(readonly, nonatomic) NSArray *originClientRequets;

/* class methods */
+ (id)sharedManager;

/* instance methods */
- (id)debugDescription;
- (id)init;
- (id)activeSystemEndpointOutputDeviceUIDForType:(long long)type;
- (void)clearActiveSystemEndpoints;
- (id)clientForPlayerPath:(id)path;
- (id)clientRequestsForPlayerPath:(id)path;
- (id)createCustomOriginClientForOrigin:(id)origin;
- (id)existingClientRequestsForPlayerPath:(id)path;
- (id)existingOriginClientRequestsForPlayerPath:(id)path;
- (id)existingPlayerClientRequestsForPlayerPath:(id)path;
- (void)handleActiveSystemEndpointOutputDeviceUIDForType:(long long)type
                                                   queue:(id)queue
                                              completion:(id /* block */)completion;
- (id)localOriginClient;
- (id)originClientForOrigin:(id)origin;
- (id)originClientForPlayerPath:(id)path;
- (id)originClientRequestsForPlayerPath:(id)path;
- (id)playerClientForPlayerPath:(id)path;
- (id)playerClientRequestsForPlayerPath:(id)path;
- (void)removeOrigin:(id)origin;
- (void)removeOriginRequests:(id)requests;
- (void)resolveActiveSystemEndpointWithType:(long long)type
                                    timeout:(double)timeout
                                      queue:(id)queue
                                 completion:(id /* block */)completion;
- (void)restoreNowPlayingClientState;
- (void)updateActiveSystemEndpointOutputDeviceUID:(id)uid forType:(long long)type;

@end

#endif /* MRNowPlayingOriginClientManager_h */
