//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRNowPlayingOriginClientRequests_h
#define MRNowPlayingOriginClientRequests_h
@import Foundation;

#include "MRDeviceInfo.h"
#include "MRNowPlayingClientState-Protocol.h"
#include "MROrigin.h"
#include "MRPlayerPath.h"

@protocol OS_dispatch_queue;

@interface MRNowPlayingOriginClientRequests : NSObject <MRNowPlayingClientState> {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSMutableArray *_nowPlayingClients;
    NSMutableArray *_deviceInfoCompletions;
    NSMutableArray *_volumeCompletions;
    NSMutableArray *_volumeCapabilitiesCompletions;
    NSMutableArray *_lastPlayingDateCompletions;
}

@property(readonly, nonatomic) MROrigin *origin;
@property(readonly, nonatomic) MRPlayerPath *playerPath;
@property(readonly, nonatomic) NSArray *nowPlayingClientRequests;
@property(copy, nonatomic) MRDeviceInfo *deviceInfo;
@property(retain, nonatomic) NSNumber *volumeCapabilities;
@property(retain, nonatomic) NSNumber *volume;
@property(retain, nonatomic) NSDate *lastPlayingDate;

/* instance methods */
- (void)dealloc;
- (id)debugDescription;
- (void)removeClient:(id)client;
- (id)initWithOrigin:(id)origin;
- (id)existingNowPlayingClientRequestsForPlayerPath:(id)path;
- (void)handleDeviceInfoRequestWithCompletion:(id /* block */)completion;
- (void)handleLastPlayingDateRequestWithCompletion:(id /* block */)completion;
- (void)handleVolumeCapabilitiesRequestWithCompletion:(id /* block */)completion;
- (void)handleVolumeRequestWithCompletion:(id /* block */)completion;
- (id)nowPlayingClientRequestsForPlayerPath:(id)path;
- (void)removeAllClients;
- (void)restoreNowPlayingClientState;

@end

#endif /* MRNowPlayingOriginClientRequests_h */
