//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRNowPlayingControllerImpl_Protocol_h
#define MRNowPlayingControllerImpl_Protocol_h
@import Foundation;

#include "MRNowPlayingControllerConfiguration.h"
#include "MRNowPlayingControllerDestination.h"
#include "MRNowPlayingControllerHelper.h"

@protocol MRNowPlayingControllerImpl <NSObject>

@required

@property(retain, nonatomic) MRNowPlayingControllerHelper *helper;
@property(readonly, copy, nonatomic) MRNowPlayingControllerDestination *destination;
@property(readonly, copy, nonatomic) MRNowPlayingControllerConfiguration *configuration;

/* required instance methods */
- (id)initWithConfiguration:(id)configuration;
- (void)beginLoadingUpdates;
- (void)destinationWithCompletion:(id /* block */)completion;

@optional

@end

#endif /* MRNowPlayingControllerImpl_Protocol_h */
