//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRNowPlayingClient_h
#define MRNowPlayingClient_h
@import Foundation;

#include "MRClient.h"
#include "MRNowPlayingClientState-Protocol.h"
#include "MRPlayer.h"
#include "MRPlayerPath.h"

@protocol OS_dispatch_queue;

@interface MRNowPlayingClient : NSObject <MRNowPlayingClientState> {
    /* instance variables */
    MRPlayer *_activePlayer;
    _Bool _isForeground;
    double _canBeNowPlayingTimestamp;
    NSObject<OS_dispatch_queue> *_replayQueue;
    NSMutableArray *_commandQueue;
    NSObject<OS_dispatch_queue> *_avscQueue;
}

@property(nonatomic) _Bool canBeNowPlaying;
@property(nonatomic) _Bool perPlayerCanBeNowPlaying;
@property(retain, nonatomic) MRPlayerPath *playerPath;
@property(retain, nonatomic) MRClient *client;
@property(readonly, nonatomic) MRPlayerPath *activePlayerPath;
@property(readonly, nonatomic) NSArray *playerClients;
@property(nonatomic) _Bool useMediaRemoteActivePlayerHeuristic;

/* instance methods */
- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (void)applicationWillEnterForeground;
- (void)_avSessionMediaServicesResetNotification:(id)notification;
- (void)applicationDidEnterBackground;
- (_Bool)canBeNowPlayingForPlayer:(id)player;
- (void)enqueueCommand:(unsigned int)command
               options:(id)options
            playerPath:(id)path
     commandCompletion:(id /* block */)completion;
- (id)initWithPlayerPath:(id)path;
- (void)mergeClient:(id)client;
- (id)nowPlayingPlayerClientForPlayerPath:(id)path;
- (void)reevaluateActivePlayerWithReason:(id)reason completion:(id /* block */)completion;
- (void)removePlayer:(id)player;
- (void)requestActiveForPlayerPath:(id)path completion:(id /* block */)completion;
- (void)restoreNowPlayingClientState;
- (void)sendQueuedCommandsWithReason:(id)reason;
- (void)setActivePlayerPath:(id)path reason:(id)reason completion:(id /* block */)completion;
- (void)updateActivePlayerPath:(id)path completion:(id /* block */)completion;

@end

#endif /* MRNowPlayingClient_h */
