//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRNowPlayingController_h
#define MRNowPlayingController_h
@import Foundation;

#include "MRDestination.h"
#include "MRNowPlayingControllerConfiguration.h"
#include "MRNowPlayingControllerDelegate-Protocol.h"
#include "MRNowPlayingControllerImpl-Protocol.h"
#include "MRNowPlayingPlayerResponse.h"

@protocol OS_dispatch_queue;

@interface MRNowPlayingController : NSObject

@property(retain, nonatomic) id<MRNowPlayingControllerImpl> impl;
@property(retain, nonatomic) MRNowPlayingPlayerResponse *response;
@property(copy, nonatomic) MRNowPlayingControllerConfiguration *configuration;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workerQueue;
@property(retain, nonatomic) NSError *lastError;
@property(retain, nonatomic) NSDate *allocationDate;
@property(retain, nonatomic) NSDate *beginDate;
@property(retain, nonatomic) NSDate *endDate;
@property(retain, nonatomic) NSDate *lastInitialLoadDate;
@property(retain, nonatomic) NSDate *lastInvalidationDate;
@property(retain, nonatomic) NSDate *lastErrorDate;
@property(retain, nonatomic) NSDate *lastUpdateDate;
@property(weak, nonatomic) id<MRNowPlayingControllerDelegate> delegate;
@property(readonly, copy, nonatomic) MRDestination *destination;

/* class methods */
+ (id)localRouteController;
+ (void)performRequest:(id)request withCompletion:(id /* block */)completion;
+ (id)proactiveEndpointController;
+ (void)sendCommand:(unsigned int)command
      toDestination:(id)destination
            options:(id)options
         appOptions:(unsigned int)options
     withCompletion:(id /* block */)completion;
+ (id)userSelectedEndpointController;

/* instance methods */
- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (id)initWithConfiguration:(id)configuration;
- (id)initWithUID:(id)uid;
- (void)sendCommand:(unsigned int)command options:(id)options completion:(id /* block */)completion;
- (id)_createImplWithConfiguration:(id)configuration;
- (id)_makeHelper;
- (void)_notifyDelegateOfError:(id)error;
- (void)_notifyDelegateOfInvalidation;
- (void)_notifyDelegateOfNewResponse:(id)response;
- (void)_notifyDelegateOfPlaybackQueueChange:(id)change;
- (void)_notifyDelegateOfPlaybackStateChange:(unsigned int)change;
- (void)_notifyDelegateOfPlayerPathChange:(id)change;
- (void)_notifyDelegateOfSupportedCommandsChange:(id)change;
- (void)_notifyDelegateOfUpdate;
- (void)_notifyDelegateOfUpdatedArtwork:(id)artwork;
- (void)_notifyDelegateOfUpdatedClientProperties:(id)properties;
- (void)_notifyDelegateOfUpdatedContentItemsWithContentItems:(id)items;
- (void)_notifyDelegateOfUpdatedDeviceLastPlayingDate:(id)date;
- (void)_notifyDelegateOfUpdatedPlayerLastPlayingDate:(id)date;
- (void)beginLoadingUpdates;
- (void)endLoadingUpdates;
- (id)initWithDestination:(id)destination;
- (void)performRequestWithCompletion:(id /* block */)completion;
- (id)playerPath;
- (void)sendCommand:(unsigned int)command
            options:(id)options
         appOptions:(unsigned int)options
         completion:(id /* block */)completion;

@end

#endif /* MRNowPlayingController_h */
