//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRNowPlayingAudioFormatController_h
#define MRNowPlayingAudioFormatController_h
@import Foundation;

#include "MRClient.h"
#include "MRNowPlayingAudioFormatApplication.h"
#include "MRNowPlayingAudioFormatContentInfo.h"

@class FBSDisplayLayoutMonitor;
@protocol MRNowPlayingAudioFormatControllerDelegate
, OS_dispatch_queue;

@interface MRNowPlayingAudioFormatController : NSObject

@property(retain, nonatomic) NSArray *contentInfos;
@property(retain, nonatomic) MRClient *activeClient;
@property(retain, nonatomic) FBSDisplayLayoutMonitor *layoutMonitor;
@property(retain, nonatomic) NSString *foregroundBundleID;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property(weak, nonatomic) id<MRNowPlayingAudioFormatControllerDelegate> delegate;
@property(readonly, nonatomic) MRNowPlayingAudioFormatApplication *audioFormatApplication;
@property(readonly, nonatomic) MRNowPlayingAudioFormatContentInfo *audioFormatContentInfo;
@property(readonly, copy, nonatomic) NSString *bundleID;
@property(readonly, copy, nonatomic) NSString *displayName;
@property(readonly, nonatomic) _Bool hasNowPlayingApp;
@property(readonly, copy, nonatomic) NSString *audioFormatDescription;
@property(readonly, copy, nonatomic) NSString *bestAvailableAudioFormatDescription;
@property(readonly, nonatomic) _Bool multichannel;
@property(readonly, nonatomic) long long bestAvailableAudioFormat;
@property(readonly, nonatomic) _Bool eligibleForSpatialization;

/* instance methods */
- (void)dealloc;
- (id)description;
- (id)init;
- (id)displayNameForBundleID:(id)id;
- (void)activeClientDidChange:(id)change;
- (void)contentInfoDidChange:(id)change;
- (id)contentInfoForBundleID:(id)id contentInfos:(id)infos;
- (id)faceTimeBundleSet;
- (id)firstContentInfoMatchingSet:(id)set contentInfos:(id)infos;
- (id)firstEligibleContentInfoFor:(id)_for;
- (_Bool)isEligibleForSpatialization;
- (_Bool)isMultichannel;
- (void)updateActiveClient;
- (void)updateAudioFormatContentInfo;
- (void)updateDeprecatedApplication;
- (void)updateDeprecatedContentInfo;
- (void)updateForegroundBundleID;
- (void)updateSelectedContentInfo;

@end

#endif /* MRNowPlayingAudioFormatController_h */
