//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRNowPlayingArtworkImage_h
#define MRNowPlayingArtworkImage_h
@import Foundation;

#include "MRNowPlayingArtwork.h"

@interface MRNowPlayingArtworkImage : MRNowPlayingArtwork

@property(readonly, copy, nonatomic) NSData *imageData;
@property(readonly, copy, nonatomic) NSString *mimeType;

/* instance methods */
- (id)description;
- (_Bool)isEqual:(id)equal;
- (unsigned int)type;
- (id)copyImageData;
- (_Bool)hasArtworkData;
- (id)initWithImageData:(id)data mimeType:(id)type;

@end

#endif /* MRNowPlayingArtworkImage_h */
