//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRNowPlayingPlayerClientRequests_h
#define MRNowPlayingPlayerClientRequests_h
@import Foundation;

#include "MRNowPlayingClientState-Protocol.h"
#include "MRPlaybackQueue.h"
#include "MRPlaybackQueueSubscriptionController.h"
#include "MRPlayer.h"
#include "MRPlayerPath.h"

@protocol OS_dispatch_queue;

@interface MRNowPlayingPlayerClientRequests : NSObject <MRNowPlayingClientState> {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSObject<OS_dispatch_queue> *_responseQueue;
    NSMutableDictionary *_playbackQueueCompletions;
    NSMutableArray *_supportedCommandsCompletions;
    NSMutableArray *_playbackStateCompletions;
    NSMutableArray *_playerPropertiesCompletions;
    NSOperationQueue *_enquedNowPlayingInfoRequests;
    NSOperationQueue *_enquedNowPlayingInfoAssetRequests;
}

@property(readonly, nonatomic) MRPlayerPath *playerPath;
@property(readonly, nonatomic) MRPlaybackQueueSubscriptionController *subscriptionController;
@property(nonatomic) unsigned int playbackState;
@property(copy, nonatomic) MRPlaybackQueue *playbackQueue;
@property(copy, nonatomic) NSArray *supportedCommands;
@property(copy, nonatomic) MRPlayer *playerProperties;

/* instance methods */
- (void)dealloc;
- (id)debugDescription;
- (void)enqueuePlaybackQueueRequest:(id)request completion:(id /* block */)completion;
- (void)handlePlaybackStateRequestWithCompletion:(id /* block */)completion;
- (void)handlePlayerPropertiesRequestWithCompletion:(id /* block */)completion;
- (void)handleSupportedCommandsRequestWithCompletion:(id /* block */)completion;
- (id)initWithPlayerPath:(id)path;
- (void)restoreNowPlayingClientState;
- (void)updateContentItemArtwork:(id)artwork;
- (void)updateContentItems:(id)items;
- (void)updatePlaybackQueueIfUninitialized:(id)uninitialized;
- (void)updatePlaybackStateIfUninitialized:(unsigned int)uninitialized;
- (void)updateSupportedCommandsIfUninitialized:(id)uninitialized;

@end

#endif /* MRNowPlayingPlayerClientRequests_h */
