//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRNotificationServiceClient_h
#define MRNotificationServiceClient_h
@import Foundation;

// #include "MRMediaRemoteServiceClient.h"
@class MRMediaRemoteServiceClient;

@interface MRNotificationServiceClient : NSObject {
    /* instance variables */
    MRMediaRemoteServiceClient *_serviceClient;
}

/* instance methods */
- (void)_handleActiveApplicationDidChangeNotification:(id)notification;
- (void)_handleActiveOriginDidChangeNotification:(id)notification;
- (void)_handleActivePlayerDidChangeNotification:(id)notification;
- (void)_handleActiveSystemEndpointDidChangeNotification:(id)notification;
- (void)_handleApplicationClientStateDidChangeNotification:(id)notification;
- (void)_handleApplicationDidForegroundNotification:(id)notification;
- (void)_handleApplicationDidRegisterNotification:(id)notification;
- (void)_handleApplicationDidUnregisterNotification:(id)notification;
- (void)_handleApplicationDisplayNameDidChangeNotification:(id)notification;
- (void)_handleDeviceInfoDidChangeNotification:(id)notification;
- (void)_handleLocalGroupSessionInfoDidChangeNotification:(id)notification;
- (void)_handleLocalUserIdentityDidChangeNotification:(id)notification;
- (void)_handleOriginDidRegisterNotification:(id)notification;
- (void)_handleOriginDidUnregisterNotification:(id)notification;
- (void)_handlePlayerContentItemArtworkDidChangeNotification:(id)notification;
- (void)_handlePlayerContentItemsDidChangeNotification:(id)notification;
- (void)_handlePlayerDidRegisterNotification:(id)notification;
- (void)_handlePlayerDidUnregisterNotification:(id)notification;
- (void)_handlePlayerIsPlayingDidChangeNotification:(id)notification;
- (void)_handlePlayerNowPlayingInfoDidChangeNotification:(id)notification;
- (void)_handlePlayerPlaybackQueueDidChangeNotification:(id)notification;
- (void)_handlePlayerPlaybackStateDidChangeNotification:(id)notification;
- (void)_handlePlayerStateDidChangeNotification:(id)notification;
- (void)_handlePlayerSupportedCommandsDidChangeNotification:(id)notification;
- (void)_handleVolumeControlCapabilitiesDidChangeNotification:(id)notification;
- (void)_handleVolumeDidChangeNotification:(id)notification;
- (void)
    _maybePostPlaybackQueueNowPlayingItemChangedNotificationFromPlaybackQueueChangedNotification:
        (id)notification;
- (void)_notificationFired:(id)fired
        clientNotification:(id)notification
        originNotification:(id)notification
    nowPlayingNotification:(id)notification;
- (void)_notificationFired:(id)fired
        originNotification:(id)notification
    nowPlayingNotification:(id)notification;
- (void)_notificationFired:(id)fired
     playerPathNotifcation:(id)notifcation
        originNotification:(id)notification
    nowPlayingNotification:(id)notification;
- (void)_postDefaultAppilicationNotifications:(id)notifications;
- (void)_postDefaultOriginNotifications:(id)notifications;
- (void)_postDefaultPlayerNotificationsWithUserInfo:(id)info object:(id)object;
- (void)_processActiveApplicationInvalidationHandlersForNotification:(id)notification;
- (void)_processActiveOriginInvalidationHandlersForNotification:(id)notification;
- (void)_processActivePlayerInvalidationHandlersForNotification:(id)notification;
- (void)_processApplicationInvalidationHandlersForNotification:(id)notification;
- (_Bool)_processNeedsNonPlayerPathBasedNotificationsForBackwardCompatabilitySupport;
- (void)_processOriginInvalidationHandlersForNotification:(id)notification;
- (void)_processPlayerInvalidationHandlersForNotification:(id)notification;
- (_Bool)_shouldPostNotifications;
- (id)initWithServiceClient:(id)client;
- (void)registerCallbacks;

@end

#endif /* MRNotificationServiceClient_h */
