//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRNowPlayingState_h
#define MRNowPlayingState_h
@import Foundation;

#include "MRPlaybackQueue.h"
#include "MRPlaybackQueueRequest.h"
#include "MRPlayerPath.h"

@interface MRNowPlayingState : NSObject <NSCopying>

@property(copy, nonatomic) NSDictionary *nowPlayingInfo;
@property(copy, nonatomic) NSArray *supportedCommands;
@property(copy, nonatomic) MRPlaybackQueue *playbackQueue;
@property(copy, nonatomic) NSString *displayID;
@property(copy, nonatomic) NSString *displayName;
@property(copy, nonatomic) MRPlayerPath *playerPath;
@property(copy, nonatomic) MRPlaybackQueueRequest *request;
@property(nonatomic) _Bool hasPlaybackState;
@property(nonatomic) unsigned int playbackState;
@property(nonatomic) _Bool hasPlaybackStateTimestamp;
@property(nonatomic) double playbackStateTimestamp;
@property(readonly, nonatomic) _Bool containsArtwork;
@property(nonatomic) unsigned long long playbackQueueCapabilities;
@property(readonly, nonatomic) NSData *data;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (id)initWithData:(id)data;
- (id)dictionaryRepresentation;
- (id)copyWithoutArtwork;
- (id)initWithPlayerPath:(id)path;
- (id)initWithProtobuf:(id)protobuf;
- (id)protobufWithEncoding:(long long)encoding;

@end

#endif /* MRNowPlayingState_h */
