//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRNowPlayingAudioFormatApplication_h
#define MRNowPlayingAudioFormatApplication_h
@import Foundation;

@interface MRNowPlayingAudioFormatApplication : NSObject

@property(readonly, copy, nonatomic) NSString *bundleID;
@property(readonly, copy, nonatomic) NSString *displayName;

/* instance methods */
- (id)description;
- (_Bool)isEqual:(id)equal;
- (id)initWithBundleID:(id)id displayName:(id)name;

@end

#endif /* MRNowPlayingAudioFormatApplication_h */
