//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MROptimisticState_h
#define MROptimisticState_h
@import Foundation;

@class MSVTimer;

@interface MROptimisticState : NSObject

@property(readonly, nonatomic) MSVTimer *timer;
@property(readonly, nonatomic) id initialState;
@property(readonly, nonatomic) id expectedState;

/* instance methods */
- (void)dealloc;
- (id)initWithInitialState:(id)state
             expectedState:(id)state
                   timeout:(double)timeout
                     queue:(id)queue
            timeoutHandler:(id /* block */)handler;

@end

#endif /* MROptimisticState_h */
