//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MROrigin_h
#define MROrigin_h
@import Foundation;

#include "MRPlayerPath.h"
#include "_MROriginProtobuf.h"

@interface MROrigin : NSObject <NSSecureCoding, NSCopying>

@property(nonatomic) int identifier;
@property(nonatomic) long long type;
@property(copy, nonatomic) NSString *displayName;
@property(nonatomic) _Bool local;
@property(nonatomic) _Bool locallyHosted;
@property(readonly, nonatomic) _MROriginProtobuf *protobuf;
@property(readonly, nonatomic) MROrigin *skeleton;
@property(readonly, nonatomic) NSData *data;
@property(readonly, nonatomic) _Bool hosted;
@property(readonly, nonatomic) MRPlayerPath *playerPath;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)anyOrigin;
+ (id)localOrigin;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithData:(id)data;
- (_Bool)isLocal;
- (_Bool)isLocallyHosted;
- (id)initWithIdentifier:(int)identifier type:(long long)type displayName:(id)name;
- (id)initWithProtobuf:(id)protobuf;
- (_Bool)isHosted;

@end

#endif /* MROrigin_h */
