//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MROutputContextController_h
#define MROutputContextController_h
@import Foundation;

#include "MRAVOutputContext.h"
#include "MRAVOutputDevice.h"
#include "MROutputContextDataSource.h"

@protocol OS_dispatch_queue;

@interface MROutputContextController : MROutputContextDataSource {
    /* instance variables */
    MRAVOutputContext *_outputContext;
    float _masterVolume;
    unsigned int _masterVolumeControlCapabilities;
    _Bool _groupVolumeMuted;
    _Bool _localVolumeInitialized;
    _Bool _localVolumeControlCapabilitiesInitialized;
    _Bool _localVolumeMutedInitialized;
    NSMutableDictionary *_outputDeviceVolume;
    NSMutableDictionary *_outputDeviceVolumeMuted;
    NSObject<OS_dispatch_queue> *_serialQueue;
}

@property(nonatomic) float localVolume;
@property(nonatomic) unsigned int localVolumeControlCapabilities;
@property(nonatomic) _Bool localVolumeMuted;
@property(readonly, nonatomic) _Bool localDeviceDesignatedGroupLeader;
@property(readonly, nonatomic) _Bool useLocalValues;
@property(readonly, nonatomic) _Bool useOutputContextValues;
@property(readonly, nonatomic) _Bool outputContextEmpty;
@property(retain, nonatomic) MRAVOutputDevice *designatedGroupLeaderWhenContextEmpty;

/* class methods */
+ (id)sharedOutputContextController;

/* instance methods */
- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (id)uniqueIdentifier;
- (float)volume;
- (id)outputDevices;
- (float)volumeForOutputDeviceUID:(id)uid error:(id *)error;
- (void)_handleLocalDeviceVolumeControlCapabilitiesDidChangeNotification:(id)notification;
- (void)_handleLocalDeviceVolumeDidChangeNotification:(id)notification;
- (void)_handleLocalDeviceVolumeMutedDidChangeNotification:(id)notification;
- (void)_handleOutputDeviceAddedNotification:(id)notification;
- (void)_handleOutputDeviceDidChangeNotification:(id)notification;
- (void)_handleOutputDeviceRemovedNotification:(id)notification;
- (void)_handleOutputDeviceVolumeControlCapabilitiesDidChangeNotification:(id)notification;
- (void)_handleOutputDeviceVolumeDidChangeNotification:(id)notification;
- (void)_handleOutputDeviceVolumeMutedDidChangeNotification:(id)notification;
- (void)_handleOutputDevicesReloadedNotification:(id)notification;
- (void)_handlePredictedOutputDeviceDidChangeNotification:(id)notification;
- (id)adjustVolume:(long long)volume outputDeviceUID:(id)uid details:(id)details;
- (id)initWithOutputContext:(id)context;
- (_Bool)isLocalDeviceDesignatedGroupLeader;
- (_Bool)isOutputContextEmpty;
- (id)muteVolume:(_Bool)volume outputDeviceUID:(id)uid details:(id)details;
- (id)setVolume:(float)volume outputDeviceUID:(id)uid details:(id)details;
- (unsigned int)volumeControlCapabilities;
- (unsigned int)volumeControlCapabilitiesForOutputDeviceUID:(id)uid error:(id *)error;
- (_Bool)volumeMutedForOutputDevice:(id)device error:(id *)error;

@end

#endif /* MROutputContextController_h */
