//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRPersistentTimer_h
#define MRPersistentTimer_h
@import Foundation;

@class MSVPersistentTimer, MSVTimer;

@interface MRPersistentTimer : NSObject {
    /* instance variables */
    MSVPersistentTimer *_pTimer;
    MSVTimer *_timer;
}

@property(readonly, nonatomic) _Bool valid;

/* class methods */
+ (_Bool)usePersistentTimer;

/* instance methods */
- (_Bool)isValid;
- (void)invalidate;
- (id)initWithInterval:(double)interval name:(id)name queue:(id)queue block:(id /* block */)block;
- (void)invalidateWithReason:(id)reason;

@end

#endif /* MRPersistentTimer_h */
