//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRPlaybackQueueParticipant_h
#define MRPlaybackQueueParticipant_h
@import Foundation;

#include "MRUserIdentity.h"

@interface MRPlaybackQueueParticipant : NSObject <NSCopying>

@property(readonly, nonatomic) NSData *protobufData;
@property(retain, nonatomic) NSString *identifier;
@property(retain, nonatomic) MRUserIdentity *identity;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;

/* class methods */
+ (id)expectedIdentifierForUserIdentity:(id)identity withRandomData:(id)data;
+ (void)fetchParticipantsWithRequest:(id)request
                       forPlayerPath:(id)path
                               queue:(id)queue
                          completion:(id /* block */)completion;
+ (void)fetchPlaybackQueueParticipantIdentifierForLocalAccountWithDSID:(id)dsid
                                                            completion:(id /* block */)completion;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (id)initWithIdentifier:(id)identifier identity:(id)identity;
- (id)initWithProtobuf:(id)protobuf;
- (id)initWithProtobufData:(id)data;
- (id)protobufWithEncoding:(long long)encoding;

@end

#endif /* MRPlaybackQueueParticipant_h */
