//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRPlaybackSessionMigrateRequestMessage_h
#define MRPlaybackSessionMigrateRequestMessage_h
@import Foundation;

#include "MRPlaybackSession.h"
#include "MRPlaybackSessionMigrateRequest.h"
#include "MRPlayerPath.h"
#include "MRProtocolMessage.h"

@interface MRPlaybackSessionMigrateRequestMessage : MRProtocolMessage

@property(readonly, nonatomic) MRPlaybackSession *playbackSession;
@property(readonly, nonatomic) MRPlaybackSessionMigrateRequest *request;
@property(readonly, nonatomic) MRPlayerPath *playerPath;

/* instance methods */
- (unsigned long long)type;
- (id)initWithPlaybackSession:(id)session request:(id)request forPlayerPath:(id)path;

@end

#endif /* MRPlaybackSessionMigrateRequestMessage_h */
