//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRPlaybackSessionMigrateRequest_h
#define MRPlaybackSessionMigrateRequest_h
@import Foundation;

#include "MRContentItem.h"
#include "MRPlaybackSessionRequest.h"
#include "MRPlayerPath.h"
#include "_MRPlaybackSessionMigrateRequestProtobuf.h"

@interface MRPlaybackSessionMigrateRequest : NSObject <NSCopying> {
    /* instance variables */
    NSError *_migrateError;
    NSError *_fallbackError;
}

@property(nonatomic) unsigned int destinationTypes;
@property(nonatomic) long long playerOptions;
@property(nonatomic) long long endpointOptions;
@property(retain, nonatomic) NSString *requestID;
@property(retain, nonatomic) NSString *initiator;
@property(nonatomic) unsigned long long requestType;
@property(nonatomic) unsigned long long fallbackReason;
@property(nonatomic) double playbackPosition;
@property(nonatomic) double playbackRate;
@property(nonatomic) long long playbackSessionSize;
@property(nonatomic) unsigned int playbackState;
@property(retain, nonatomic) MRContentItem *contentItem;
@property(nonatomic) _Bool allowFadeTransition;
@property(retain, nonatomic) MRPlayerPath *playerPath;
@property(nonatomic) unsigned int originatorType;
@property(readonly, nonatomic) double duration;
@property(readonly, nonatomic) NSString *report;
@property(retain, nonatomic) MRPlayerPath *resolvedPlayerPath;
@property(retain, nonatomic) MRPlaybackSessionRequest *playbackSessionRequest;
@property(readonly, nonatomic) _MRPlaybackSessionMigrateRequestProtobuf *protobuf;
@property(readonly, nonatomic) NSData *protobufData;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (void)finalize;
- (id)init;
- (id)initWithData:(id)data;
- (void)merge:(id)merge;
- (void)addDestinationTypesFromDevices:(id)devices;
- (void)addDestinationType:(unsigned int)type;
- (void)endEvent:(id)event;
- (void)endEvent:(id)event withError:(id)error;
- (id)initWithProtobuf:(id)protobuf;
- (void)setOriginatorTypeFromDevice:(id)device;
- (void)startEvent:(id)event;

@end

#endif /* MRPlaybackSessionMigrateRequest_h */
