//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRPlaybackQueueRequest_h
#define MRPlaybackQueueRequest_h
@import Foundation;

#include "MRPlayerPath.h"
#include "_MRPlaybackQueueRequestProtobuf.h"

@interface MRPlaybackQueueRequest : NSObject <NSCopying, NSSecureCoding>

@property(nonatomic) long long location;
@property(nonatomic) _Bool hasLocation;
@property(nonatomic) long long length;
@property(nonatomic) _Bool hasLength;
@property(nonatomic) _Bool hasIncludeMetadata;
@property(nonatomic) _Bool hasArtworkWidth;
@property(nonatomic) _Bool hasArtworkHeight;
@property(nonatomic) _Bool hasIncludeLyrics;
@property(nonatomic) _Bool hasIncludeSections;
@property(nonatomic) _Bool hasIncludeInfo;
@property(nonatomic) _Bool hasIncludeLanguageOptions;
@property(nonatomic) _Bool hasIncludeAvailableArtworkFormats;
@property(copy, nonatomic) NSArray *contentItemIdentifiers;
@property(nonatomic) _Bool legacyNowPlayingInfoRequest;
@property(nonatomic) _Bool hasLegacyNowPlayingInfoRequest;
@property(nonatomic) unsigned int cachingPolicy;
@property(nonatomic) _Bool hasCachingPolicy;
@property(readonly, nonatomic) _MRPlaybackQueueRequestProtobuf *protobuf;
@property(retain, nonatomic) MRPlayerPath *playerPath;
@property(readonly, nonatomic) _Bool rangeContainsNowPlayingItem;
@property(readonly, nonatomic) _Bool shouldRequestItem;
@property(readonly, nonatomic) _Bool shouldRequestItemNotConsideringMetadata;
@property(readonly, nonatomic) _Bool containsNonDefaultAssets;
@property(readonly, nonatomic) MRPlaybackQueueRequest *skeleton;
@property(readonly, nonatomic) NSData *data;
@property(nonatomic) _Bool includeMetadata;
@property(nonatomic) _Bool includeLyrics;
@property(nonatomic) _Bool includeSections;
@property(nonatomic) _Bool includeInfo;
@property(nonatomic) _Bool includeLanguageOptions;
@property(nonatomic) double artworkWidth;
@property(nonatomic) double artworkHeight;
@property(copy, nonatomic) NSString *requestIdentifier;
@property(copy, nonatomic) NSString *label;
@property(readonly, copy, nonatomic) NSDictionary *dictionaryRepresentation;
@property(readonly, nonatomic) NSRange range;
@property(readonly, nonatomic) _Bool hasRange;
@property(nonatomic) _Bool includeAvailableArtworkFormats;
@property(readonly, nonatomic) _Bool includeArtwork;
@property(readonly, nonatomic) _Bool includeRemoteArtwork;
@property(copy, nonatomic) NSArray *requestedArtworkFormats;
@property(copy, nonatomic) NSArray *requestedRemoteArtworkFormats;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (double)defaultArtworkHeight;
+ (double)defaultArtworkWidth;
+ (id)defaultPlaybackQueueRequest;
+ (id)defaultPlaybackQueueRequestWithRange:(struct _NSRange {
    unsigned long long x0;
    unsigned long long x1;
})range;
+ (id)requestWithCurrentState:(id)state range:(struct _NSRange {
    unsigned long long x0;
    unsigned long long x1;
})range;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (_Bool)isEqual:(id)equal;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithData:(id)data;
- (id)initWithRange:(struct _NSRange {
    unsigned long long x0;
    unsigned long long x1;
})range;
- (void)mergeFrom:(id)from;
- (id)initWithIdentifiers:(id)identifiers;
- (_Bool)match:(id)match;
- (_Bool)exactMatch:(id)match;
- (id)initFromTransactionName:(unsigned long long)name;
- (id)initWithIdentifiers:(id)identifiers range:(struct _NSRange {
    unsigned long long x0;
    unsigned long long x1;
})range;
- (id)initWithProtobuf:(id)protobuf;
- (_Bool)isLegacyNowPlayingInfoRequest;
- (void)performRequestForDestination:(id)destination completion:(id /* block */)completion;
- (id)requestByRemovingArtwork;

@end

#endif /* MRPlaybackQueueRequest_h */
