//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRPlaybackQueue_h
#define MRPlaybackQueue_h
@import Foundation;

#include "MRPlayerPath.h"
#include "_MRPlaybackQueueContextProtobuf.h"

@interface MRPlaybackQueue : NSObject <NSCopying, NSSecureCoding>

@property(copy, nonatomic) _MRPlaybackQueueContextProtobuf *context;
@property(nonatomic) long long location;
@property(nonatomic) _Bool hasLocation;
@property(copy, nonatomic) NSString *requestIdentifier;
@property(copy, nonatomic) NSString *queueIdentifier;
@property(copy, nonatomic) NSArray *contentItems;
@property(copy, nonatomic) NSSet *homeUserIdentifiers;
@property(retain, nonatomic) MRPlayerPath *resolvedPlayerPath;
@property(readonly, copy, nonatomic) NSData *data;
@property(readonly, copy, nonatomic) NSDictionary *dictionaryRepresentation;
@property(readonly, copy, nonatomic) NSArray *contentItemIdentifiers;
@property(readonly, nonatomic) NSRange range;
@property(readonly, copy, nonatomic) NSString *minimalReadableDescription;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (_Bool)isEqual:(id)equal;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithData:(id)data;
- (void)mergeFrom:(id)from;
- (id)contentItemForIdentifier:(id)identifier;
- (id)contentItemWithOffset:(unsigned long long)offset;
- (id)initWithContentItem:(id)item;
- (id)initWithContentItems:(id)items;
- (id)initWithContentItems:(id)items location:(unsigned long long)location;
- (id)initWithProtobuf:(id)protobuf;
- (id)protobufWithEncoding:(long long)encoding;

@end

#endif /* MRPlaybackQueue_h */
