//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRPlaybackSessionMigrateEndMessage_h
#define MRPlaybackSessionMigrateEndMessage_h
@import Foundation;

#include "MRPlaybackSessionRequest.h"
#include "MRPlayerPath.h"
#include "MRProtocolMessage.h"

@interface MRPlaybackSessionMigrateEndMessage : MRProtocolMessage

@property(readonly, nonatomic) MRPlaybackSessionRequest *request;
@property(readonly, nonatomic) NSError *error;
@property(readonly, nonatomic) MRPlayerPath *playerPath;

/* instance methods */
- (unsigned long long)type;
- (id)initWithRequest:(id)request error:(id)error playerPath:(id)path;

@end

#endif /* MRPlaybackSessionMigrateEndMessage_h */
