//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRPlayer_h
#define MRPlayer_h
@import Foundation;

@interface MRPlayer : NSObject <NSCopying>

@property(copy, nonatomic) NSString *identifier;
@property(copy, nonatomic) NSString *displayName;
@property(copy, nonatomic) NSURL *appIcon;
@property(nonatomic) long long audioSessionType;
@property(copy, nonatomic) NSSet *mxSessionIDs;
@property(nonatomic) unsigned int audioSessionID;
@property(readonly, nonatomic) _Bool hasAuxiliaryProperties;
@property(readonly, nonatomic) MRPlayer *skeleton;
@property(readonly, copy, nonatomic) NSData *data;
@property(readonly, nonatomic) _Bool defaultPlayer;

/* class methods */
+ (id)anyPlayer;
+ (id)defaultPlayer;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)initWithData:(id)data;
- (void)mergeFrom:(id)from;
- (id)initWithIdentifier:(id)identifier displayName:(id)name;
- (_Bool)isDefaultPlayer;

@end

#endif /* MRPlayer_h */
