//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRPlaybackSessionResponseMessage_h
#define MRPlaybackSessionResponseMessage_h
@import Foundation;

#include "MRPlaybackSession.h"
#include "MRProtocolMessage.h"

@interface MRPlaybackSessionResponseMessage : MRProtocolMessage

@property(readonly, nonatomic) MRPlaybackSession *playbackSession;

/* instance methods */
- (unsigned long long)type;
- (id)initWithPlaybackSession:(id)session;

@end

#endif /* MRPlaybackSessionResponseMessage_h */
