//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRProtocolMessage_h
#define MRProtocolMessage_h
@import Foundation;

#include "MRProtocolClientConnection.h"
#include "MRProtocolMessageOptions.h"

union _MRHIDPoint {
    struct {
        float x0;
        float x1;
    } x0;
    float x1[2];
};
typedef union _MRHIDPoint MRHIDPoint;

struct _MRHIDTouchEvent {
    MRHIDPoint x0;
    unsigned int x1;
    unsigned long long x2;
    unsigned int x3;
};
typedef struct _MRHIDTouchEvent MRHIDTouchEvent;

struct _MRHIDButtonEvent {
    unsigned int x0;
    unsigned int x1;
    _Bool x2;
};
typedef struct _MRHIDButtonEvent MRHIDButtonEvent;

@class PBCodable;

@interface MRProtocolMessage : NSObject {
    /* instance variables */
    _Bool _replied;
}

@property(retain, nonatomic) PBCodable *underlyingCodableMessage;
@property(copy, nonatomic) NSString *replyIdentifier;
@property(copy, nonatomic) NSString *uniqueIdentifier;
@property(nonatomic) unsigned long long timestamp;
@property(copy, nonatomic) NSError *error;
@property(weak, nonatomic) MRProtocolClientConnection *clientConnection;
@property(nonatomic) _Bool isIncomingReply;
@property(nonatomic) _Bool isOutgoingReply;
@property(readonly, nonatomic) NSData *protobufData;
@property(readonly, nonatomic) unsigned long long encryptionType;
@property(readonly, nonatomic) unsigned long long type;
@property(readonly, nonatomic) NSString *description;
@property(readonly, nonatomic) _Bool shouldLog;
@property(retain, nonatomic) MRProtocolMessageOptions *transportOptions;

/* class methods */
+ (unsigned long long)currentProtocolVersion;
+ (id)protocolMessageWithProtobufData:(id)data error:(id *)error;

/* instance methods */
- (void)dealloc;
- (id)init;
- (_Bool)reply;
- (id)initWithUnderlyingCodableMessage:(id)message error:(id)error;
- (_Bool)replyWithMessage:(id)message;

@end

#endif /* MRProtocolMessage_h */
