//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRProtocolClientConnection_h
#define MRProtocolClientConnection_h
@import Foundation;

#include "MRDeviceInfo.h"
#include "MRExternalDeviceTransportConnection.h"
#include "MRExternalDeviceTransportConnectionDelegate-Protocol.h"
#include "MRProtocolClientConnectionDelegate-Protocol.h"
#include "MRSupportedProtocolMessages.h"
#include "MSVMessageParserDelegate-Protocol.h"

@class MSVMessageParser;
@protocol OS_dispatch_queue;

@interface MRProtocolClientConnection
    : NSObject <MSVMessageParserDelegate, MRExternalDeviceTransportConnectionDelegate> {
    /* instance variables */
    MSVMessageParser *_parser;
    unsigned long long _firstClientNanoseconds;
    unsigned long long _firstDeviceTicks;
    NSMutableDictionary *_pendingReplyQueue;
}

@property(retain, nonatomic) NSError *error;
@property(retain, nonatomic) MRDeviceInfo *deviceInfo;
@property(retain, nonatomic) MRSupportedProtocolMessages *supportedMessages;
@property(retain, nonatomic) NSString *label;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property(readonly, nonatomic) _Bool isValid;
@property(readonly, nonatomic) _Bool disconnected;
@property(readonly, nonatomic) MRExternalDeviceTransportConnection *connection;
@property(weak, nonatomic) id<MRProtocolClientConnectionDelegate> delegate;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (void)sendMessage:(id)message;
- (id)dataForMessage:(id)message;
- (id)decryptData:(id)data error:(id *)error;
- (void)disconnectWithError:(id)error;
- (id)encryptDataForMessage:(id)message;
- (id)initWithConnection:(id)connection queue:(id)queue;
- (void)parser:(id)parser didParseMessage:(id)message;
- (void)sendMessage:(id)message reply:(id /* block */)reply;
- (void)sendMessage:(id)message timeout:(double)timeout reply:(id /* block */)reply;
- (void)transport:(id)transport didReceiveData:(id)data;
- (void)transportDidClose:(id)close error:(id)error;

@end

#endif /* MRProtocolClientConnection_h */
