//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRProtocolMessageLogger_h
#define MRProtocolMessageLogger_h
@import Foundation;

@interface MRProtocolMessageLogger : NSObject

@property(nonatomic) _Bool shouldLog;
@property(nonatomic) _Bool shouldVerboselyLog;

/* class methods */
+ (id)sharedLogger;

/* instance methods */
- (id)init;
- (void)logMessage:(id)message client:(id)client protocolMessage:(id)message;

@end

#endif /* MRProtocolMessageLogger_h */
