//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRRapportTransport_h
#define MRRapportTransport_h
@import Foundation;

#include "MRAVOutputDevice.h"
#include "MRCompanionLinkClient.h"
#include "MRExternalDeviceTransport.h"
#include "MRExternalDeviceTransportConnection.h"

@class RPCompanionLinkDevice;
@protocol OS_dispatch_queue;

@interface MRRapportTransport : MRExternalDeviceTransport {
    /* instance variables */
    NSError *_error;
    NSObject<OS_dispatch_queue> *_workerQueue;
    MRAVOutputDevice *_outputDevice;
    MRAVOutputDevice *_proxyOutputDevice;
    id _resetToken;
    id _disconnectToken;
    MRCompanionLinkClient *_client;
}

@property(retain, nonatomic) NSString *sessionUID;
@property(retain, nonatomic) MRExternalDeviceTransportConnection *connection;
@property(retain, nonatomic) RPCompanionLinkDevice *targetDevice;

/* class methods */
+ (id)userDefaults;
+ (id)_readConnectionRecordsFromDisk;
+ (void)_writeConnectionRecordsToDisk:(id)disk;
+ (void)resetPersistedConnections;

/* instance methods */
- (void)dealloc;
- (id)name;
- (id)error;
- (long long)port;
- (id)uid;
- (void)setError:(id)error;
- (id)hostname;
- (id)deviceInfo;
- (void)resetWithError:(id)error;
- (void)_removeConnectionRecordFromDisk;
- (id)_generateSessionUID;
- (void)_persistConnectionRecordToDisk;
- (id)createConnectionWithUserInfo:(id)info;
- (id)initWithOutputDevice:(id)device;
- (id)initWithOutputDevice:(id)device proxyOutputDevice:(id)device;
- (void)setShouldUseSystemAuthenticationPrompt:(_Bool)prompt;
- (_Bool)shouldUseSystemAuthenticationPrompt;

@end

#endif /* MRRapportTransport_h */
