//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRRapportTransportConfiguration_h
#define MRRapportTransportConfiguration_h
@import Foundation;

@interface MRRapportTransportConfiguration : NSObject <NSSecureCoding>

@property(retain, nonatomic) NSString *deviceUID;
@property(retain, nonatomic) NSString *sessionUID;
@property(retain, nonatomic) NSString *name;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)description;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;

@end

#endif /* MRRapportTransportConfiguration_h */
