//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRRemoveClientMessage_h
#define MRRemoveClientMessage_h
@import Foundation;

#include "MRClient.h"
#include "MRProtocolMessage.h"

@interface MRRemoveClientMessage : MRProtocolMessage

@property(readonly, nonatomic) MRClient *client;

/* instance methods */
- (unsigned long long)type;
- (id)initWithClient:(id)client;

@end

#endif /* MRRemoveClientMessage_h */
