//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRRestrictedCommandClientsManager_h
#define MRRestrictedCommandClientsManager_h
@import Foundation;

@interface MRRestrictedCommandClientsManager : NSObject

@property(retain, nonatomic) NSArray *lastAcceptedTokens;

/* class methods */
+ (id)sharedManager;

/* instance methods */
- (id)_restrictCommandClientsTo:(id)to;
- (void)republishStateIfNeeded;
- (id)restrictCommandClientsTo:(id)to;

@end

#endif /* MRRestrictedCommandClientsManager_h */
