//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRRegisterHIDDeviceResultMessage_h
#define MRRegisterHIDDeviceResultMessage_h
@import Foundation;

#include "MRProtocolMessage.h"

@interface MRRegisterHIDDeviceResultMessage : MRProtocolMessage

@property(readonly, nonatomic) long long errorCode;
@property(readonly, nonatomic) unsigned long long deviceIdentifier;

/* instance methods */
- (unsigned long long)type;
- (id)initWithErrorCode:(long long)code deviceIdentifier:(unsigned long long)identifier;

@end

#endif /* MRRegisterHIDDeviceResultMessage_h */
