//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRSendCommandMessage_h
#define MRSendCommandMessage_h
@import Foundation;

#include "MRPlayerPath.h"
#include "MRProtocolMessage.h"

@interface MRSendCommandMessage : MRProtocolMessage

@property(readonly, nonatomic) unsigned int command;
@property(readonly, nonatomic) NSDictionary *options;
@property(readonly, nonatomic) NSDate *serializationDate;
@property(readonly, nonatomic) MRPlayerPath *playerPath;
@property(readonly, nonatomic) unsigned int appOptions;

/* instance methods */
- (unsigned long long)type;
- (id)initWithCommand:(unsigned int)command options:(id)options playerPath:(id)path;

@end

#endif /* MRSendCommandMessage_h */
