//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRSendCommandResultStatus_h
#define MRSendCommandResultStatus_h
@import Foundation;

#include "MRSendCommandHandlerDialog.h"
#include "_MRSendCommandResultStatusProtobuf.h"

@interface MRSendCommandResultStatus : NSObject <NSCopying>

@property(readonly, copy, nonatomic) _MRSendCommandResultStatusProtobuf *protobuf;
@property(readonly, nonatomic) unsigned int statusCode;
@property(readonly, nonatomic) long long statusType;
@property(readonly, nonatomic) MRSendCommandHandlerDialog *dialog;
@property(readonly, copy, nonatomic) NSError *commandError;
@property(readonly, copy, nonatomic) NSData *customData;
@property(readonly, copy, nonatomic) NSString *customDataType;

/* class methods */
+ (id)statusWithCode:(unsigned int)code customData:(id)data type:(id)type;
+ (id)statusWithCode:(unsigned int)code;
+ (id)statusWithCode:(unsigned int)code dialog:(id)dialog;
+ (id)statusWithCode:(unsigned int)code error:(id)error;
+ (id)successStatus;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (id)initWithProtobuf:(id)protobuf;
- (id)initWithStatusType:(long long)type
              statusCode:(unsigned int)code
                  dialog:(id)dialog
              customData:(id)data
          customDataType:(id)type
                   error:(id)error;

@end

#endif /* MRSendCommandResultStatus_h */
