//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRStaticRouteBannerRequest_h
#define MRStaticRouteBannerRequest_h
@import Foundation;

@interface MRStaticRouteBannerRequest : NSObject <NSSecureCoding>

@property(retain, nonatomic) NSString *routeIdentifier;
@property(retain, nonatomic) NSString *routeName;
@property(retain, nonatomic) NSArray *outputDeviceNames;
@property(retain, nonatomic) NSString *routeSymbolName;
@property(retain, nonatomic) NSString *actionImageName;
@property(retain, nonatomic) NSString *soloModelID;
@property(retain, nonatomic) NSString *soloDeviceEnclosureColor;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)description;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;

@end

#endif /* MRStaticRouteBannerRequest_h */
