//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRSupportedProtocolMessages_h
#define MRSupportedProtocolMessages_h
@import Foundation;

@interface MRSupportedProtocolMessages : NSObject <NSSecureCoding>

@property(readonly, nonatomic) unsigned long long lastSupportedMessageType;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithAllSupportedMessages;
- (id)initWithLastSupportedMessageType:(unsigned long long)type;
- (_Bool)isSupported:(unsigned long long)supported;

@end

#endif /* MRSupportedProtocolMessages_h */
