//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRTelevisionDevice_h
#define MRTelevisionDevice_h
@import Foundation;

#include "MRExternalDevice.h"
#include "RTIInputSystemPayloadDelegate-Protocol.h"

@protocol OS_dispatch_queue;

@interface MRTelevisionDevice : MRExternalDevice <RTIInputSystemPayloadDelegate> {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_serialQueue;
}

@property(copy, nonatomic) id /* block */ gameControllerInputModeCallback;
@property(nonatomic) unsigned int gameControllerInputMode;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *gameControllerInputModeCallbackQueue;
@property(copy, nonatomic) id /* block */ gameControllerPropertiesCallback;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *gameControllerPropertiesCallbackQueue;
@property(copy, nonatomic) id /* block */ recordingStateCallback;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *recordingStateCallbackQueue;
@property(copy, nonatomic) id /* block */ textInputCallback;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *textInputCallbackQueue;
@property(copy, nonatomic) id /* block */ rtiCallback;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *rtiCallbackQueue;
@property(copy, nonatomic) id /* block */ hiliteModeCallback;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *hiliteModeCallbackQueue;
@property(readonly, nonatomic) _Bool hiliteMode;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)performDocumentRequest:(id)request completion:(id /* block */)completion;
- (void)wake;
- (void)handleTextActionPayload:(id)payload;
- (void)clearActiveTextEditingSessionData;
- (id)currentClientUpdatesConfigMessage;
- (void)deleteBackwardInActiveTextEditingSession;
- (void)exitHiliteMode;
- (void)getRTISessionWithReplyQueue:(id)queue completion:(id /* block */)completion;
- (void)getTextEditingSessionWithReplyQueue:(id)queue completion:(id /* block */)completion;
- (void)insertTextIntoActiveTextEditingSessionWithText:(id)text;
- (void)processVoiceInputAudioDataForDeviceID:(unsigned int)id withBuffer:(id)buffer time:(struct {
    double x0;
    double x1;
})time gain:(float)gain;
- (void)registerGameControllerWithProperties:(id)properties
                                       queue:(id)queue
                                  completion:(id /* block */)completion;
- (void)registerTouchDeviceWithDescriptor:(id)descriptor
                               replyQueue:(id)queue
                               completion:(id /* block */)completion;
- (void)registerVoiceInputDeviceWithDescriptor:(id)descriptor
                                    replyQueue:(id)queue
                                    completion:(id /* block */)completion;
- (void)sendGameControllerEvent:(id)event controllerID:(unsigned long long)id;
- (void)sendTouchEvent:(MRHIDTouchEvent)event toVirtualDeviceWithID:(unsigned long long)id;
- (void)setGameControllerInputModeCallback:(id /* block */)callback withQueue:(id)queue;
- (void)setGameControllerPropertiesCallback:(id /* block */)callback withQueue:(id)queue;
- (void)setHiliteModeCallback:(id /* block */)callback withQueue:(id)queue;
- (void)setRTICallback:(id /* block */)rticallback withQueue:(id)queue;
- (void)setTextEditingCallback:(id /* block */)callback withQueue:(id)queue;
- (void)setTextOnActiveTextEditingSessionWithText:(id)text;
- (void)setVoiceRecordingStateCallback:(id /* block */)callback withQueue:(id)queue;
- (void)unregisterGameController:(unsigned long long)controller;

@end

#endif /* MRTelevisionDevice_h */
