//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRTextEditingAttributes_h
#define MRTextEditingAttributes_h
@import Foundation;

@interface MRTextEditingAttributes : NSObject <NSCopying, NSMutableCopying>

@property(readonly, nonatomic) NSString *title;
@property(readonly, nonatomic) NSString *prompt;
@property(readonly, nonatomic) struct _MRTextInputTraits {
    unsigned int x0;
    unsigned int x1;
    unsigned int x2;
    unsigned int x3;
    unsigned int x4;
    struct {
        long long x0;
        long long x1;
    } x5;
    _Bool x6;
    _Bool x7;
    long long x8[10];
    unsigned long long x9;
} inputTraits;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (id)initWithTitle:(id)title prompt:(id)prompt;

@end

#endif /* MRTextEditingAttributes_h */
