//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRTransactionMessage_h
#define MRTransactionMessage_h
@import Foundation;

#include "MRPlayerPath.h"
#include "MRProtocolMessage.h"

@interface MRTransactionMessage : MRProtocolMessage

@property(readonly, nonatomic) unsigned long long name;
@property(readonly, nonatomic) NSArray *packets;
@property(readonly, nonatomic) MRPlayerPath *playerPath;

/* instance methods */
- (unsigned long long)type;
- (id)initWithContentItems:(id)items forPlayerPath:(id)path;
- (id)initWithName:(unsigned long long)name packets:(id)packets playerPath:(id)path;
- (id)initWithPlaybackQueue:(id)queue forPlayerPath:(id)path;

@end

#endif /* MRTransactionMessage_h */
