//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRTransactionPacketizer_h
#define MRTransactionPacketizer_h
@import Foundation;

@interface MRTransactionPacketizer : NSObject {
    /* instance variables */
    NSMutableArray *_outgoingPackets;
    NSMutableDictionary *_incomingPackets;
}

/* instance methods */
- (_Bool)isEmpty;
- (void)packetize:(id)packetize
      packageSize:(unsigned long long)size
       completion:(id /* block */)completion;
- (void)unpacketize:(id)unpacketize completion:(id /* block */)completion;

@end

#endif /* MRTransactionPacketizer_h */
