//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRUserSettings_h
#define MRUserSettings_h
@import Foundation;
#include <os/lock.h>

@interface MRUserSettings : NSObject {
    /* instance variables */
    NSUserDefaults *_userDefaults;
    os_unfair_lock _lock;
}

@property(readonly, nonatomic) _Bool usePeerToPeerExternalDeviceConnections;
@property(readonly, nonatomic) _Bool useNoDelayOptionForExternalDeviceSockets;
@property(readonly, nonatomic) _Bool useDebugAVRouteWithoutVolumeControl;
@property(readonly, nonatomic) _Bool useAPSyncAPI;
@property(readonly, nonatomic) _Bool useClusterDevices;
@property(readonly, nonatomic) _Bool shouldInitializeTelevisionBonjourService;
@property(readonly, nonatomic) _Bool shouldInitializeGenericBonjourService;
@property(readonly, nonatomic) _Bool shouldInitializeRapportService;
@property(readonly, nonatomic) _Bool shouldInitializeIDSService;
@property(readonly, nonatomic) _Bool shouldLogPairingSetupCode;
@property(readonly, nonatomic) _Bool shouldLogArtwork;
@property(readonly, nonatomic) _Bool verboseProtocolMessageLogging;
@property(readonly, nonatomic) _Bool shouldWakeDeviceForRemoteControlCommands;
@property(readonly, nonatomic) _Bool verboseHostedDiscoverySessionLogging;
@property(readonly, nonatomic) _Bool verboseHostedExternalDeviceClientLogging;
@property(readonly, nonatomic) _Bool verboseMRDMediaRemoteClientLogging;
@property(readonly, nonatomic) _Bool verboseConnectionMonitorLogging;
@property(readonly, nonatomic) _Bool verboseNowPlayingControllerLogging;
@property(readonly, nonatomic) _Bool verboseOriginForwarderLogging;
@property(readonly, nonatomic) _Bool verboseNowPlayingStateObserver;
@property(readonly, nonatomic) _Bool verboseRemoteControlDiscoveryLogging;
@property(readonly, nonatomic) _Bool verboseOriginClientLogging;
@property(readonly, nonatomic) _Bool verboseOutputContextLogging;
@property(readonly, nonatomic) _Bool verboseOutputContextDataSourceLogging;
@property(readonly, nonatomic) _Bool verboseDiscoveryLogging;
@property(readonly, nonatomic) _Bool hasExternalDeviceSocketQOSLevelSet;
@property(readonly, nonatomic) long long externalDeviceSocketQOSLevel;
@property(nonatomic) _Bool externalDevicePairingAllowed;
@property(readonly, nonatomic) double externalDeviceTimeoutDuration;
@property(readonly, nonatomic) double externalDeviceNowPlayingInfoCoalesceDuration;
@property(readonly, nonatomic) double externalDeviceNowPlayingInfoArtworkCoalesceDuration;
@property(readonly, nonatomic) double externalDeviceDisconnectWaitDuration;
@property(readonly, nonatomic) double externalDeviceDisconnectSleepDuration;
@property(readonly, nonatomic) double externalDeviceSleepAssertionOnClientConnectDuration;
@property(readonly, nonatomic) double bluetoothDeviceResumeDuration;
@property(readonly, nonatomic) double broadcastCommandWaitDuration;
@property(readonly, nonatomic) double airPlayOutputContextInitTimeoutDuration;
@property(readonly, nonatomic) double wakingPlayerPathAssertionDuration;
@property(readonly, nonatomic) double nowPlayingUIWakingPlayerEventAssertionDuration;
@property(readonly, nonatomic) double externalDeviceArtificalConnectionDelay;
@property(readonly, nonatomic) unsigned long long checkXPCConnectionStatusDefaultInterval;
@property(readonly, nonatomic) double checkXPCConnectionStatusDefaultResponseTimeout;
@property(readonly, nonatomic) double nowPlayingObserverCoalesceInterval;
@property(readonly, nonatomic) _Bool useExternalDeviceSystemPairing;
@property(readonly, nonatomic) long long maxTransactionMemorySize;
@property(readonly, nonatomic) double transactionWaitDurationOnOutOfMemory;
@property(readonly, nonatomic) double transactionWaitDurationOnXpcSend;
@property(readonly, nonatomic) double transactionWaitDurationOnNetworkSend;
@property(readonly, nonatomic) _Bool useSystemAudioContextForAirPlayTransport;
@property(readonly, nonatomic) _Bool useGenericTransportForHostedEndpoints;
@property(retain, nonatomic) NSArray *connectedClientAuditTokens;
@property(retain, nonatomic) NSArray *expectedClientAuditTokens;
@property(readonly, nonatomic) double queuedCommandsTimeoutInterval;
@property(readonly, nonatomic) _Bool computeNowPlayingApplication;
@property(readonly, nonatomic) double nowPlayingApplicationTimeout;
@property(readonly, nonatomic) _Bool takelockScreenAssertion;
@property(readonly, nonatomic) _Bool connectToEndpointWhenBeginsPlayback;
@property(readonly, nonatomic) _Bool notifyDevicesInHomeThatPlaybackStarted;
@property(readonly, nonatomic) _Bool connectToAllEndpointsWhenAnyEndpointBeginsPlayback;
@property(readonly, nonatomic) _Bool connectToUserSelectedEndpoint;
@property(readonly, nonatomic) double discoverEndpointTimeoutInterval;
@property(readonly, nonatomic) _Bool needNowPlayingForegroundState;
@property(readonly, nonatomic) _Bool supportSystemEndpoints;
@property(readonly, nonatomic) _Bool supportElectedPlayer;
@property(readonly, nonatomic) double deviceRecentlyUsedInterval;
@property(readonly, nonatomic) double mediaRecentlyPlayedInterval;
@property(readonly, nonatomic) double endpointRecentlyUserSelectedInterval;
@property(readonly, nonatomic) double remoteDeviceIdleDisconnectionInterval;
@property(readonly, nonatomic) _Bool remoteDeviceIdleDisconnection;
@property(readonly, nonatomic) double launchApplicationTimeoutInterval;
@property(readonly, nonatomic) _Bool supportProximityMigration;
@property(readonly, nonatomic) _Bool supportMigration;
@property(readonly, nonatomic) _Bool supportNewMigrationBehaviorForProximity;
@property(readonly, nonatomic) _Bool supportNewMigrationArchitecture;
@property(readonly, nonatomic) _Bool supportProximityMigrationV2;
@property(readonly, nonatomic) _Bool supportExpanseMigration;
@property(readonly, nonatomic) _Bool supportOutOfProcessMigration;
@property(readonly, nonatomic) _Bool forceFadeForEveryHandoff;
@property(readonly, nonatomic) _Bool supportLastPlayingDevice;
@property(readonly, nonatomic) _Bool supportRapportRemoteControlTransport;
@property(readonly, nonatomic) _Bool supportRapportRemoteControlConnection;
@property(readonly, nonatomic) _Bool sendLastPlayingDeviceToHome;
@property(readonly, nonatomic) _Bool connectToAllEndpointsWhenInProximityToAnyDevice;
@property(readonly, nonatomic) _Bool computeDevicePlaybackSessionID;
@property(readonly, nonatomic) double lastPlayingDeviceThresholdInterval;
@property(readonly, nonatomic) double sendPlaybackSessionUpdateToCompanionCoalesceInterval;
@property(readonly, nonatomic) _Bool forceEnableCECVolume;
@property(readonly, nonatomic) _Bool supportLockscreenPlatterDisplayForPersonalDevice;
@property(readonly, nonatomic) double personalDeviceLockScreenTimeout;
@property(retain, nonatomic) NSDictionary *personalDeviceState;
@property(readonly, nonatomic) unsigned long long maximumNumberOfMediaSuggestions;
@property(readonly, nonatomic) _Bool supportProactiveSuggestion;
@property(readonly, nonatomic) _Bool visuallyIdentifyProactiveSuggestion;
@property(readonly, nonatomic)
    double activeSystemEndpointStartupDelayToAllowAllPreviousClientsTimeToInitializeInterval;
@property(readonly, nonatomic) _Bool supportNanoLinkAgent;
@property(readonly, nonatomic) _Bool discoverCompanionDevices;
@property(readonly, nonatomic) _Bool supportMultiplayerHost;
@property(readonly, nonatomic) _Bool multiplayerAware;
@property(readonly, nonatomic) _Bool canHostMultiplayerStream;
@property(readonly, nonatomic) _Bool removeLocalDevice;
@property(readonly, nonatomic) _Bool showUncommitedDevices;
@property(readonly, nonatomic) _Bool supportNowPlayingPIP;
@property(readonly, nonatomic) _Bool needsMXApplications;
@property(readonly, nonatomic) _Bool supportCoordinatedVolume;
@property(readonly, nonatomic) _Bool supportIDSDiscovery;
@property(readonly, nonatomic) _Bool supportGenericAudioGroup;
@property(readonly, nonatomic) _Bool supportOutputContextSync;
@property(readonly, nonatomic) _Bool supportOutputContextPrewarming;
@property(readonly, nonatomic) _Bool removeLocalDeviceOnMultiplayerReceiverSession;
@property(readonly, nonatomic) unsigned long long maxStreamCapacity;
@property(readonly, nonatomic) _Bool reserveSlotForLocal;
@property(readonly, nonatomic) _Bool forceDeviceInfoDiscovery;
@property(nonatomic) _Bool homepodDemoMode;
@property(readonly, nonatomic) NSArray *jsonClientUIDs;
@property(retain, nonatomic) NSString *lastBootUUID;
@property(readonly, nonatomic) NSArray *routePickerAirPlayAllowList;
@property(readonly, nonatomic) NSArray *routePickerAirPlayDenyList;
@property(readonly, nonatomic) NSArray *destinationResolverReconRetryIntervals;
@property(readonly, nonatomic) int nowPlayingControllerVersion;
@property(readonly, nonatomic) float proximitySortingNearbyRadius;
@property(readonly, nonatomic) _Bool shouldConnectToLocalEndpoint;
@property(readonly, nonatomic) _Bool calculateDiscoveryUpdates;
@property(readonly, nonatomic) _Bool supportRouteRecommendations;
@property(readonly, nonatomic) _Bool enableRouteRecommendations;
@property(readonly, nonatomic) _Bool addDebugBadgeToRecommendedRoutes;
@property(readonly, nonatomic) _Bool showBluePill;
@property(readonly, nonatomic) _Bool enableQueueHandOffForRouteRecommendations;
@property(readonly, nonatomic) NSArray *routeRecommendationEligibleApps;
@property(readonly, nonatomic) double oneTapSuggestionInactiveTimeout;
@property(readonly, nonatomic) double autoRouteInactiveTimeout;
@property(readonly, nonatomic) _Bool useProactivePFSQSender;
@property(readonly, nonatomic) _Bool sendProactivePFSQOnUserSelectedASEChange;
@property(readonly, nonatomic) _Bool sendProactivePFSQOnProactiveASEChange;
@property(readonly, nonatomic) _Bool sendProactivePFSQAfterBoot;
@property(readonly, nonatomic) _Bool sendProactivePFSQOnSiriActivation;
@property(readonly, nonatomic) _Bool internalUI;
@property(readonly, nonatomic) _Bool allowAllClientUIConnections;
@property(readonly, nonatomic) _Bool suppressScreenMirroringErrors;
@property(readonly, nonatomic) _Bool placeholderGroupSessionIdentity;
@property(readonly, nonatomic) _Bool groupSessionHUD;
@property(readonly, nonatomic) _Bool groupSessionNearbyBanner;
@property(readonly, nonatomic) _Bool groupSessionNearbyLockscreen;
@property(readonly, nonatomic) _Bool alwaysShowGroupSessionHUD;
@property(readonly, nonatomic) _Bool startGroupSessionsForAllRoutes;
@property(readonly, nonatomic) _Bool startGroupSessionsForAllRouteSubtypes;
@property(readonly, nonatomic) _Bool startGroupSessionWithBasicIdentity;
@property(readonly, nonatomic) _Bool supportGroupSessionLowPowerMode;
@property(readonly, nonatomic) _Bool supportGroupSessionActiveEndpoint;
@property(readonly, nonatomic) double groupSessionEndAfterPauseInterval;
@property(readonly, nonatomic) double groupSessionLeaderDiscoveryInterval;
@property(readonly, nonatomic) double groupSessionEndpointDiscoveryInterval;
@property(readonly, nonatomic) _Bool supportGroupSessionParticipantNotifications;
@property(readonly, nonatomic) _Bool supportGroupSessionOfframp;
@property(retain, nonatomic) NSNumber *minorUserState;
@property(readonly, nonatomic) _Bool supportGroupSessionAttribution;
@property(readonly, nonatomic) double groupSessionAttributionValidityDuration;
@property(readonly, nonatomic) NSString *recentGroupSessionParticipantsPepper;
@property(readonly, nonatomic) _Bool groupSessionSynchronizePendingParticipants;
@property(readonly, nonatomic) _Bool groupSessionAutoApproveHomeParticipants;
@property(readonly, nonatomic) _Bool supportGroupSessionAutoApproval;
@property(readonly, nonatomic) _Bool groupSessionGenerateSharedSecret;
@property(readonly, nonatomic) _Bool groupSessionListenForProxyJoinRequests;
@property(nonatomic) _Bool groupSessionNearbyContactDiscoveryEnabled;
@property(readonly, nonatomic) NSString *groupSessionNearbyContactDiscoveryDidChangeNotification;
@property(nonatomic) _Bool groupSessionContactAutoApprovalEnabled;
@property(nonatomic) _Bool prefersExpandedLockScreenPlatter;
@property(readonly, nonatomic) double quickControlsInactiveTimeout;
@property(readonly, nonatomic) double lockScreenAPLTarget;
@property(readonly, nonatomic) double lockScreenAPLRatio;
@property(readonly, nonatomic) double flipBookUpdateInterval;
@property(readonly, nonatomic) _Bool donateActiveRoutesToBiome;

/* class methods */
+ (id)currentSettings;

/* instance methods */
- (id)init;
- (void)observeValueForKeyPath:(id)path
                      ofObject:(id)object
                        change:(id)change
                       context:(void *)context;
- (id)defaultSupportedCommandsData;
- (id)defaultSupportedCommandsDataForClient:(id)client;
- (_Bool)isExternalDevicePairingAllowed;
- (_Bool)isMultiplayerAware;
- (id)localLastPlayingDate;
- (unsigned int)localPlaybackState;
- (void)setLocalLastPlayingDate:(id)date;
- (void)setLocalPlaybackState:(unsigned int)state;
- (void)updateDefaultSupportedCommandsData:(id)data forClient:(id)client;

@end

#endif /* MRUserSettings_h */
