//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRUserIdentity_h
#define MRUserIdentity_h
@import Foundation;

#include "_MRUserIdentityProtobuf.h"

@interface MRUserIdentity : NSObject <NSSecureCoding, NSCopying>

@property(readonly, nonatomic) _MRUserIdentityProtobuf *protobuf;
@property(readonly, nonatomic) NSData *protobufData;
@property(readonly, nonatomic) NSString *identifier;
@property(readonly, nonatomic) NSString *displayName;
@property(readonly, nonatomic) long long type;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)basicIdentityWithIdentifier:(id)identifier displayName:(id)name;
+ (void)fetchIdentityForDSID:(id)dsid completion:(id /* block */)completion;
+ (id)resolvableIdentityWithIdentifier:(id)identifier;
+ (id)resolvableIdentityWithIdentifier:(id)identifier displayName:(id)name;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithIdentifier:(id)identifier displayName:(id)name type:(long long)type;
- (id)initWithProtobuf:(id)protobuf;
- (id)initWithProtobufData:(id)data;

@end

#endif /* MRUserIdentity_h */
