//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRV1NowPlayingController_h
#define MRV1NowPlayingController_h
@import Foundation;

#include "MRAVEndpointObserver.h"
#include "MRNowPlayingControllerConfiguration.h"
#include "MRNowPlayingControllerDestination.h"
#include "MRNowPlayingControllerHelper.h"
#include "MRNowPlayingControllerImpl-Protocol.h"
#include "MRNowPlayingPlayerResponse.h"

@class MSVVariableIntervalTimer;
@protocol OS_dispatch_queue;

@interface MRV1NowPlayingController : NSObject <MRNowPlayingControllerImpl>

@property(copy, nonatomic) MRNowPlayingControllerDestination *destination;
@property(copy, nonatomic) MRNowPlayingControllerConfiguration *configuration;
@property(copy, nonatomic) MRNowPlayingPlayerResponse *response;
@property(retain, nonatomic) id playerPathInvalidationObserver;
@property(retain, nonatomic) MRAVEndpointObserver *endpointObserver;
@property(retain, nonatomic) NSString *endpointObserverGroupUID;
@property(retain, nonatomic) NSMutableArray *deferredContentItemsToMerge;
@property(nonatomic) _Bool registeredForNotifications;
@property(nonatomic) _Bool registeredForEndpointChanges;
@property(nonatomic) _Bool registeredForPlayerPathInvalidations;
@property(nonatomic) _Bool updateLoadingEnabled;
@property(nonatomic) _Bool requestingQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property(retain, nonatomic) MSVVariableIntervalTimer *retryTimer;
@property(retain, nonatomic) MRNowPlayingControllerHelper *helper;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (id)initWithConfiguration:(id)configuration;
- (void)_registerNotificationHandlersIfNeeded;
- (void)_unregisterNotificationHandlers;
- (void)_createPlayerPathForEndpoint:(id)endpoint
                              client:(id)client
                              player:(id)player
                          completion:(id /* block */)completion;
- (void)_handleActiveSystemEndpointChangedNotification:(id)notification;
- (void)_handlePlaybackQueueChangedNotification:(id)notification;
- (void)_handlePlaybackQueueContentItemsArtworkChangedNotification:(id)notification;
- (void)_handlePlaybackQueueContentItemsChangedNotification:(id)notification;
- (void)_handlePlaybackStateChangedNotification:(id)notification;
- (void)_handleSupportedCommandsChangedNotification:(id)notification;
- (void)_loadNowPlayingStateForEndpoint:(id)endpoint
                                 client:(id)client
                                 player:(id)player
                             completion:(id /* block */)completion;
- (id)_loadNowPlayingStateForPlayerPath:(id)path error:(id *)error;
- (void)_loadNowPlayingStateForUID:(id)uid
                            client:(id)client
                            player:(id)player
                        completion:(id /* block */)completion;
- (void)_notifyDelegateOfError:(id)error;
- (void)_notifyDelegateOfInvalidation;
- (void)_notifyDelegateOfNewResponse:(id)response;
- (void)_notifyDelegateOfPlaybackQueueChange:(id)change;
- (void)_notifyDelegateOfPlaybackStateChange:(unsigned int)change;
- (void)_notifyDelegateOfPlayerPathChange:(id)change;
- (void)_notifyDelegateOfSupportedCommandsChange:(id)change;
- (void)_notifyDelegateOfUpdatedArtwork:(id)artwork;
- (void)_notifyDelegateOfUpdatedClientProperties:(id)properties;
- (void)_notifyDelegateOfUpdatedContentItemsWithContentItems:(id)items;
- (void)_notifyDelegateOfUpdatedPlayerLastPlayingDate:(id)date;
- (void)_onQueue_clearState;
- (void)_onQueue_retrieveEndpointForUID:(id)uid completion:(id /* block */)completion;
- (void)_registerForEndpointChangesIfNeeded;
- (void)_registerForPlayerPathInvalidationsIfNeeded;
- (void)_reloadForCompleteInvalidation;
- (void)_reloadForPlayerPathInvalidation;
- (void)_requestContentItemArtwork:(id)artwork
                     forPlayerPath:(id)path
                             queue:(id)queue
                        completion:(id /* block */)completion;
- (void)_requestPlaybackQueueForPlayerPath:(id)path
                            includeArtwork:(_Bool)artwork
                                     queue:(id)queue
                                completion:(id /* block */)completion;
- (void)_requestPlayerLastPlayingDateForPlayerPath:(id)path
                                             queue:(id)queue
                                        completion:(id /* block */)completion;
- (void)_requestSupportedCommandsForPlayerPath:(id)path
                                         queue:(id)queue
                                    completion:(id /* block */)completion;
- (void)_resolvePlayerPath:(id)path completion:(id /* block */)completion;
- (void)_unregisterForEndpointChanges;
- (void)_unregisterForPlayerPathInvalidations;
- (void)beginLoadingUpdates;
- (void)destinationWithCompletion:(id /* block */)completion;
- (void)endLoadingUpdates;

@end

#endif /* MRV1NowPlayingController_h */
