//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRV2NowPlayingControllerOperationQueue_h
#define MRV2NowPlayingControllerOperationQueue_h
@import Foundation;

@interface MRV2NowPlayingControllerOperationQueue : NSObject {
    /* instance variables */
    NSOperationQueue *_queue;
    _Bool _invalidated;
}

/* instance methods */
- (void)invalidate;
- (void)addOperationWithBlock:(id /* block */)block;
- (id)initWithQueue:(id)queue;

@end

#endif /* MRV2NowPlayingControllerOperationQueue_h */
