//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRVirtualTouchDeviceDescriptor_h
#define MRVirtualTouchDeviceDescriptor_h
@import Foundation;

union _MRHIDSize {
    struct {
        float x0;
        float x1;
    } x0;
    float x1[2];
};
typedef union _MRHIDSize MRHIDSize;

@interface MRVirtualTouchDeviceDescriptor : NSObject <NSCopying, NSMutableCopying>

@property(readonly, nonatomic) _Bool absolute;
@property(readonly, nonatomic) _Bool integratedDisplay;
@property(readonly, nonatomic) MRHIDSize screenSize;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (_Bool)isAbsolute;
- (_Bool)isIntegratedDisplay;

@end

#endif /* MRVirtualTouchDeviceDescriptor_h */
