//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRVolumeMutedDidChangeMessage_h
#define MRVolumeMutedDidChangeMessage_h
@import Foundation;

#include "MRProtocolMessage.h"

@interface MRVolumeMutedDidChangeMessage : MRProtocolMessage

@property(readonly, nonatomic) _Bool muted;
@property(readonly, nonatomic) NSString *outputDeviceUID;

/* instance methods */
- (unsigned long long)type;
- (_Bool)isMuted;
- (id)initWithMuted:(_Bool)muted outputDeviceUID:(id)uid;

@end

#endif /* MRVolumeMutedDidChangeMessage_h */
