//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRVolumeControlCapabilitiesDidChangeMessage_h
#define MRVolumeControlCapabilitiesDidChangeMessage_h
@import Foundation;

#include "MRProtocolMessage.h"

@interface MRVolumeControlCapabilitiesDidChangeMessage : MRProtocolMessage

@property(readonly, nonatomic) unsigned int capabilities;
@property(readonly, nonatomic) NSString *endpointUID;
@property(readonly, nonatomic) NSString *outputDeviceUID;

/* instance methods */
- (unsigned long long)type;
- (id)initWithCapabilities:(unsigned int)capabilities endpointUID:(id)uid outputDeviceUID:(id)uid;

@end

#endif /* MRVolumeControlCapabilitiesDidChangeMessage_h */
