//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef MRXPCConnection_h
#define MRXPCConnection_h
@import Foundation;

@protocol OS_dispatch_queue
, OS_xpc_object;

@interface MRXPCConnection : NSObject {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSObject<OS_dispatch_queue> *_defaultReplyQueue;
    NSMutableDictionary *_customXpcHandlers;
}

@property(readonly, nonatomic) NSObject<OS_xpc_object> *connection;
@property(copy, nonatomic) id /* block */ messageHandler;
@property(copy, nonatomic) id /* block */ invalidationHandler;
@property(readonly, nonatomic) int pid;
@property(readonly, nonatomic) unsigned int uid;

/* instance methods */
- (void)dealloc;
- (void)addCustomXPCHandler:(id /* block */)xpchandler forKey:(unsigned long long)key;
- (id)initWithConnection:(id)connection queue:(id)queue defaultReplyQueue:(id)queue;
- (void)removeCustomXPCHandler:(unsigned long long)xpchandler;
- (void)sendMessage:(id)message queue:(id)queue reply:(id /* block */)reply;
- (void)sendMessageWithType:(unsigned long long)type queue:(id)queue reply:(id /* block */)reply;
- (id)sendSyncMessage:(id)message error:(id *)error;
- (id)sendSyncMessageWithType:(unsigned long long)type error:(id *)error;

@end

#endif /* MRXPCConnection_h */
