//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef NSCoder_CGRectKeyedCoding_h
#define NSCoder_CGRectKeyedCoding_h
@import Foundation;

@interface NSCoder (CGRectKeyedCoding)

/* instance methods */
- (CGRect)mr_decodeCGRectForKey:(id)key;
- (void)mr_encodeCGRect:(struct CGRect {
    struct CGPoint {
        double x0;
        double x1;
    } x0;
    struct CGSize {
        double x0;
        double x1;
    } x1;
})cgrect forKey:(id)key;

@end

#endif /* NSCoder_CGRectKeyedCoding_h */
