//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef NSNetServiceBrowserDelegate_Protocol_h
#define NSNetServiceBrowserDelegate_Protocol_h
@import Foundation;

// @protocol NSNetServiceBrowserDelegate <NSObject>

// @required

// @optional

// /* optional instance methods */
// - (void)netServiceBrowser:(id)browser didNotSearch:(id)search;
// - (void)netServiceBrowserDidStopSearch:(id)search;
// - (void)netServiceBrowser:(id)browser didFindDomain:(id)domain moreComing:(_Bool)coming;
// - (void)netServiceBrowser:(id)browser didFindService:(id)service moreComing:(_Bool)coming;
// - (void)netServiceBrowser:(id)browser didRemoveDomain:(id)domain moreComing:(_Bool)coming;
// - (void)netServiceBrowser:(id)browser didRemoveService:(id)service moreComing:(_Bool)coming;
// - (void)netServiceBrowserWillSearch:(id)search;

// @end

#endif /* NSNetServiceBrowserDelegate_Protocol_h */
