//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.440.1.0.0
//
#ifndef NSNetServiceDelegate_Protocol_h
#define NSNetServiceDelegate_Protocol_h
@import Foundation;

// @protocol NSNetServiceDelegate <NSObject>

// @required

// @optional

// /* optional instance methods */
// - (void)netService:(id)service didNotPublish:(id)publish;
// - (void)netService:(id)service didNotResolve:(id)resolve;
// - (void)netServiceDidStop:(id)stop;
// - (void)netServiceWillPublish:(id)publish;
// - (void)netServiceWillResolve:(id)resolve;
// - (void)netService:(id)service didAcceptConnectionWithInputStream:(id)stream
// outputStream:(id)stream;
// - (void)netService:(id)service didUpdateTXTRecordData:(id)data;
// - (void)netServiceDidPublish:(id)publish;
// - (void)netServiceDidResolveAddress:(id)address;

// @end

#endif /* NSNetServiceDelegate_Protocol_h */
