//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef _EntitlementCheckResult_h
#define _EntitlementCheckResult_h
@import Foundation;

@interface _EntitlementCheckResult : NSObject

@property(retain, nonatomic) NSError *error;
@property(copy, nonatomic) NSString *group;
@property(copy, nonatomic) NSString *entitlement;
@property(nonatomic) _Bool entitled;

/* instance methods */
- (_Bool)isEntitled;
- (id)initWithEntitlement:(id)entitlement group:(id)group;

@end

#endif /* _EntitlementCheckResult_h */
