//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef _MSVStreamWriterPendingData_h
#define _MSVStreamWriterPendingData_h
@import Foundation;

@interface _MSVStreamWriterPendingData : NSObject

@property(copy, nonatomic) NSData *data;
@property(copy, nonatomic) id /* block */ completionHandler;
@property(nonatomic) long long bytesWritten;

/* instance methods */

@end

#endif /* _MSVStreamWriterPendingData_h */
