//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef _MSVSQLDatabaseAggregateFunctionDescriptor_h
#define _MSVSQLDatabaseAggregateFunctionDescriptor_h
@import Foundation;

#include "_MSVSQLDatabaseFunctionDescriptor.h"

@interface _MSVSQLDatabaseAggregateFunctionDescriptor : _MSVSQLDatabaseFunctionDescriptor {
    /* instance variables */
    id /* block */ _start;
    id /* block */ _add;
    id /* block */ _remove;
    id /* block */ _value;
}

/* instance methods */

@end

#endif /* _MSVSQLDatabaseAggregateFunctionDescriptor_h */
