//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef _MSVSQLDatabaseScalarFunctionDescriptor_h
#define _MSVSQLDatabaseScalarFunctionDescriptor_h
@import Foundation;

#include "_MSVSQLDatabaseFunctionDescriptor.h"

@interface _MSVSQLDatabaseScalarFunctionDescriptor : _MSVSQLDatabaseFunctionDescriptor {
    /* instance variables */
    id /* block */ _block;
}

/* instance methods */

@end

#endif /* _MSVSQLDatabaseScalarFunctionDescriptor_h */
