//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef _MSVSQLConnection_h
#define _MSVSQLConnection_h
@import Foundation;

#include "MSVSQLExecutable-Protocol.h"

@interface _MSVSQLConnection : NSObject <MSVSQLExecutable> {
    /* instance variables */
    struct sqlite3 *_connectionHandle;
    unsigned long long _options;
    NSMutableDictionary *_attachedDatabases;
    NSMutableArray *_scalarFunctions;
    NSMutableArray *_aggregateFunctions;
    _Bool _invalid;
    NSString *_databaseURI;
}

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (_Bool)executeStatement:(id)statement error:(id *)error;
- (id)_cloneWithOptions:(unsigned long long)options error:(id *)error;
- (void)_registerAggregateFunctionDescriptor:(id)descriptor;
- (void)_registerScalarFunctionDescriptor:(id)descriptor;
- (_Bool)executeStatementString:(id)string error:(id *)error;
- (void)registerAggregateFunctionNamed:(id)named
                             arguments:(long long)arguments
                               options:(unsigned long long)options
                                 start:(id /* block */)start
                                   add:(id /* block */)add
                                remove:(id /* block */)remove
                                 value:(id /* block */)value;
- (void)registerFunctionNamed:(id)named
                    arguments:(long long)arguments
                      options:(unsigned long long)options
                        block:(id /* block */)block;
- (id)resultsForStatement:(id)statement;
- (id)statementWithString:(id)string error:(id *)error;
- (void)unregisterFunctionNamed:(id)named arguments:(long long)arguments;

@end

#endif /* _MSVSQLConnection_h */
