//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVArtworkColorAnalysis_h
#define MSVArtworkColorAnalysis_h
@import Foundation;

@interface MSVArtworkColorAnalysis : NSObject <NSCopying, NSMutableCopying, NSSecureCoding>

@property(retain, nonatomic) NSString *backgroundColorHex;
@property(retain, nonatomic) NSString *primaryTextColorHex;
@property(retain, nonatomic) NSString *secondaryTextColorHex;
@property(retain, nonatomic) NSString *tertiaryTextColorHex;
@property(readonly, nonatomic) _Bool backgroundColorLight;
@property(readonly, nonatomic) _Bool primaryTextColorLight;
@property(readonly, nonatomic) _Bool secondaryTextColorLight;
@property(nonatomic) _Bool tertiaryTextColorLight;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)_copyWithClass:(Class)_class;
- (_Bool)isBackgroundColorLight;
- (_Bool)isPrimaryTextColorLight;
- (_Bool)isSecondaryTextColorLight;
- (_Bool)isTertiaryTextColorLight;

@end

#endif /* MSVArtworkColorAnalysis_h */
