//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVArtworkServiceRequest_h
#define MSVArtworkServiceRequest_h
@import Foundation;

@interface MSVArtworkServiceRequest : NSObject <NSSecureCoding> {
    /* instance variables */
    NSMutableDictionary *_sandboxExtensions;
    NSMutableArray *_sandboxHandles;
}

@property(readonly, nonatomic) Class operationClass;
@property(readonly, nonatomic) long long operationPriority;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)init;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (void)addSandboxExtensionIfNeededForURL:(id)url;
- (void)consumeSandboxExtensions;
- (void)releaseSandboxExtensions;

@end

#endif /* MSVArtworkServiceRequest_h */
