//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVArtworkColorAnalyzer_h
#define MSVArtworkColorAnalyzer_h
@import Foundation;
@import CoreImage;

@interface MSVArtworkColorAnalyzer : NSObject

@property(nonatomic) CGImageRef sourceImage;
@property(nonatomic) CGSize preferredImageSize;
@property(nonatomic) long long algorithm;

/* class methods */
+ (long long)algorithmWithMPColorAnalyzerAlgorithm:(long long)algorithm;

/* instance methods */
- (id)analyze;
- (void)analyzeWithCompletionHandler:(id /* block */)handler;
- (id)initWithSourceImage:(struct CGImage *)image algorithm:(long long)algorithm preferredImageSize:(struct CGSize {
    double x0;
    double x1;
})size;

@end

#endif /* MSVArtworkColorAnalyzer_h */
