//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVArtworkServiceColorAnalysisRequest_h
#define MSVArtworkServiceColorAnalysisRequest_h
@import Foundation;

#include "MSVArtworkServiceRequest.h"

@interface MSVArtworkServiceColorAnalysisRequest : MSVArtworkServiceRequest

@property(readonly, nonatomic) NSURL *sourceURL;
@property(readonly, nonatomic) float preferredImageWidth;
@property(readonly, nonatomic) float preferredImageHeight;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)description;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (Class)operationClass;
- (id)initWithSourceURL:(id)url preferredImageSize:(struct CGSize {
    double x0;
    double x1;
})size;

@end

#endif /* MSVArtworkServiceColorAnalysisRequest_h */
