//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVArtworkService_h
#define MSVArtworkService_h
@import Foundation;

@interface MSVArtworkService : NSObject

@property(retain, nonatomic) NSOperationQueue *serviceThrottlingOperationQueue;
@property(retain, nonatomic) NSOperationQueue *serviceColorAnalysisOperationQueue;
@property(retain, nonatomic) NSXPCConnection *serverConnection;

/* class methods */
+ (id)sharedService;

/* instance methods */
- (void)dealloc;
- (id)init;
- (void)sendRequest:(id)request completion:(id /* block */)completion;
- (void)sendRequest:(id)request completionHandler:(id /* block */)handler;

@end

#endif /* MSVArtworkService_h */
