//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVBackgroundTaskProviding_Protocol_h
#define MSVBackgroundTaskProviding_Protocol_h
@import Foundation;

@protocol MSVBackgroundTaskProviding

@required

/* required instance methods */
- (unsigned long long)beginTaskWithExpirationHandler:(id /* block */)handler;
- (unsigned long long)beginTaskWithName:(id)name expirationHandler:(id /* block */)handler;
- (void)endTask:(unsigned long long)task;

@optional

@end

#endif /* MSVBackgroundTaskProviding_Protocol_h */
