//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVBackgroundTaskProvider_h
#define MSVBackgroundTaskProvider_h
@import Foundation;

#include "MSVBackgroundTaskProviding-Protocol.h"

@interface MSVBackgroundTaskProvider : NSObject <MSVBackgroundTaskProviding> {
    /* instance variables */
    struct os_unfair_lock_s {
        unsigned int _os_unfair_lock_opaque;
    } _lock;
}

@property(nonatomic) unsigned long long lastIdentifier;
@property(retain, nonatomic) NSMutableDictionary *timeoutGuards;

/* class methods */
+ (id)sharedProvider;

/* instance methods */
- (id)init;
- (unsigned long long)beginTaskWithExpirationHandler:(id /* block */)handler;
- (_Bool)_locked_acquireAssertion;
- (void)_locked_releaseAssertion;
- (unsigned long long)beginTaskWithName:(id)name expirationHandler:(id /* block */)handler;
- (void)endTask:(unsigned long long)task;

@end

#endif /* MSVBackgroundTaskProvider_h */
