//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVBidirectionalDictionary_h
#define MSVBidirectionalDictionary_h
@import Foundation;

@interface MSVBidirectionalDictionary : NSObject <NSCopying, NSMutableCopying, NSSecureCoding> {
    /* instance variables */
    NSDictionary *_keyToObjectDictionary;
    NSDictionary *_objectToKeyDictionary;
}

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)bidirectionalDictionary;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (id)init;
- (_Bool)isEqual:(id)equal;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (id)allKeys;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithDictionary:(id)dictionary;
- (id)objectForKey:(id)key;
- (id)keyForObject:(id)object;

@end

#endif /* MSVBidirectionalDictionary_h */
