//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVCallback_h
#define MSVCallback_h
@import Foundation;

@protocol OS_dispatch_queue;

@interface MSVCallback : NSObject

@property(copy, nonatomic) id block;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue;

/* class methods */
+ (id)callbackWithQueue:(id)queue block:(id)block;

/* instance methods */
- (void)invoke;
- (void)invokeWithObject:(id)object;

@end

#endif /* MSVCallback_h */
