//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVDefaultDictionary_h
#define MSVDefaultDictionary_h
@import Foundation;

@interface MSVDefaultDictionary : NSMutableDictionary {
    /* instance variables */
    NSMutableDictionary *_storage;
}

@property(copy, nonatomic) id /* block */ defaultValue;

/* class methods */
+ (id)dictionaryWithCapacity:(unsigned long long)capacity defaultValue:(id /* block */)value;
+ (id)dictionaryWithDefaultValue:(id /* block */)value;
+ (id)dictionaryWithDictionary:(id)dictionary defaultValue:(id /* block */)value;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)init;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (unsigned long long)count;
- (id)initWithObjects:(const id *)objects forKeys:(const id *)keys count:(unsigned long long)count;
- (id)keyEnumerator;
- (id)objectForKey:(id)key;
- (id)objectForKeyedSubscript:(id)subscript;
- (void)removeObjectForKey:(id)key;
- (void)setObject:(id)object forKey:(id)key;
- (id)initWithCapacity:(unsigned long long)capacity defaultValue:(id /* block */)value;
- (id)initWithDefaultValue:(id /* block */)value;
- (id)initWithDictionary:(id)dictionary defaultValue:(id /* block */)value;

@end

#endif /* MSVDefaultDictionary_h */
