//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVExtendableBackgroundTaskProvider_h
#define MSVExtendableBackgroundTaskProvider_h
@import Foundation;

#include "MSVBackgroundTaskProviding-Protocol.h"
#include "RBSAssertionObserving-Protocol.h"

@class RBSAssertion;

@interface MSVExtendableBackgroundTaskProvider
    : NSObject <RBSAssertionObserving, MSVBackgroundTaskProviding> {
    /* instance variables */
    NSString *_domain;
    NSString *_name;
    double _invalidationDuration;
    // struct os_unfair_recursive_lock_s { struct os_unfair_lock_s { unsigned int
    // _os_unfair_lock_opaque; } ourl_lock; unsigned int ourl_count; } _lock;
    RBSAssertion *_assertion;
    double _assertionCreatedTime;
    unsigned int _assertionInvalidationNonce;
    NSString *_explanationForExtension;
    unsigned long long _lastIdentifier;
    NSMutableDictionary *_expirationHandlers;
    NSMutableDictionary *_timeoutGuards;
}

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* instance methods */
- (unsigned long long)beginTaskWithExpirationHandler:(id /* block */)handler;
- (void)_assertionInvalidated:(id)invalidated error:(id)error;
- (_Bool)_locked_acquireAssertion:(id)assertion;
- (_Bool)_locked_needsAssertion;
- (void)_locked_releaseAssertion;
- (void)_locked_removeAllTasksWithError:(id)error;
- (long long)_locked_taskCount;
- (void)_taskDidTimeout:(unsigned long long)timeout;
- (unsigned long long)beginTaskWithName:(id)name expirationHandler:(id /* block */)handler;
- (void)endTask:(unsigned long long)task;
- (id)initWithRunningRBSDomain:(id)rbsdomain name:(id)name invalidationDuration:(double)duration;

@end

#endif /* MSVExtendableBackgroundTaskProvider_h */
