//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVLyricsLine_h
#define MSVLyricsLine_h
@import Foundation;

@class MSVLyricsLine;

#include "MSVLyricsSection.h"
#include "MSVLyricsTextElement.h"
#include "MSVLyricsWord.h"

@interface MSVLyricsLine : MSVLyricsTextElement

@property(nonatomic) _Bool instrumentalBreak;
@property(nonatomic) long long lineIndex;
@property(nonatomic) long long originalLineIndex;
@property(weak, nonatomic) MSVLyricsSection *parentSection;
@property(retain, nonatomic) MSVLyricsLine *nextLine;
@property(retain, nonatomic) NSArray *words;
@property(copy, nonatomic) NSString *translationKey;
@property(nonatomic) _Bool hasBackgroundVocal;
@property(retain, nonatomic) MSVLyricsWord *backgroundVocals;
@property(copy, nonatomic) NSAttributedString *primaryVocalText;

/* instance methods */
- (id)description;
- (id)init;
- (id)agent;
- (_Bool)containsTimeOffset:(double)offset withErrorMargin:(double)margin;
- (_Bool)isInstrumentalBreak;

@end

#endif /* MSVLyricsLine_h */
