//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVMarkdownTable_h
#define MSVMarkdownTable_h
@import Foundation;

@interface MSVMarkdownTable : NSObject {
    /* instance variables */
    NSMutableArray *_columnAlignments;
}

@property(readonly, copy, nonatomic) NSArray *columnHeaders;
@property(readonly, copy, nonatomic) NSArray *rows;

/* class methods */
+ (id)escapedString:(id)string;

/* instance methods */
- (id)init;
- (void)addRow:(id)row;
- (void)removeColumnAtIndex:(long long)index;
- (void)removeRowAtIndex:(long long)index;
- (void)insertColumnWithHeader:(id)header atIndex:(long long)index;
- (id)_formatString:(id)string withWidth:(long long)width alignment:(long long)alignment;
- (void)addColumnWithHeader:(id)header;
- (long long)alignmentForColumnAtIndex:(long long)index;
- (id)cellAtColumn:(long long)column row:(long long)row;
- (void)insertRow:(id)row atIndex:(long long)index;
- (id)renderMarkdownWithOptions:(unsigned long long)options;
- (void)setAlignment:(long long)alignment forColumnAtIndex:(long long)index;
- (void)setCell:(id)cell atColumn:(long long)column row:(long long)row;

@end

#endif /* MSVMarkdownTable_h */
