//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVMutableSectionedCollection_h
#define MSVMutableSectionedCollection_h
@import Foundation;

#include "MSVSectionedCollection.h"

@interface MSVMutableSectionedCollection : MSVSectionedCollection

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)removeAllObjects;
- (void)removeItemAtIndexPath:(id)path;
- (void)appendItem:(id)item;
- (void)_initializeAsEmptySectionedCollection;
- (void)appendItems:(id)items;
- (void)appendSection:(id)section;
- (void)insertItem:(id)item atIndexPath:(id)path;
- (void)insertSection:(id)section atIndex:(long long)index;
- (void)moveItemFromIndexPath:(id)path toIndexPath:(id)path;
- (void)moveSectionFromIndex:(long long)index toIndex:(long long)index;
- (void)removeSectionAtIndex:(long long)index;
- (void)replaceItemsUsingBlock:(id /* block */)block;
- (void)replaceObjectAtIndexPath:(id)path withObject:(id)object;
- (void)replaceSectionAtIndex:(long long)index withObject:(id)object;
- (void)replaceSectionsUsingBlock:(id /* block */)block;

@end

#endif /* MSVMutableSectionedCollection_h */
