//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVMutableBidirectionalDictionary_h
#define MSVMutableBidirectionalDictionary_h
@import Foundation;

#include "MSVBidirectionalDictionary.h"

@interface MSVMutableBidirectionalDictionary : MSVBidirectionalDictionary

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithDictionary:(id)dictionary;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)key;
- (void)setObject:(id)object forKey:(id)key;
- (void)removeKeyForObject:(id)object;
- (void)setKey:(id)key forObject:(id)object;

@end

#endif /* MSVMutableBidirectionalDictionary_h */
