//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVMutableArtworkColorAnalysis_h
#define MSVMutableArtworkColorAnalysis_h
@import Foundation;

#include "MSVArtworkColorAnalysis.h"

@interface MSVMutableArtworkColorAnalysis : MSVArtworkColorAnalysis

@property(retain, nonatomic) NSString *backgroundColorHex;
@property(retain, nonatomic) NSString *primaryTextColorHex;
@property(retain, nonatomic) NSString *secondaryTextColorHex;
@property(retain, nonatomic) NSString *tertiaryTextColorHex;
@property(nonatomic) _Bool backgroundColorLight;
@property(nonatomic) _Bool primaryTextColorLight;
@property(nonatomic) _Bool secondaryTextColorLight;
@property(nonatomic) _Bool tertiaryTextColorLight;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)setBackgroundColor:(id)color;
- (void)setPrimaryTextColor:(id)color;
- (void)setSecondaryTextColor:(id)color;
- (void)setTertiaryTextColor:(id)color;

@end

#endif /* MSVMutableArtworkColorAnalysis_h */
