//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVMultiCallback_h
#define MSVMultiCallback_h
@import Foundation;

#include "MSVCallback.h"

@protocol OS_dispatch_queue;

@interface MSVMultiCallback : NSObject {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_serialQueue;
}

@property(readonly, nonatomic) unsigned long long count;
@property(readonly, nonatomic) NSArray *callbacks;
@property(retain, nonatomic) MSVCallback *firstCallback;
@property(retain, nonatomic) MSVCallback *lastCallback;

/* instance methods */
- (id)init;
- (void)invoke;
- (_Bool)removeCallback:(id)callback;
- (void)addCallback:(id)callback;
- (void)invokeWithObject:(id)object;

@end

#endif /* MSVMultiCallback_h */
