//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVOPACKDecoder_h
#define MSVOPACKDecoder_h
@import Foundation;

#include "MSVSegmentedSubDecoder-Protocol.h"

@protocol MSVOPACKDecoderDelegate;

@interface MSVOPACKDecoder : NSCoder <MSVSegmentedSubDecoder>

@property(readonly, nonatomic) NSMutableArray *allowedClassesStack;
@property(readonly, nonatomic) NSArray *objects;
@property(readonly, nonatomic) NSMapTable *objectLookupTable;
@property(readonly, nonatomic) NSMutableArray *wrapperStack;
@property(copy, nonatomic) NSDictionary *userInfo;
@property(weak, nonatomic) id<MSVOPACKDecoderDelegate> delegate;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)decodedObjectOfClass:(Class)_class fromData:(id)data error:(id *)error;
+ (id)decodedObjectOfClass:(Class)_class fromData:(id)data userInfo:(id)info error:(id *)error;
+ (id)decodedObjectOfClasses:(id)classes fromData:(id)data error:(id *)error;
+ (id)decodedObjectOfClasses:(id)classes fromData:(id)data userInfo:(id)info error:(id *)error;

/* instance methods */
- (id)allowedClasses;
- (_Bool)allowsKeyedCoding;
- (const char *)decodeBytesForKey:(id)key returnedLength:(unsigned long long *)length;
- (long long)decodeInt64ForKey:(id)key;
- (id)decodeObjectOfClasses:(id)classes forKey:(id)key;
- (_Bool)decodeBoolForKey:(id)key;
- (double)decodeDoubleForKey:(id)key;
- (int)decodeInt32ForKey:(id)key;
- (int)decodeIntForKey:(id)key;
- (_Bool)containsValueForKey:(id)key;
- (float)decodeFloatForKey:(id)key;
- (id)initForReadingFromData:(id)data error:(id *)error;
- (_Bool)requiresSecureCoding;
- (id)_decodeNumberForKey:(id)key;
- (id)_decodeOPACKObject:(id)opackobject ofClasses:(id)classes;
- (void)_validateClass:(Class)_class fromSupportedClasses:(id)classes;
- (void)beginDecodingPartialTopLevelObjectOfClasses:(id)classes;
- (id)decodeRootObjectOfClass:(Class)_class error:(id *)error;
- (id)decodeRootObjectOfClasses:(id)classes error:(id *)error;
- (void)finishDecodingPartialTopLevelObject;
- (id)initForReadingFromData:(id)data userInfo:(id)info error:(id *)error;
- (void)msv_setUserInfo:(id)info;
- (id)msv_userInfo;

@end

#endif /* MSVOPACKDecoder_h */
