//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVOPACKEncoder_h
#define MSVOPACKEncoder_h
@import Foundation;

@interface MSVOPACKEncoder : NSCoder <NSObject>

@property(nonatomic) _Bool hasFinished;
@property(readonly, nonatomic) NSMutableArray *objects;
@property(readonly, nonatomic) NSMapTable *objectLookupTable;
@property(readonly, nonatomic) NSMutableArray *wrapperStack;
@property(readonly, nonatomic) NSDictionary *userInfo;
@property(readonly, nonatomic) NSData *encodedData;
@property(readonly, nonatomic) _Bool hasTopLevelData;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)encodedDataWithRootObject:(id)object error:(id *)error;
+ (id)encodedDataWithRootObject:(id)object userInfo:(id)info error:(id *)error;

/* instance methods */
- (id)init;
- (_Bool)allowsKeyedCoding;
- (void)encodeBool:(_Bool)_bool forKey:(id)key;
- (void)encodeBytes:(const char *)bytes length:(unsigned long long)length forKey:(id)key;
- (void)encodeInt32:(int)int32 forKey:(id)key;
- (void)encodeInt64:(long long)int64 forKey:(id)key;
- (void)encodeObject:(id)object forKey:(id)key;
- (void)encodeDouble:(double)_double forKey:(id)key;
- (void)encodeInt:(int)_int forKey:(id)key;
- (void)encodeFloat:(float)_float forKey:(id)key;
- (void)encodeRootObject:(id)object;
- (void)finishEncoding;
- (_Bool)requiresSecureCoding;
- (id)_convertNumber:(id)number;
- (id)_convertObject:(id)object;
- (void)_encodeNumber:(id)number forKey:(id)key;
- (void)beginEncodingPartialTopLevelObject:(id)object;
- (id)encodedDataWithError:(id *)error;
- (void)finishEncodingPartialTopLevelObject;
- (_Bool)finishEncodingWithError:(id *)error;
- (void)msv_setUserInfo:(id)info;
- (id)msv_userInfo;

@end

#endif /* MSVOPACKEncoder_h */
