//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVPropertyListEncoder_h
#define MSVPropertyListEncoder_h
@import Foundation;

@interface MSVPropertyListEncoder : NSObject

@property(retain, nonatomic) NSFileHandle *outputFileHandle;
@property(retain, nonatomic) NSMutableData *outputBuffer;
@property(retain, nonatomic) NSDateFormatter *dateFormatter;
@property(retain, nonatomic) NSMutableArray *containerStack;
@property(retain, nonatomic) NSMutableString *tabPrefix;
@property(retain, nonatomic) NSData *tabPrefixData;
@property(readonly, nonatomic) NSData *arrayOpeningTagData;
@property(readonly, nonatomic) NSData *arrayClosingTagData;
@property(readonly, nonatomic) NSData *dictionaryOpeningTagData;
@property(readonly, nonatomic) NSData *dictionaryClosingTagData;
@property(readonly, nonatomic) NSData *keyOpeningTagData;
@property(readonly, nonatomic) NSData *keyClosingTagData;
@property(readonly, nonatomic) NSData *stringOpeningTagData;
@property(readonly, nonatomic) NSData *stringClosingTagData;
@property(readonly, nonatomic) NSData *dataOpeningTagData;
@property(readonly, nonatomic) NSData *dataClosingTagData;
@property(readonly, nonatomic) NSData *boolTrueTagData;
@property(readonly, nonatomic) NSData *boolFalseTagData;

/* instance methods */
- (id)init;
- (void)addObject:(id)object;
- (void)close;
- (void)setObject:(id)object forKey:(id)key;
- (void)endArray;
- (void)endDictionary;
- (void)_addObject:(id)object;
- (void)startDictionary;
- (void)_decrementTabPrefix;
- (void)_encodeData:(id)data;
- (void)_encodeDate:(id)date;
- (void)_encodeNumber:(id)number;
- (void)_encodeString:(id)string;
- (void)_flushOutputBuffer;
- (void)_incrementTabPrefix;
- (void)_startArray;
- (void)_startDictionary;
- (void)_writeData:(id)data;
- (void)_writeDictionaryKey:(id)key;
- (void)_writeString:(id)string;
- (id)initWithOutputFileHandle:(id)handle;
- (void)startArray;
- (void)startArrayForKey:(id)key;
- (void)startDictionaryForKey:(id)key;

@end

#endif /* MSVPropertyListEncoder_h */
