//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVRandomDistribution_h
#define MSVRandomDistribution_h
@import Foundation;

#include "MSVRandom-Protocol.h"

@interface MSVRandomDistribution : NSObject <MSVRandom, NSSecureCoding> {
    /* instance variables */
    id<MSVRandom> _source;
}

@property(readonly, nonatomic) long long lowestValue;
@property(readonly, nonatomic) long long highestValue;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)init;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithRandomSource:(id)source lowestValue:(long long)value highestValue:(long long)value;
- (unsigned long long)nextIntWithUpperBound:(unsigned long long)bound;

@end

#endif /* MSVRandomDistribution_h */
