//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVSystemDialog_h
#define MSVSystemDialog_h
@import Foundation;

#include "MSVSystemDialogOptions.h"

@interface MSVSystemDialog : NSObject {
    /* instance variables */
    struct __CFUserNotification *_preparedUserNotification;
}

@property(nonatomic) struct __CFUserNotification *presentedUserNotification;
@property(nonatomic) struct __CFRunLoopSource *activeRunLoopSource;
@property(copy, nonatomic) id /* block */ pendingCompletion;
@property(readonly, nonatomic) MSVSystemDialogOptions *options;
@property(readonly, nonatomic) NSArray *textFields;

/* class methods */
+ (id)systemDialogWithOptions:(id)options;

/* instance methods */
- (void)dealloc;
- (id)initWithOptions:(id)options;
- (void)dismiss;
- (void)presentWithCompletion:(id /* block */)completion;
- (void)addTextField:(id)field;
- (void)clearTextFields;
- (void)addTextFieldWithTitle:(id)title secure:(_Bool)secure;
- (id)initWithCFUserNotification:(struct __CFUserNotification *)notification;

@end

#endif /* MSVSystemDialog_h */
