//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVSQLDatabaseTransaction_h
#define MSVSQLDatabaseTransaction_h
@import Foundation;

#include "MSVSQLExecutable-Protocol.h"
#include "_MSVSQLAssertion-Protocol.h"
#include "_MSVSQLConnection.h"

@interface MSVSQLDatabaseTransaction : NSObject <MSVSQLExecutable> {
    /* instance variables */
    _Bool _invalid;
    _MSVSQLConnection *_connection;
    id<_MSVSQLAssertion> _assertion;
}

@property(readonly, copy, nonatomic) NSString *name;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (_Bool)commit;
- (_Bool)rollback;
- (_Bool)executeStatement:(id)statement error:(id *)error;
- (id)createSavepoint;
- (_Bool)_releaseSavepoint:(id)savepoint;
- (_Bool)executeStatementString:(id)string error:(id *)error;
- (id)resultsForStatement:(id)statement;
- (_Bool)rollbackToSavepoint:(id)savepoint;
- (id)statementWithString:(id)string error:(id *)error;

@end

#endif /* MSVSQLDatabaseTransaction_h */
