//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVSystemDialogResponse_h
#define MSVSystemDialogResponse_h
@import Foundation;

@interface MSVSystemDialogResponse : NSObject

@property(readonly, nonatomic) long long buttonIdentifier;
@property(readonly, nonatomic) NSArray *textFieldValues;

/* instance methods */
- (id)description;
- (id)initWithIdentifier:(long long)identifier textFieldValues:(id)values;

@end

#endif /* MSVSystemDialogResponse_h */
