//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVSegmentedEncoder_h
#define MSVSegmentedEncoder_h
@import Foundation;

#include "MSVSegmentedCoding-Protocol.h"
#include "MSVSegmentedCodingPackage.h"

@interface MSVSegmentedEncoder : NSCoder

@property(nonatomic) _Bool hasFinished;
@property(retain, nonatomic) MSVSegmentedCodingPackage *package;
@property(retain, nonatomic) id<MSVSegmentedCoding> rootObject;
@property(retain, nonatomic) NSMutableDictionary *subcoders;
@property(copy, nonatomic) NSDictionary *userInfo;

/* instance methods */
- (void)encodeBool:(_Bool)_bool forKey:(id)key;
- (void)encodeBytes:(const char *)bytes length:(unsigned long long)length forKey:(id)key;
- (void)encodeInt32:(int)int32 forKey:(id)key;
- (void)encodeInt64:(long long)int64 forKey:(id)key;
- (void)encodeObject:(id)object forKey:(id)key;
- (void)encodeDouble:(double)_double forKey:(id)key;
- (void)encodeInt:(int)_int forKey:(id)key;
- (void)encodeFloat:(float)_float forKey:(id)key;
- (void)encodeRootObject:(id)object;
- (void)finishEncoding;
- (id)initWithCodingPackage:(id)package userInfo:(id)info;
- (id)_coderForKey:(id)key;
- (id)initWithCodingPackage:(id)package;
- (void)msv_setUserInfo:(id)info;
- (id)msv_userInfo;

@end

#endif /* MSVSegmentedEncoder_h */
