//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVSegmentedCodingPackage_h
#define MSVSegmentedCodingPackage_h
@import Foundation;

@interface MSVSegmentedCodingPackage : NSObject {
    /* instance variables */
    _Bool _needsInfoDictionaryUpdate;
}

@property(copy, nonatomic) NSURL *packageURL;
@property(retain, nonatomic) NSMutableDictionary *segmentEncoderMap;
@property(retain, nonatomic) NSMutableDictionary *infoDictionary;
@property(retain, nonatomic) Class archivedClass;
@property(readonly, nonatomic) NSDictionary *allVersions;

/* class methods */
+ (id)packageTypeIdentifier;

/* instance methods */
- (id)initWithURL:(id)url;
- (void)reset;
- (_Bool)saveWithError:(id *)error;
- (_Bool)deleteWithError:(id *)error;
- (_Bool)writeWithError:(id *)error;
- (id)coderTypeForSegment:(id)segment;
- (id)decodersWithError:(id *)error;
- (id)encoderForSegment:(id)segment version:(long long)version;
- (void)setNeedsInfoDictionaryUpdate;

@end

#endif /* MSVSegmentedCodingPackage_h */
