//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVSystemDialogTextField_h
#define MSVSystemDialogTextField_h
@import Foundation;

@interface MSVSystemDialogTextField : NSObject

@property(copy, nonatomic) NSString *title;
@property(nonatomic) _Bool secure;
@property(nonatomic) long long keyboardType;

/* class methods */
+ (id)textFieldWithTitle:(id)title;
+ (id)textFieldWithTitle:(id)title secure:(_Bool)secure;

/* instance methods */
- (id)initWithTitle:(id)title;
- (_Bool)isSecure;

@end

#endif /* MSVSystemDialogTextField_h */
