//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVSQLExecutable_Protocol_h
#define MSVSQLExecutable_Protocol_h
@import Foundation;

@protocol MSVSQLExecutable <NSObject>

@required

/* required instance methods */
- (_Bool)executeStatement:(id)statement error:(id *)error;
- (_Bool)executeStatementString:(id)string error:(id *)error;
- (id)resultsForStatement:(id)statement;
- (id)statementWithString:(id)string error:(id *)error;

@optional

@end

#endif /* MSVSQLExecutable_Protocol_h */
