//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVSegmentedDecoder_h
#define MSVSegmentedDecoder_h
@import Foundation;

#include "MSVSegmentedCodingPackage.h"

@interface MSVSegmentedDecoder : NSCoder

@property(retain, nonatomic) MSVSegmentedCodingPackage *package;
@property(retain, nonatomic) Class rootClass;
@property(retain, nonatomic) NSArray *subcoders;
@property(copy, nonatomic) NSDictionary *userInfo;

/* class methods */
+ (id)decodedObjectOfClass:(Class)_class fromPackage:(id)package error:(id *)error;
+ (id)decodedObjectOfClass:(Class)_class
               fromPackage:(id)package
                  userInfo:(id)info
                     error:(id *)error;
+ (id)decodedObjectOfClasses:(id)classes fromPackage:(id)package error:(id *)error;
+ (id)decodedObjectOfClasses:(id)classes
                 fromPackage:(id)package
                    userInfo:(id)info
                       error:(id *)error;

/* instance methods */
- (const char *)decodeBytesForKey:(id)key returnedLength:(unsigned long long *)length;
- (long long)decodeInt64ForKey:(id)key;
- (id)decodeObjectOfClasses:(id)classes forKey:(id)key;
- (_Bool)decodeBoolForKey:(id)key;
- (double)decodeDoubleForKey:(id)key;
- (int)decodeInt32ForKey:(id)key;
- (int)decodeIntForKey:(id)key;
- (_Bool)containsValueForKey:(id)key;
- (float)decodeFloatForKey:(id)key;
- (id)_coderForKey:(id)key;
- (id)decodeRootObjectOfClass:(Class)_class error:(id *)error;
- (id)decodeRootObjectOfClasses:(id)classes error:(id *)error;
- (id)initWithCodingPackage:(id)package error:(id *)error;
- (id)initWithCodingPackage:(id)package userInfo:(id)info error:(id *)error;
- (void)msv_setUserInfo:(id)info;
- (id)msv_userInfo;

@end

#endif /* MSVSegmentedDecoder_h */
