//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVSegmentedCoding_Protocol_h
#define MSVSegmentedCoding_Protocol_h
@import Foundation;

@protocol MSVSegmentedCoding <NSSecureCoding, NSObject>

@required

/* required instance methods */
- (void)didRestoreVersion:(long long)version forSegment:(id)segment;
- (id)segmentForCodingKey:(id)key;
- (long long)versionForSegment:(id)segment;

@optional

@end

#endif /* MSVSegmentedCoding_Protocol_h */
