//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVSystemDialogManager_h
#define MSVSystemDialogManager_h
@import Foundation;

@protocol OS_dispatch_queue;

@interface MSVSystemDialogManager : NSObject {
    /* instance variables */
    struct __CFDictionary *_registeredSystemDialogs;
    NSObject<OS_dispatch_queue> *_serialQueue;
}

/* class methods */
+ (id)sharedManager;

/* instance methods */
- (void)dealloc;
- (id)init;
- (void)registerSystemDialog:(id)dialog
         forUserNotification:(struct __CFUserNotification *)notification;
- (id)systemDialogForUserNotification:(struct __CFUserNotification *)notification;
- (void)unregisterSystemDialogWithUserNotification:(struct __CFUserNotification *)notification;

@end

#endif /* MSVSystemDialogManager_h */
