//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVTaskAssertion_h
#define MSVTaskAssertion_h
@import Foundation;

@class BKSProcessAssertion;
@protocol OS_dispatch_source;

@interface MSVTaskAssertion : NSObject {
    /* instance variables */
    NSString *_uuid;
    NSString *_subsystem;
    int _pid;
    NSObject<OS_dispatch_source> *_invalidationTimer;
    _Bool _acquired;
    BKSProcessAssertion *_processAssertion;
}

@property(readonly, nonatomic) NSString *bundleID;
@property(readonly, nonatomic) _Bool valid;
@property(readonly, nonatomic) NSString *name;
@property(copy, nonatomic) id /* block */ invalidationHandler;

/* instance methods */
- (void)dealloc;
- (id)description;
- (id)init;
- (_Bool)isValid;
- (void)invalidate;
- (_Bool)acquire;
- (_Bool)isAcquired;
- (unsigned int)_BSKFlagsForMSVFlags:(unsigned long long)msvflags;
- (unsigned int)_BSKReasonForMSVReason:(unsigned long long)msvreason;
- (void)_cancelInvalidationTimerWithCompletion:(id /* block */)completion;
- (id)_initWithName:(id)name
           bundleID:(id)id
                pid:(int)pid
          subsystem:(id)subsystem
             reason:(unsigned long long)reason
              flags:(unsigned long long)flags;
- (id)initWithName:(id)name
          bundleID:(id)id
         subsystem:(id)subsystem
            reason:(unsigned long long)reason
             flags:(unsigned long long)flags;
- (id)initWithName:(id)name
               pid:(int)pid
          bundleID:(id)id
         subsystem:(id)subsystem
            reason:(unsigned long long)reason
             flags:(unsigned long long)flags;
- (id)initWithName:(id)name
               pid:(int)pid
         subsystem:(id)subsystem
            reason:(unsigned long long)reason
             flags:(unsigned long long)flags;
- (void)invalidateOnDate:(id)date;

@end

#endif /* MSVTaskAssertion_h */
