//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVTrialExperiment_h
#define MSVTrialExperiment_h
@import Foundation;
#include <os/lock.h>

@class TRIClient, TRIExperimentIdentifiers;

@interface MSVTrialExperiment : NSObject {
    /* instance variables */
    TRIClient *_trialClient;
    NSString *_namespaceName;
    TRIExperimentIdentifiers *_identifiers;
    _Bool _identifiersFetched;
    os_unfair_lock _lock;
}

@property(readonly, nonatomic) NSString *experimentID;
@property(readonly, nonatomic) NSString *treatmentID;
@property(readonly, nonatomic) NSString *deploymentID;

/* instance methods */
- (id)description;
- (void)invalidate;
- (id)identifiers;
- (void)refresh;
- (id)metadataForFactor:(id)factor;
- (id)stringForFactor:(id)factor;
- (_Bool)boolForFactor:(id)factor;
- (double)doubleForFactor:(id)factor;
- (id)initWithProjectID:(long long)id namespaceName:(id)name;
- (long long)longForFactor:(id)factor;

@end

#endif /* MSVTrialExperiment_h */
