//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVXPCTransaction_h
#define MSVXPCTransaction_h
@import Foundation;

@protocol OS_os_transaction;

@interface MSVXPCTransaction : NSObject {
    /* instance variables */
    NSUUID *_identifier;
    NSObject<OS_os_transaction> *_transaction;
    long long _transactionCount;
}

@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) _Bool active;

/* class methods */
+ (id)activeTransactions;

/* instance methods */
- (id)description;
- (id)initWithName:(id)name;
- (_Bool)isActive;
- (void)beginTransaction;
- (void)endTransaction;
- (void)endTransactionOnDate:(id)date;

@end

#endif /* MSVXPCTransaction_h */
