//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVXPCConnection_h
#define MSVXPCConnection_h
@import Foundation;

@interface MSVXPCConnection : NSXPCConnection

/* class methods */
+ (void)registerLocalListener:(id)listener withServiceName:(id)name;
+ (void)unregisterLocalListerWithName:(id)name;

/* instance methods */
- (id)initWithMachServiceName:(id)name options:(unsigned long long)options;
- (id)initWithServiceName:(id)name;

@end

#endif /* MSVXPCConnection_h */
