//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef MSVXPCListener_h
#define MSVXPCListener_h
@import Foundation;

@interface MSVXPCListener : NSXPCListener {
    /* instance variables */
    NSString *_registeredServiceName;
    NSXPCListener *_localProxy;
}

/* instance methods */
- (void)dealloc;
- (id)initWithMachServiceName:(id)name;
- (void)invalidate;
- (void)resume;
- (void)setDelegate:(id)delegate;
- (void)activate;
- (void)suspend;
- (id)localProxy;

@end

#endif /* MSVXPCListener_h */
