//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef NSIndexPath_MSVAdditions_h
#define NSIndexPath_MSVAdditions_h
@import Foundation;

@interface NSIndexPath (MSVAdditions)

/* class methods */
+ (id)msv_indexPathForItem:(long long)item inSection:(long long)section;

/* instance methods */
- (long long)msv_item;
- (long long)msv_section;

@end

#endif /* NSIndexPath_MSVAdditions_h */
