//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef NSObject_MSVDebugUtilities_h
#define NSObject_MSVDebugUtilities_h
@import Foundation;

@interface NSObject (MSVDebugUtilities)

/* instance methods */
- (id)__msv_inspect;
- (id)__msv_inspectWithOptions:(unsigned long long)options;
- (id)__msv_ivars;
- (id)__msv_methods;
- (id)__msv_objectDescription;
- (id)__msv_properties;

@end

#endif /* NSObject_MSVDebugUtilities_h */
