//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef NSString_MSVLyricsTTMLParser_h
#define NSString_MSVLyricsTTMLParser_h
@import Foundation;

#include "MSVLyricsSongInfo.h"
#include "MSVLyricsTextElement.h"

@protocol OS_dispatch_queue;

@interface NSString (MSVLyricsTTMLParser)

/* instance methods */
- (id)msv_stringByResolvingRealPath;
- (unsigned long long)msv_unsignedLongLongValue;
- (_Bool)msvl_isElementType:(id)type;
- (double)msvl_timeValue;

@end

#endif /* NSString_MSVLyricsTTMLParser_h */
