//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef NSURLSession_MSVTaskCapturingCompletion_h
#define NSURLSession_MSVTaskCapturingCompletion_h
@import Foundation;

@interface NSURLSession (MSVTaskCapturingCompletion)

/* instance methods */
- (id)msv_dataTaskWithRequest:(id)request completionHandler:(id /* block */)handler;
- (id)msv_downloadTaskWithRequest:(id)request completionHandler:(id /* block */)handler;
- (id)msv_uploadTaskWithRequest:(id)request
                       fromData:(id)data
              completionHandler:(id /* block */)handler;

@end

#endif /* NSURLSession_MSVTaskCapturingCompletion_h */
