//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef NSValue_MSVSignedRange_h
#define NSValue_MSVSignedRange_h
@import Foundation;

@interface NSValue (MSVSignedRange)

/* class methods */
+ (id)valueWithMSVSignedRange:(struct _MSVSignedRange {
    long long x0;
    long long x1;
})range;

/* instance methods */
- (struct _MSVSignedRange {
    long long x0;
    long long x1;
})signedRangeValue;

@end

#endif /* NSValue_MSVSignedRange_h */
