//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.508, BuildCommit: 5831334d9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.3, SDK: 14.3, Tool: ld (902.8)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.3, SDK: 17.3, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.340.1.0.0
//
#ifndef RBSAssertionObserving_Protocol_h
#define RBSAssertionObserving_Protocol_h
@import Foundation;

@protocol RBSAssertionObserving <NSObject>

@required

@optional

/* optional instance methods */
- (void)assertion:(id)assertion didInvalidateWithError:(id)error;
- (void)assertionWillInvalidate:(id)invalidate;

@end

#endif /* RBSAssertionObserving_Protocol_h */
